### ISSUE TITLE
add detail to project description

### ISSUE THREAD

**Issue by catawbasam** [jheinen/GR.jl#1]
Thanks for creating GR.jl.
At the moment, the package listing for GR (http://pkg.julialang.org/) doesn't provide much of a clue as to what GR is about: "No description available."

I believe it will pick up your project description when the listing is next updated, but that still won't provide any clues as to what GR is about: "The GR module for Julia:

How about a project description along the lines of: "Julia package for GR, a visualization framework"

**Comment by jheinen** [comment]
Thanks for your comment. I changed the project description on GitHub to "Julia package for GR, a visualization framework", but I don't know how to update the metadata information in the Julia packages repo.

**Comment by jheinen** [comment]
I'd like to use "Plotting for Julia based on GR, a framework for visualisation applications" for the package description, but I still don't know how to change the metadata information in the Julia packages repo.

**Comment by catawbasam** [comment]
I believe it should be using the GitHub repo description.  

However, that currently reads "The GR module for Julia" whereas the Julia package listing at http://pkg.julialang.org/ shows "No description available."  Not sure why.

cc: @IainNZ

**Comment by IainNZ** [comment]
The website updates automatically, by picking up the github repo description. However, it requires some manual intervention (basically running package update) to pick these up. Should be up in about an hour.

**Comment by jheinen** [comment]
Ok. I updated the repo description to "Plotting for Julia based on GR, a framework for visualisation applications". With the next package update, it should be picked up.
