### ISSUE TITLE
Legend not saved to png correctly

### ISSUE THREAD

**Issue by JackDunnNZ** [jheinen/GR.jl#100]
Any ideas on the following problem? When running the code

```julia
using GR
x = 1:10
y1 = rand(10)
y2 = rand(10)
legend("A", "B")
plot(x, y1, x, y2)
savefig("test.png")
```

The plot is correct in the window:

![image](https://user-images.githubusercontent.com/4717044/37535550-7034e896-291e-11e8-970f-8473f3bc098d.png)

But in the saved png the legend is incomplete:

![test](https://user-images.githubusercontent.com/4717044/37535590-8a955a9a-291e-11e8-92fe-ebe5bc25a8ad.png)

**Comment by FlorianRhiem** [comment]
Thank you for the bug report and sorry for the delayed response. This was an issue in the cairo plugin, it has been [fixed](https://github.com/sciapp/gr/commit/a97352a49a2215a77ef6949697516737a4c36290) in gr and the fix will be in the next GR.jl release.
