### ISSUE TITLE
Segfault on Travis Linux build

### ISSUE THREAD

**Issue by juliohm** [jheinen/GR.jl#101]
I am not 100% sure, but there is a consistent segfault on my Travis CI Linux build with a couple of GR-related traces:

https://travis-ci.org/juliohm/ImageInpainting.jl/jobs/357202750#L774-L791

I tried restarting the build, but the error persists. The build is successful on my local Linux laptop.

**Comment by jheinen** [comment]
The above Travis-CI link is dead!?

**Comment by juliohm** [comment]
Similar segmentation fault is happening in another package: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/367866431#L640

**Comment by juliohm** [comment]
I don't know if the issue is related to GR, I will close it and wait to see if it gets fixed by itself, or after Julia v0.7. Thanks.
