### ISSUE TITLE
Error: could not load library "libGR.dll"

### ISSUE THREAD

**Issue by marianaodio** [jheinen/GR.jl#102]
Hi! I'm having the following issue. I followed the steps to use GR: 

Pkg.add("GR")

and then try to run the simplest example: 

using GR
histogram(randn(10000))

But I get the following error. 

ERROR: error compiling _do_plot_show: error compiling _display: could not load library "libGR.dll"
The specified module could not be found.

Any suggestions to fix this? Thanks!

**Comment by jheinen** [comment]
What version of GR are you using?
```
using GR
version()
```
... and, what is the output of a package build command?
```
ENV["GRDIR"]=""
Pkg.build("GR")
```

**Comment by marianaodio** [comment]
When I try to see what version it gives me the following: 
"ERROR: error compiling version: could not load library "libGR.dll"
The specified module could not be found."

And the output of the package build command is: 
INFO: Building GR

**Comment by jheinen** [comment]
Please try:
```
Pkg.update()
ENV["GRDIR"]=""
Pkg.build("GR")
```
... which should download a binary GR run-time for Windows.

**Comment by marianaodio** [comment]
So, what I get is the same: 

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating GR master...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> ENV["GRDIR"]=""
""

julia> Pkg.build("GR")
INFO: Building GR

julia>

**Comment by jheinen** [comment]
Which platform are you using?
```
versioninfo()
```

**Comment by marianaodio** [comment]
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

**Comment by jheinen** [comment]
Is there probably an old `downloads` folder in the GR directory (`Pkg.dir("GR")`)? If so, please remove it ...

**Comment by marianaodio** [comment]
So I did Pkg.dir("GR"), I go to the path it gives me, but there's only one GR folder. Should I remove it?

**Comment by jheinen** [comment]
For any reason, the `build.jl` script is not downloading the GR run-time. It's hard for me to figure out why, as it works for me.

Could you check (by adding some debug statements in the `build.jl` script), what's going wrong?
This is the interesting part:
```
  if !isfile("downloads/$tarball")
    info("Downloading pre-compiled GR $version $os binary")
    url = "gr-framework.org/downloads/$tarball"
    file = "downloads/$tarball"
    mkpath("downloads")
    try
      download("https://$url", file)
    catch
      info("Using insecure connection")
      download("http://$url", file)
    end
    if os == :Windows
      success(`$JULIA_HOME/7z x downloads/$tarball -y`)
      rm("downloads/$tarball")
      tarball = tarball[1:end-3]
      success(`$JULIA_HOME/7z x $tarball -y -ttar`)
      rm("$tarball")
    else
      run(`tar xzf downloads/$tarball`)
      rm("downloads/$tarball")
    end
  end
```

Sorry for the trouble, but I have no other idea how to fix the problem ...

**Comment by jheinen** [comment]
That's the URL for the file you need:

`https://gr-framework.org/downloads/gr-latest-Windows-x86_64.tar.gz`

Does the download work on your Windows machine?

**Comment by marianaodio** [comment]
So I downloaded the file, and it said: 

INFO: Downloading pre-compiled GR 0.30.2 Windows binary

but nothing afterward. I don't know if I have to do something else with the file?

**Comment by jheinen** [comment]
If you get this message, then the build script would extract the archive in the correct location:
```
      success(`$JULIA_HOME/7z x downloads/$tarball -y`)
      rm("downloads/$tarball")
      tarball = tarball[1:end-3]
      success(`$JULIA_HOME/7z x $tarball -y -ttar`)
      rm("$tarball")
```
So you don't have to do anything else.

Is the problem finally fixed?

**Comment by marianaodio** [comment]
No, I didnt get that message. It got stuck in 
INFO: Downloading pre-compiled GR 0.30.2 Windows binary

and later nothing happened. If I do, 
julia> Pkg.build("GR")

 I still get 

INFO: Building GR
julia>

**Comment by jheinen** [comment]
For any reason, either the `download()` function or the `7z` command in Julia is no longer working as expected. I have no idea, why - the extracted `gr` directory is incomplete.

Unfortunately, I can't make further tests, as I have a very slow Internet connection.

@FlorianRhiem : Can you make some tests on your Windows VM (tomorrow)? I suspect some problem with `7z` (in `build.jl`) ...

**Comment by FlorianRhiem** [comment]
I have installed Julia 0.6 on a Windows 10 VM and installed GR using `Pkg.add("GR")`, which worked without any problems ([here's the log file](https://github.com/jheinen/GR.jl/files/1858820/julia_gr_log.txt)). Except for the CPU the versioninfo is identical.

@marianaodio What are the contents of your GR `deps` directory (e.g. `C:\Users\<Username>\.julia\v0.6\GR\deps` or find it via `Pkg.dir("GR")` and then the sub-directory `deps`)?

After I performed these steps for me the `deps` directory contains:
- `build.jl`
- `downloads` (empty directory)
- `gr` (containing `bin`, `fonts` and `include`, with `bin` containing all the DLLs)

After I manually deleted the `gr` sub-directory and ran `Pkg.build("GR")` I could watch the build script download the tarball, extract it to `gr` and then remove it again. In your case perhaps the `deps` directory contains the tarball (which would explain why it is not downloaded again), but no `gr` directory?

**Comment by jheinen** [comment]
Thanks @FlorianRhiem - that's how it should work.

My problems were probably caused by some weird behaviour on Windows:
- removing the `gr` directory using `DEL /S /Q /F` did not always work. I had to delete the files using `Explorer`
- In earlier tests, I had to remove temporary Internet files

I have absolutely no explanation for the latter, may be someone can tell me ...

**Comment by marianaodio** [comment]
So, I deleted any extra files in 'deps' directory and downloaded the gr file again and now it's working fine. Thank you so much for the help.
