### ISSUE TITLE
problem with: display(plot(...)) in win 8 and win 10

### ISSUE THREAD

**Issue by programistawpf** [jheinen/GR.jl#105]
Win 10, Win 8 Julia 0.6.2 using Plots ; gr()
plot(rand(5)) working ok !
A have problem with :

p1=plot(rand(5))
p2=plot(rand(5))
display(plot(p1,p2,layout=(2,1),wsize=(600,600)))

No plots, no window. In Win7 is ok!
Somebody using it ?
Paul

**Comment by jheinen** [comment]
This is my Win 10 result:
<img width="1342" alt="screen shot 2018-04-05 at 19 29 25" src="https://user-images.githubusercontent.com/5718244/38381693-e1569fd0-3907-11e8-933b-879a46451bff.png">
