### ISSUE TITLE
Where are samples with GR plots (without Plots)

### ISSUE THREAD

**Issue by programistawpf** [jheinen/GR.jl#106]
Where are samples with GR plots (without Plots) ? I am looking for more then https://gr-framework.org/julia-gr.html#GR
Paul

**Comment by jheinen** [comment]
https://github.com/jheinen/GR.jl/tree/master/examples

**Comment by programistawpf** [comment]
Thx, nice  !
P
W dniu 2018-04-05 o 19:32, Josef Heinen pisze:
