### ISSUE TITLE
Pkg.build broken on CentOS, download of GR fails

### ISSUE THREAD

**Issue by oschulz** [jheinen/GR.jl#110]
Hey @jheinen, sorry to bother you - Pkg.build is broken on CentOS again (the download of the GR binary fails):

```
LoadError: failed process: Process(`curl -L -f -o downloads/gr-0.31.0-Redhat-x86_64.tar.gz http://gr-framework.org/downloads/gr-0.31.0-Redhat-x86_64.tar.gz`, ProcessExited(22)) [22]
```

**Comment by mmikhasenko** [comment]
I have the same problem.

I noticed that at the `http://gr-framework.org/downloads/`
 - there no `gr-0.31.0-Redhat-x86_64.tar.gz`,
 - while there is `gr-0.31.0-CentOS-x86_64.tar.gz`

**Comment by mmikhasenko** [comment]
the line 40 of `.julia/v0.6/GR/deps/build.jl` to be changed to `os = "CentOS"`

**Comment by jheinen** [comment]
Sorry for the noise - it's fixed (and automated) now ....

**Comment by oschulz** [comment]
Thanks for the quick fix!
