### ISSUE TITLE
Pkg.add("GR")  Can't install on 32-bit Windows platform 

### ISSUE THREAD

**Issue by DuLiangMin** [jheinen/GR.jl#12]
julia> Pkg.add("GR")
INFO: Installing GR v0.9.14
JULIA_PKGDIR=O:\Julia-0.4.1\bin\..\share\julia\site
INFO: Building GR
INFO: Downloading pre-compiled GR 0.17.1 binary
=================================[ ERROR: GR ]==================================

LoadError: automatic download failed (error: 2148270086): http://gr-framework.or
g/downloads/gr-0.17.1-Windows-i686.tar.gz
while loading O:\Julia-0.4.1\share\julia\site\v0.4\GR\deps\build.jl, in expressi
on starting on line 11

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: GR had build errors.

 - packages with build errors remain installed in O:\Julia-0.4.1\share\julia\sit
e\v0.4
 - build the package(s) and all dependencies with `Pkg.build("GR")`
 - build a single package by running its `deps/build.jl` script

================================================================================

INFO: Package database updated
INFO: METADATA is out-of-date —— you may not have the latest version of GR
INFO: Use `Pkg.update()` to get the latest versions of your packages

**Comment by jheinen** [comment]
Sorry for the late answer. Right now, I could only provide you with a minimal GR distribution (without plugins), as I have migrated my build machine to Windows 10 64Bit.

**Comment by jheinen** [comment]
@DuLiangMin : starting with GR 0.19.0 Windows i686 is a supported platform.
