### ISSUE TITLE
yflip and xflip is not working for heatmap

### ISSUE THREAD

**Issue by Paethon** [jheinen/GR.jl#121]
It seems that the flipping options do not work for `heatmap`.

There is some discussion about this over at `Plots.jl`:
https://github.com/JuliaPlots/Plots.jl/issues/1491

It seems to work for some(most?) people but not for others(including me) and it is unclear why it fails.

For me, `yflip` and `xflip` flips the axis and (weirdly?) also the color legend, but not the actual image (e.g. if I set `xflip=true` the numbers of the color legend are shown on the left of the bar instead of the right). Using the Python library gives me the same result.

For example:

    heatmap(eye(10), xflip=true)
![2018-06-14-142426_681x570_scrot](https://user-images.githubusercontent.com/237550/41412049-11c50716-6fdf-11e8-837a-6a875e6fa1b8.png)

The image itself always looks like this independent what I set for `xflip` or `yflip`. Only the axes change.

Any idea what could cause this?

**Comment by jheinen** [comment]
Above problems should be fixed in GR master (https://github.com/jheinen/GR.jl/commit/b16a5da6fd7bca3855156a3e25a5e7556fd2b91c)

**Comment by Paethon** [comment]
That solved it. Thank you so much!
