### ISSUE TITLE
GR on 0.7.beta2, Win64

### ISSUE THREAD

**Issue by PaulSoderlind** [jheinen/GR.jl#125]
GR 0.31.0+ crashes on ```build GR``` if ```using LinearAlgebra, Compat``` has been executed just before. Somehow, with just ```using Compat```, it works, although with ```using Statistics, Compat``` it also crashes.

The error message starts with
```
 Error: Error building `GR`:
│ ERROR: LoadError: ArgumentError: Package Compat not found in current path:
│  - Run `Pkg.add("Compat")` to install the Compat package.
```

**Comment by PaulSoderlind** [comment]
Here it is:

``` 
ERROR: LoadError: ArgumentError: Package Compat not found in current path:
 - Run `Pkg.add("Compat")` to install the Compat package.

Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:816
 [2] include at .\boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1034
 [4] include at .\sysimg.jl:29 [inlined]
 [5] include_ifexists at .\client.jl:196 [inlined]
 [6] load_julia_startup() at .\client.jl:293
 [7] exec_options(::Base.JLOptions) at .\logging.jl:300
 [8] _start() at .\client.jl:427
in expression starting at C:\Users\psoderlind\.julia\config\startup.jl:8
```

I have noticed that the error only occurs when ```using LinearAlgebra, Compat``` is in the startup.jl file, not when issued in the REPL. Perhaps just a corner case that does not deserve attention.

**Comment by PaulSoderlind** [comment]
One more data point. Today Pkg3 updated my GR#master and the build failed once again. This time with the error message
> Building GR → `C:\Users\PaulS\.julia\packages\GR\Xx0in\deps\build.log`
> ┌ Error: Error building `GR`:
> │ ERROR: LoadError: ArgumentError: Package Statistics not found in current path:
> │ - Run `Pkg.add("Statistics")` to install the Statistics package.

This sort of squares with my previous observation, since now my startup.jl includes (among other things)
`using Statistics,`

As before, by deleting this from the startup.jl, GR builds nicely.

**Comment by jheinen** [comment]
This problem is not related to GR. Loading modules in `startup.jl` causes problems with other packages, too.
