### ISSUE TITLE
Output directly to png

### ISSUE THREAD

**Issue by sje30** [jheinen/GR.jl#127]
Hi
sorry for the obvious question, but how do I save a plot direct to a png, rather than have it appear in an X window first?

```
using(GR)
histogram(rand(999))
savefig('output.png')
```
In the above, this first shows the plot in an X window on my linux system, and then saves to output.png, but what I'd like (e.g. within a docker container) is to not have an X session first.  Is this possible?  (In R, the equivalent might be:

```
png(file='out.png')
plot(1:10)
dev.off()
```

**Comment by jheinen** [comment]
If you are in a console environment, you could use a simple shell script (`julia`):
```bash
#!/bin/sh
juliadir=/usr/local/julia

if [ "$1" = "-o" ]
then
  shift
  if [ "`echo $1 | grep '\.'`" != "" ]
  then
    type=`echo $1 | awk -F. '{print $NF}'`
    export GKS_FILEPATH="$1"
    export GKS_WSTYPE="$type"
  else
    export GKS_WSTYPE="$1"
  fi
  shift
fi
exec ${juliadir}/bin/julia "$@"
```
... and call it with the desired output file, e.g.:
```bash
julia -o output.png ...
```

**Comment by jheinen** [comment]
You probably want something like this:
```julia
using GR

x = collect(0:0.01:2*pi)

ENV["GKS_WSTYPE"] = 100
for i = 1:200
    plot(x, sin.(x + i / 10.0))
    savefig("output" * string(i) * ".png")
end
```
For an animation, you could try:
```julia
beginprint("anim.mov")
figure(size=(800,600))
for i = 1:200
    plot(x, sin.(x + i / 10.0))
end
endprint()
```

**Comment by sje30** [comment]
Thanks, this is perfect, as it means all I need to add is the ENV line to my scripts.

By the way, what is code 100?  https://gr-framework.org/about.html doesn't list 100.
