### ISSUE TITLE
'could not load library "libGR.so"' error with Julia 1.0 and GR 0.32.3 

### ISSUE THREAD

**Issue by sjmgarnier** [jheinen/GR.jl#133]
The full error message is below. 

> ERROR: LoadError: error compiling _plot!: error compiling _display: could not load library "libGR.so"
dlopen(libGR.so.dylib, 1): image not found
Stacktrace:
 [1] #plot#134(::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:zcolor, :group, :legend),Tuple{Array{Float64,1},Array{Float64,1},Bool}}}, ::Function, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N} whereN) at /Users/simon/.julia/packages/Plots/LWBTU/src/plot.jl:57
 [2] (::getfield(RecipesBase, Symbol("#kw##plot")))(::NamedTuple{(:zcolor, :group, :legend),Tuple{Array{Float64,1},Array{Float64,1},Bool}}, ::typeof(plot), ::Array{Float64,1}, ::Array{Float64,1}) at ./none:0
 [3] top-level scope at none:0
 [4] include_string(::Module, ::String, ::String) at ./loading.jl:1002
 [5] include_string(::Module, ::String, ::String, ::Int64) at /Users/simon/.julia/packages/CodeTools/8CjYJ/src/eval.jl:30
 [6] (::getfield(Atom, Symbol("##100#105")){String,Int64,String})() at /Users/simon/.julia/packages/Atom/jJn7Y/src/eval.jl:60
 [7] withpath(::getfield(Atom, Symbol("##100#105")){String,Int64,String}, ::String) at /Users/simon/.julia/packages/CodeTools/8CjYJ/src/utils.jl:30
 [8] withpath at /Users/simon/.julia/packages/Atom/jJn7Y/src/eval.jl:46 [inlined]
 [9] #99 at /Users/simon/.julia/packages/Atom/jJn7Y/src/eval.jl:58 [inlined]
 [10] hideprompt(::getfield(Atom, Symbol("##99#104")){String,Int64,String}) at /Users/simon/.julia/packages/Atom/jJn7Y/src/repl.jl:76
 [11] macro expansion at /Users/simon/.julia/packages/Atom/jJn7Y/src/eval.jl:57 [inlined]
 [12] (::getfield(Atom, Symbol("##98#103")){Dict{String,Any}})() at ./task.jl:85
in expression starting at /Users/simon/Google Drive/NJIT/Work/research/others/vikram/julia/run.jl:13

**Comment by jheinen** [comment]
Please rebuild GR:
```julia
ENV["GRDIR"]=""
Pkg.build("GR")
```
This should download the GR run-time libraries (including libGR.so.dylib) again.

**Comment by sjmgarnier** [comment]
@jheinen Thanks! It worked.

**Comment by PacificBase** [comment]
@jheinen I tried this,
`ENV["GRDIR"]=""
Pkg.build("GR")`
but it doesn't work, my Julia version is v0.7.0.
So, why and how to address it?

**Comment by jheinen** [comment]
Is it a typo or did you omit the semicolon?
```
ENV["GRDIR"]=""; Pkg.build("GR")
```

**Comment by PacificBase** [comment]
it isn't a typo, i,e. I omit the semicolon. So, I tried 
'ENV["GRDIR"]=""; Pkg.build("GR")' again. There is same error
-----------------------------------------------------------------------------------------
`ERROR: error compiling #plot#19: error compiling plot_data:
error compiling send_meta: error compiling openmeta: could not load library "libGR.dll"
The specified module could not be found.`
-------------------------------------------------------------------------------------------

**Comment by PacificBase** [comment]
it isn't a typo, i,e. I omit the semicolon. So, I tried
'ENV["GRDIR"]=""; Pkg.build("GR")' again. There is same error

ERROR: error compiling #plot#19: error compiling plot_data: error compiling send_meta: error compiling openmeta: could not load library "libGR.dll" The specified module could not be found.

**Comment by PacificBase** [comment]
The library that Julia always load is "libGR.dll", but that's "libgr.dll" in the  `C:\Users\Administrator\.julia\packages\GR\fnyt8\deps\downloads\gr-0.32.0-Windows-x86_64.tar.gz`. It's different. So , in my opinion, maybe this's the key to the issue.

**Comment by jheinen** [comment]
Could you please try to rename `libgr.dll` to `libGR.dll` (same for `libgks.dll`)?
If his fixes the problem, we will have to change the file names in our distribution ...

**Comment by PacificBase** [comment]
Sorry, it doesn't work. Besides, the zip file can't  decompress completely. The error blog says there is a error in the end of file.  So, I don't have `lidgks.dll`, and I tried rebuild again and again, unfortunately, the zip file is same.

**Comment by jheinen** [comment]
Can you manually unzip (using Julia's 7z)?

```bash
7z x gr-0.32.0-Windows-x86_64.tar.gz
...
7z x gr-0.32.0-Windows-x86_64.tar -ttar
...
Extracting  gr
Extracting  gr/fonts
Extracting  gr/fonts/NimbusMonL-BoldObli.afm
Extracting  gr/fonts/NimbusRomNo9L-ReguItal.pfb
Extracting  gr/fonts/URWPalladioL-BoldItal.afm
Extracting  gr/fonts/NimbusSanL-Regu.afm
Extracting  gr/fonts/NimbusRomNo9L-Medi.afm
Extracting  gr/fonts/URWBookmanL-Ligh.afm
Extracting  gr/fonts/CenturySchL-BoldItal.afm
Extracting  gr/fonts/NimbusSanL-Bold.afm
Extracting  gr/fonts/NimbusSanL-BoldItal.afm
Extracting  gr/fonts/CenturySchL-Bold.pfb
Extracting  gr/fonts/URWBookmanL-DemiBoldItal.afm
Extracting  gr/fonts/NimbusSanL-BoldItal.pfb
Extracting  gr/fonts/URWBookmanL-Ligh.pfb
Extracting  gr/fonts/URWPalladioL-Roma.afm
Extracting  gr/fonts/NimbusRomNo9L-MediItal.afm
Extracting  gr/fonts/NimbusSanL-BoldCond.afm
Extracting  gr/fonts/NimbusRomNo9L-Medi.pfb
Extracting  gr/fonts/URWGothicL-Demi.afm
Extracting  gr/fonts/NimbusRomNo9L-MediItal.pfb
Extracting  gr/fonts/NimbusSanL-BoldCond.pfb
Extracting  gr/fonts/NimbusSanL-ReguCondItal.pfb
Extracting  gr/fonts/NimbusMonL-Regu.pfb
Extracting  gr/fonts/URWPalladioL-Ital.afm
Extracting  gr/fonts/URWPalladioL-Roma.pfb
Extracting  gr/fonts/NimbusSanL-BoldCondItal.afm
Extracting  gr/fonts/NimbusSanL-ReguItal.pfb
Extracting  gr/fonts/URWBookmanL-DemiBoldItal.pfb
Extracting  gr/fonts/CenturySchL-Ital.pfb
Extracting  gr/fonts/gksfont.dat
Extracting  gr/fonts/NimbusMonL-ReguObli.pfb
Extracting  gr/fonts/StandardSymL.afm
Extracting  gr/fonts/NimbusSanL-ReguCondItal.afm
Extracting  gr/fonts/URWGothicL-DemiObli.afm
Extracting  gr/fonts/NimbusMonL-BoldObli.pfb
Extracting  gr/fonts/URWBookmanL-LighItal.pfb
Extracting  gr/fonts/CenturySchL-Roma.afm
Extracting  gr/fonts/NimbusRomNo9L-Regu.pfb
Extracting  gr/fonts/CenturySchL-Bold.afm
Extracting  gr/fonts/URWBookmanL-DemiBold.afm
Extracting  gr/fonts/CenturySchL-Roma.pfb
Extracting  gr/fonts/URWGothicL-Book.afm
Extracting  gr/fonts/URWGothicL-BookObli.afm
Extracting  gr/fonts/URWChanceryL-MediItal.afm
Extracting  gr/fonts/CenturySchL-Ital.afm
Extracting  gr/fonts/NimbusMonL-Bold.pfb
Extracting  gr/fonts/URWPalladioL-Ital.pfb
Extracting  gr/fonts/URWPalladioL-Bold.afm
Extracting  gr/fonts/NimbusSanL-ReguItal.afm
Extracting  gr/fonts/URWGothicL-BookObli.pfb
Extracting  gr/fonts/NimbusSanL-Bold.pfb
Extracting  gr/fonts/URWPalladioL-Bold.pfb
Extracting  gr/fonts/NimbusMonL-Regu.afm
Extracting  gr/fonts/URWGothicL-DemiObli.pfb
Extracting  gr/fonts/URWPalladioL-BoldItal.pfb
Extracting  gr/fonts/Dingbats.pfb
Extracting  gr/fonts/URWChanceryL-MediItal.pfb
Extracting  gr/fonts/Dingbats.afm
Extracting  gr/fonts/NimbusMonL-Bold.afm
Extracting  gr/fonts/NimbusSanL-ReguCond.pfb
Extracting  gr/fonts/NimbusRomNo9L-Regu.afm
Extracting  gr/fonts/NimbusMonL-ReguObli.afm
Extracting  gr/fonts/URWBookmanL-LighItal.afm
Extracting  gr/fonts/URWGothicL-Demi.pfb
Extracting  gr/fonts/NimbusSanL-ReguCond.afm
Extracting  gr/fonts/NimbusSanL-Regu.pfb
Extracting  gr/fonts/URWBookmanL-DemiBold.pfb
Extracting  gr/fonts/StandardSymL.pfb
Extracting  gr/fonts/CenturySchL-BoldItal.pfb
Extracting  gr/fonts/URWGothicL-Book.pfb
Extracting  gr/fonts/NimbusSanL-BoldCondItal.pfb
Extracting  gr/fonts/NimbusRomNo9L-ReguItal.afm
Extracting  gr/bin
Extracting  gr/bin/zmqplugin.dll
Extracting  gr/bin/cairoplugin.dll
Extracting  gr/bin/libstdc++-6.dll
Extracting  gr/bin/wmfplugin.dll
Extracting  gr/bin/Qt5Widgets.dll
Extracting  gr/bin/libGLESv2.dll
Extracting  gr/bin/Qt5Network.dll
Extracting  gr/bin/libgr.dll
Extracting  gr/bin/qt5plugin.dll
Extracting  gr/bin/libgcc_s_dw2-1.dll
Extracting  gr/bin/d3dcompiler_47.dll
Extracting  gr/bin/htmplugin.dll
Extracting  gr/bin/gtkplugin.dll
Extracting  gr/bin/libgcc_s_sjlj-1.dll
Extracting  gr/bin/gksqt.exe
Extracting  gr/bin/svgplugin.dll
Extracting  gr/bin/platforms
Extracting  gr/bin/platforms/qwindows.dll
Extracting  gr/bin/Qt5Gui.dll
Extracting  gr/bin/libGLESv2d.dll
Extracting  gr/bin/libgks.dll
Extracting  gr/bin/libGR3.dll
Extracting  gr/bin/Qt5Core.dll
Extracting  gr/bin/gsplugin.dll
Extracting  gr/bin/pgfplugin.dll
Extracting  gr/bin/movplugin.dll
Extracting  gr/bin/figplugin.dll
Extracting  gr/bin/wxplugin.dll
Extracting  gr/bin/glplugin.dll
Extracting  gr/bin/libwinpthread-1.dll
Extracting  gr/bin/qtplugin.dll
Extracting  gr/bin/libgcc_s_seh-1.dll
Extracting  gr/include
Extracting  gr/include/gr3.h
Extracting  gr/include/gr.h
Extracting  gr/include/gks.h
Extracting  gr/include/grwidget.h

Everything is Ok

Folders: 5
Files: 106
Size:       219911112
Compressed: 219996160
```

**Comment by PacificBase** [comment]
It doesn't work... I'm sorry, i'm going to back Julia 0.6.4 and wait new version which can address this problem. Thanks you very much again. Waiting your new version. 
by the way, if you find out the answer, could you tell me? Thanks!

**Comment by jheinen** [comment]
As a workaround you could copy the `GR.jl/deps/gr` tree from your working 0.6.4 installation into the 1.0 environment.

**Comment by PacificBase** [comment]
Finally， it does work! This problem is simple. `build GR` lasted a very long time, always be `Building` at least one hour,  which let me feels my Julia's console is dead. So I stopped it before building finish.  Anyway， It does work.  Thank you so much for helping me.

**Comment by metorm** [comment]
Guys, I found the problem, which is actually triggered by an unsteady network.

In `~/.julia/packages/GR/joQgG/deps/downloads`, there would be tempory file `gr-0.34.1-Linux-x86_64.tar.gz`, which is downloaded from `gr-framework.org` during installation. However, the file would be broken if a network error (or perhaps a user canceling operation) happens. The next time you try to rebuild GR, the broken file prevents the building script from downloading the file again.

To fix the error, the user can delete the `gr-0.34.1-Linux-x86_64.tar.gz` file manually.
For the developers, I think a checksum operation shall be added to the procedure. @jheinen

**Comment by WangWei90** [comment]
I agree with @metorm . In China, the network is really unsteady (especially for Github nowadays).

**Comment by atodniAr** [comment]
> Guys, I have located the problem, which is actually triggered by an unsteady network.
> 
> In `~/.julia/packages/GR/joQgG/deps/downloads`, there would be tempory file `gr-0.34.1-Linux-x86_64.tar.gz`, which is downloaded from `gr-framework.org` during installation. However, the file would be broken if a network error (or perhaps a user canceling operation) happens. The next time you try to rebuild GR, the broken file prevents the building script from downloading the file again.
> 
> To fix the error, the user can delete the `gr-0.34.1-Linux-x86_64.tar.gz` file manually and `build GR` again.
> For the developers, I think a checksum operation shall be added to the procedure. @jheinen

Same thing happened for me. My kernel interrupted while downloading gr zip file, which caused the error. Solved after removing tempory file and build again.

**Comment by eirikeb** [comment]
I had the same problem, but my `~/.julia/packages/GR/joQgG/deps/downloads` folder was completely empty. I fixed it by simply deleting the entire GR folder (e.g. `rm -r GR/*) and then rebooting Julia, `] add GR` after which the issue was fixed.

**Comment by metorm** [comment]
So, the dowload/build status is also saved some where else ...



发自我的小米手机
在 Eirik Eylands Brandås <notifications@github.com>，2018年11月14日 02:18写道：

I had the same problem, but my ~/.julia/packages/GR/joQgG/deps/downloads folder was completely empty. I fixed it by simply deleting the entire GR folder (e.g. rm -r GR/*) and then rebooting Julia, ] add GR` after which the issue was fixed.

**Comment by VCVina** [comment]
Oh...My computer can't build this.When I run it:

```julia
using Pkg
ENV["GRDIR"]=""
Pkg.build("GR")
```

It will become ‘Building GR → `~/.julia/packages/GR/IVBgs/deps/build.log`’ and BUILD this forever, May I ask how to solve this?

> Please rebuild GR:
> 
> ```julia
> ENV["GRDIR"]=""
> Pkg.build("GR")
> ```
>
> This should download the GR run-time libraries (including libGR.so.dylib) again.

**Comment by jheinen** [comment]
Which platform are you using?
```julia
versioninfo()
```

**Comment by VCVina** [comment]
Julia Version 1.1.0 for macOS Mojave 10.14.3.

**Comment by jheinen** [comment]
macOS is what we use. Please try to `rm` the `deps` directory and update `GR`.

**Comment by VCVina** [comment]
Thank you for your tip but I think it can't work...
Maybe I'm not skilled enough, I was directly drop the `deps` into trash can by Finder and try to do this↓
```julia
(v1.1) pkg> update GR
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.1/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.1/Manifest.toml`
 [no changes]
```
it seems that there is no change? 

(sorry for being a novice...)

**Comment by jheinen** [comment]
So he does the system really start `build`ing GR? If so, is there a `build.log` file?

**Comment by VCVina** [comment]
No, the `build.log` file isn't exist.

Exactly, After I dropped the `deps` folder and finished`pkg> update GR` , the `deps` was still not exist.

And I tried to do Pkg.build("GR") again and it can't work, the `deps` still does not exist, but I think this is for sure because the `build.jl` does not exist
![image](https://user-images.githubusercontent.com/28703833/54399987-ed17b400-46fb-11e9-9fcf-11eb1b65479e.png)

**Comment by VCVina** [comment]
@jheinen oh, I think I solved this problem!

Actually, this is the network problem, when I build this i can't download the package so this becomes an infinite loop of work, i tried to use proxy and it does work!
I'm so sorry for spending you so much time for my bad network environment in China.

**Comment by alexeypetrushin** [comment]
Maybe it's worth to re-open this issue and fix the problem properly?
Solution like "rebuild GR" does not sounds like a robust and stable way to install and manage packages.

**Comment by jheinen** [comment]
What happens if you `] build GR` ?

**Comment by alexeypetrushin** [comment]
I solved the issue, by executing the script below, as you suggested in comment above,  thanks.

My point is that requiring the user intervention for such an ordinary and common task as a installing package should not be counted as an acceptable solution. In my opinion it's a sign of a deeper problem with the package manager that should be addressed.

```
ENV["GRDIR"]=""
Pkg.build("GR")
```

**Comment by kkkllli** [comment]
Hi,
I tried 
ENV["GRDIR"]=""
Pkg.build("GR")

but it does not work. I am not sure whether it is a network problem. Could you please tell me what else I can do? Thank you so much! By the way, it reports:
┌ Error: Error building `GR`: 
│ [ Info: Downloading pre-compiled GR latest Windows binary
│ ┌ Error: Download failed: curl: (22) The requested URL returned error: 404 Not Found
│ └ @ Base download.jl:43
│ ERROR: LoadError: IOError: could not spawn `'C:\Users\Xiaomei\AppData\Local\Julia-1.3.0\bin/7z' x downloads/gr-latest-Windows-x86_64.tar.gz -y`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at .\process.jl:99
│  [2] setup_stdios(::Base.var"#554#555"{Cmd}, ::Array{Any,1}) at .\process.jl:112
│  [3] success(::Cmd) at .\process.jl:111
│  [4] top-level scope at C:\Users\Xiaomei\.julia\packages\GR\ZI5OE\deps\build.jl:119
│  [5] include at .\boot.jl:328 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1105
│  [7] include(::Module, ::String) at .\Base.jl:31
│  [8] include(::String) at .\client.jl:424
│  [9] top-level scope at none:5
│ in expression starting at C:\Users\Xiaomei\.julia\packages\GR\ZI5OE\deps\build.jl:68
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\backwards_compatible_isolation.jl:649

**Comment by jheinen** [comment]
Something seems to block thew download on **your** side.

You correspinding download is Julia is realized with `curl -O https://gr-framework.org/downloads/gr-latest-Windows-x86_64.tar.gz`, which works fine.

**Comment by kkkllli** [comment]
Could you please be more specific about &nbsp;anything I can try to fix this problem? Thank you so much!


------------------ Original ------------------

**Comment by jheinen** [comment]
"Something" means, that there is probably a firewall or protection system on **your** side. We don't filter anything on our side. If you have access to a Unix system, please try the above `curl` command.

What happens, if you try to download the required run-time in you browser? ([Link](https://gr-framework.org/downloads/gr-latest-Windows-x86_64.tar.gz))

**Comment by kkkllli** [comment]
I download the required run-time in my browser as you recommended but it cannot work.
I do not have Unix system. I also find that the package problem is not only in GR(please see the attached screenshots). Does it mean I have some problem in my computer setup? What should I do to solve it? Thank you so much!




------------------&nbsp;Original&nbsp;------------------

**Comment by jheinen** [comment]
Did you install the recommended Windows Management Framework, as described [here](https://julialang.org/downloads/platform.html). I seem to remember that without this run-time, you can't use the Julia `download()` command ...

**Comment by adnandal10ster** [comment]
> Please rebuild GR:
> 
> ```julia
> ENV["GRDIR"]=""
> Pkg.build("GR")
> ```
> 
> This should download the GR run-time libraries (including libGR.so.dylib) again.

This worked for me!!

**Comment by fonsp** [comment]
I also got this issue on a **clean** Ubuntu 20.04 machine with Julia 1.4.2. GR 0.49.1 was installed indirectly, as a dependency of Plots. (The suggested fix worked.)

**Comment by DeathGodBXX** [comment]
import Pkg;Pkg.build("GR")
     Building GR → `~/.julia/packages/GR/8mv9N/deps/build.log` 
After 10 minutes,it doesn't show any prompt ,it seems blocked, what should I do?

**Comment by DeathGodBXX** [comment]
my julia version is 1.4.1,I downloaded julia from  [https://mirrors.ustc.edu.cn/julia](url)

**Comment by jheinen** [comment]
What's the content of `~/.julia/packages/GR/8mv9N/deps/build.log` ?

**Comment by DeathGodBXX** [comment]
There is nothing. In China,Maybe my client don't connect with foreign server.So I plan to download binaries  from  [https://mirrors.bfsu.edu.cn/julia/static/](url) and add it to some place.

**Comment by DeathGodBXX** [comment]
sloved! just Spend much time building logfiles.I have to say it's too slow.But in a word,thanks author

**Comment by rubyFeedback** [comment]
Google brought me here; unfortunately I still have no idea where libGR.so is. I assume it is
part of some library but I can not find it, also because of issues like this here mentioning
it but not explaining what it is. :(

**Comment by jheinen** [comment]
What's the content of the GR run-time library (`lib`) directory? 
```
using GR
readdir(joinpath(ENV["GRDIR"], "lib"))
```

**Comment by crstnbr** [comment]
I'm seeing this as well (on Julia 1.6 and GR v0.55.0):

```Julia
julia> using GR

julia> readdir(joinpath(ENV["GRDIR"], "lib"))
21-element Vector{String}:
 "cairoplugin.so"
 "glplugin.so"
 "gr.js"
 "gsplugin.so"
 "gtkplugin.so"
 "libGKS.so"
 "libGR.so"
 "libGR3.so"
 "libGR3platform.so"
 "libGRM.so"
 "libqt4gr.so"
 "libqt5gr.so"
 "pgfplugin.so"
 "qt5plugin.so"
 "qtplugin.so"
 "svgplugin.so"
 "videoplugin.so"
 "wmfplugin.so"
 "wxplugin.so"
 "x11plugin.so"
 "zmqplugin.so"

julia> histogram(randn(10000))
ERROR: could not load library "libGR.so"
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /projects/ag-trebst/bauer/.julia/packages/GR/9Vi4m/src/../deps/gr/lib/libGR.so)
Stacktrace:
 [1] clearws
   @ /projects/ag-trebst/bauer/.julia/packages/GR/9Vi4m/src/GR.jl:536 [inlined]
 [2] plot_data(flag::Bool)
   @ GR.jlgr /projects/ag-trebst/bauer/.julia/packages/GR/9Vi4m/src/jlgr.jl:1120
 [3] plot_data
   @ /projects/ag-trebst/bauer/.julia/packages/GR/9Vi4m/src/jlgr.jl:1097 [inlined]
 [4] histogram(x::Vector{Float64}; kv::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ GR.jlgr /projects/ag-trebst/bauer/.julia/packages/GR/9Vi4m/src/jlgr.jl:1896
 [5] histogram
   @ /projects/ag-trebst/bauer/.julia/packages/GR/9Vi4m/src/jlgr.jl:1890 [inlined]
 [6] #histogram#11
   @ /projects/ag-trebst/bauer/.julia/packages/GR/9Vi4m/src/GR.jl:3502 [inlined]
 [7] histogram(x::Vector{Float64})
   @ GR /projects/ag-trebst/bauer/.julia/packages/GR/9Vi4m/src/GR.jl:3502
 [8] top-level scope
   @ REPL[3]:1
```

**Comment by CosmosJG** [comment]
Hi, I have similar problem when I try to use 'Triplot'.  May I ask you about this problem?
I uses Julia version 1.5.3 using Juno on MacOS (M1 version). 


I've got this error message, 

ERROR: LoadError: could not load library "libGR.so"
dlopen(libGR.so.dylib, 1): image not found
Stacktrace:
 [1] inqdspsize() at /Users/jonggilpark/.julia/packages/GR/yMV3y/src/GR.jl:351
 [2] rasterize(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Int64,2}; yflip::Bool, px::Nothing, py::Nothing, zmin::Nothing, zmax::Nothing) at /Users/jonggilpark/.julia/packages/Triplot/KEf9c/src/tripcolor.jl:20
 [3] rasterize at /Users/jonggilpark/.julia/packages/Triplot/KEf9c/src/tripcolor.jl:20 [inlined]
 [4] triplot(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Int64,2}) at /Users/jonggilpark/Desktop/Code_Julia/TriFEMUtils.jl:13
 [5] top-level scope at /Users/jonggilpark/Desktop/Code_Julia/Park.jl:101
 [6] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
in expression starting at /Users/jonggilpark/Desktop/Code_Julia/Park.jl:101



I already tried ENV["GRDIR"]=""; Pkg.build("GR), but there was no changes.
 
julia> ENV["GRDIR"]=""
""
julia> Pkg.build("GR")
   Building GR → `~/.julia/packages/GR/yMV3y/deps/build.log`
julia> 




Also, based on your last comments on Feb 2, I tried to do "using GR", but the following came out. 

julia> using GR
WARNING: using GR.meshgrid in module Main conflicts with an existing identifier.
WARNING: using GR.plot in module Main conflicts with an existing identifier.

May I ask you any comments or advice on this??

**Comment by jheinen** [comment]
Did you try to restart Julia and update all packages?

**Comment by CosmosJG** [comment]
Yes, I restarted Julia and updated all packages by "add Packagename" . 
But it has still same issue.

**Comment by jheinen** [comment]
But it seems to me, that you are using an old GR version, as the library name is `libGR.dylib` in the meantime (since v0.54.0, which was already released in January)

**Comment by CosmosJG** [comment]
Is there any other method to update packages? I just entered "Pkg.add [Package name]" on REPL. 
(Sorry, I am still a beginner..)

**Comment by jheinen** [comment]
`Pkg.update()` or `] update`

**Comment by CosmosJG** [comment]
I just tried it now, but I get the same error. 
On the other page, I saw that Package Triplot is a pretty old package. Could that be the reason for that issue?

**Comment by bwanab** [comment]
This is weird. I've been using 1.7.3 since it arrived. I use plotting every day. I haven't changed configurations or anything, but this morning I sat down to do some work and got this on the first Pluto notebook I opened:

Failed to show value:
could not load library "libGR.so"
dlopen(libGR.so.dylib, 0x0001): tried: '/Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libGR.so.dylib' (no such file), ....

Following the advice in this thread I've tried:

1. ENV["GRDIR"] = ""
   Pkg.build("GR")

This didn't help.

2. restart Julia, then ] update

Still same problem.

Here is the output from:

julia> using GR

julia> readdir(joinpath(ENV["GRDIR"], "lib"))
23-element Vector{String}:
 "aggplugin.so"
 "cairoplugin.so"
 "glplugin.so"
 "gr.js"
 "gsplugin.so"
 "gtkplugin.so"
 "libGKS.dylib"
 "libGR.dylib"
 "libGR3.dylib"
 "libGRM.dylib"
 "libqt5gr.dylib"
 "libqt6gr.dylib"
 "pgfplugin.so"
 "qt5plugin.so"
 "qt6plugin.so"
 "qtplugin.so"
 "quartzplugin.so"
 "svgplugin.so"
 "videoplugin.so"
 "wmfplugin.so"
 "wxplugin.so"
 "x11plugin.so"
 "zmqplugin.so"

So, it appears that I've got libGR.dylib, but the message says it's missing libGR.so.dylib.

I've got no idea what could have happened.

**Comment by jheinen** [comment]
Unfortunately, I can't reproduce the problem. Could you try the following command to see, if there is a system-wide problem?

```
otool -L `find ${HOME}/.julia -name libGR.dylib`
```

Or, could you temporarily rename your `${HOME}/.julia` directory and `] add GR` in a new session?
