### ISSUE TITLE
Feature requests: subplots, legend, hold

### ISSUE THREAD

**Issue by rveltz** [jheinen/GR.jl#14]
Hi,

I have been using your module recently and it is formidable.
I have some feature requests I hope you can easily add.
1) My first one would be to have hold function (as in Matlab).
2) Also, I would like to be able to use subplots like in pylab/matlab.
3) A savefig function would be very usefull (this is quite simple to do actually)
4) Finally, I can't find a legend function for GR.plot

These features would simplify the production of publishable figures,

Thank you for your help and your hard work,

Best regards,

Rom1

**Comment by jheinen** [comment]
As I am currently also working on a backend for Plots.jl, most of your feature requests will be met in the "near future" :-). My plan is, to implement those features in GR's libraries (instead of writing different wrappers) if possible - so these things can be used both in Julia and Python (and probably other languages).

**Comment by rveltz** [comment]
OK, thank you.

**Comment by rveltz** [comment]
Hi,
Did you manage to add the subplot functionality?
Best regards,
Romain

**Comment by jheinen** [comment]
I just added support for subplots (6285b36) - but I'll have to make further tests before making a PR.

**Comment by rveltz** [comment]
Sweet! Is it in the main package, Pkg.add() would add this function or is it another branch?

Thank you a lot

**Comment by jheinen** [comment]
To use the new features, you should checkout the master branch: ``Pkg.checkout("GR")``. I will add more functions (along with a quick tutorial) this weekend ...

**Comment by rveltz** [comment]
Hi,

I still cannot see the function GR.subplot not GR.jlgr.subplot?

Maybe this can give you a hint:

Pkg.status("GR")
 - GR                            0.9.16+            master

Thank you for your help,

Romain

**Comment by rveltz** [comment]
sorry, it works now!
Great!

**Comment by rveltz** [comment]
Hi,

When using subplot, it seems that the legend and title attributed at each subplot disappear. Is it normal?

Thank you,

**Comment by jheinen** [comment]
... has been fixed in the meanwhile.
