### ISSUE TITLE
Windows build error on julia 0.7

### ISSUE THREAD

**Issue by crbinz** [jheinen/GR.jl#140]
I ran into (I think) [this problem](https://github.com/jheinen/GR.jl/issues/137), then tried to build `GR`, as suggested:

```julia
(v0.7) pkg> build GR
  Building GR → `C:\Users\cbinz\.julia\packages\GR\fnyt8\deps\build.log`
┌ Error: Error building `GR`:
│ ERROR: LoadError: ArgumentError: Package Pkg not found in current path:
│ - Run `Pkg.add("Pkg")` to install the Pkg package.
│
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at .\loading.jl:817
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1038
│  [4] include at .\sysimg.jl:29 [inlined]
│  [5] include_ifexists at .\client.jl:201 [inlined]
│  [6] load_julia_startup() at .\client.jl:298
│  [7] exec_options(::Base.JLOptions) at .\logging.jl:312
│  [8] _start() at .\client.jl:432
│ in expression starting at C:\Users\cbinz\.julia\config\startup.jl:1
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068
```

I do `]add Pkg`, which does nothing, then unsurprisingly I get the same error with `]build GR`.

I'm using the julia 0.7 release on 64-bit Windows 7.

**Comment by jheinen** [comment]
You have to temporarily disable/remove your startup file. This is not a problem of GR. There were other users having the same problem (with other packages), too.

**Comment by johannspies** [comment]
I get the same error on  Linux 4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux with Julia 1.0.0 and Version 1.1.0-DEV.72 (2018-08-20):

` 
 Building GR → `~/.julia/packages/GR/Oatug/deps/build.log`
┌ Error: Error building `GR`: 
│ ERROR: LoadError: ArgumentError: Package Pkg not found in current path:
│ - Run `Pkg.add("Pkg")` to install the Pkg package.
│ 
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at ./loading.jl:817
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include at ./sysimg.jl:29 [inlined]
│  [5] include_ifexists at ./client.jl:191 [inlined]
│  [6] load_julia_startup() at ./client.jl:288
│  [7] exec_options(::Base.JLOptions) at ./logging.jl:312
│  [8] _start() at ./client.jl:421
│ in expression starting at /home/js/.julia/config/startup.jl:1
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

`

**Comment by johannspies** [comment]
Solved by following [this](https://discourse.julialang.org/t/plotting-packages-that-support-julia-v1-0/14125/13l) advice

**Comment by crbinz** [comment]
Thanks, disabling `startup.jl` worked. However, presumably this is a bug somewhere (if not with `GR`) - is that being tracked somewhere?
