### ISSUE TITLE
QT4 needed on Arch Linux

### ISSUE THREAD

**Issue by feanor12** [jheinen/GR.jl#145]
Without installing qt4 I got :
`GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP in routine TEXT`
when trying to run plot()

When looking at gksqt I'm missing the **qt4** package

```
ldd ~/.julia/packages/GR/fnyt8/deps/gr/bin/gksqt 
	linux-vdso.so.1 (0x00007fffa747a000)
	libQtGui.so.4 => not found
	libQtNetwork.so.4 => not found
	libQtCore.so.4 => not found
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb56f9ba000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb56f82b000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fb56f6a6000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb56f68a000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb56f4c6000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb56fa12000)
```
Is it possible to use  /usr/lib/libQt5Gui.so from **qt5-base**?
Installing qt4 works, but I could not find documentation saying that it was needed.

**Comment by juliohm** [comment]
I am having this same warning in Travis CI with GR. There is a set of messages like the one pasted above. Is Qt a requirement? Could you please clarify the issue?

**Comment by juliohm** [comment]
That is awesome. Looking forward to the new release.

**Comment by feanor12** [comment]
@FlorianRhiem The CentOS 6 qt-x11 package is a Qt4 package, I assume, but It is a bit misleading, because all other distributions are listed with Qt5 dependencies. Maybe the note could also mention that Qt4 is used as a fallback instead of Qt5.

**Comment by feanor12** [comment]
@FlorianRhiem sounds good.

**Comment by rjuarezp** [comment]
I am still having the same issue installing GR on Solus Linux. The generic package is still based on qt-4 which is since many years not being supported.
Is there a possibility that you change this package, please? Otherwise, I will have to search for alternatives to GR...
Thanks!

**Comment by jheinen** [comment]
Which GR version are you trying to install?

**Comment by IngoMeyer441** [comment]
@rjuarezp I installed GR.jl on a fresh Solus Linux, and it works for me. There is dependency to Qt4. Do you have some old GR installation on your system?

**Comment by rjuarezp** [comment]
Hi! I just deleted the ~/.julia folder and install GR.jil again. Now it's working without any problems! I don't know what happened, but now it is working!
Thanks very much!!!!
