### ISSUE TITLE
Segmentation fault on Julia v1.0

### ISSUE THREAD

**Issue by juliohm** [jheinen/GR.jl#146]
I am getting some random segmentation faults in Julia v1.0 like this one: https://travis-ci.org/JuliaImages/ImageInpainting.jl/jobs/424590051

Could you please take a look? I restarted the build, before it was segfaulting in both Linux and Mac.

**Comment by FlorianRhiem** [comment]
Hello Júlio,
this looks like a [segfault](https://github.com/jheinen/GR.jl/issues/119) that was [fixed](https://github.com/sciapp/gr/commit/bd89a9847822ca749958bd40c491c6ab787c4ffd) in version 0.33.0 and you are installing 0.32.3. Please try installing GR.jl version 0.33.1 instead and let us know if the segfault still occurs.

**Comment by juliohm** [comment]
The build pass, I will close the issue for now, and will let you know if it reappears.

Thanks for the prompt reply.
