### ISSUE TITLE
latex labels are rotated when using log-scale

### ISSUE THREAD

**Issue by Godisemo** [jheinen/GR.jl#152]
See the following MWE. using log-scaling on a plot makes latex axis labels rotate.

```julia
using Plots
gr()
x = 1:10
y = exp.(x)

p1 = plot(x, y, xlabel="\$x\$", ylabel="\$\\exp(x)\$")
p2 = plot(x, y, xlabel="\$x\$", ylabel="\$\\exp(x)\$", yscale=:log10)
p3 = plot(x, y, xlabel="x", ylabel="exp(x)")
p4 = plot(x, y, xlabel="x", ylabel="exp(x)", yscale=:log10)
p = plot(p1, p2, p3, p4, layout=(2,2), legend=false)
```
![plot](https://user-images.githubusercontent.com/847898/45350308-c09ba780-b5b3-11e8-812a-99f0a346274f.png)

**Comment by Godisemo** [comment]
possible related issue #92

**Comment by Godisemo** [comment]
Example of the same issue, without using Plots.jl
```julia
using GR
x = 1:10
y = exp.(x)
plot(x, y, xlabel="\$\\xi\$", ylabel="\$\\exp(\\xi)\$", ylog=true)
```
<img width="712" alt="screen shot 2018-09-12 at 09 26 00" src="https://user-images.githubusercontent.com/847898/45408896-f309db00-b66d-11e8-8d12-5b7ad373ddde.png">

**Comment by jheinen** [comment]
Thanks for the clarification - this will help us to find the problem ...
