### ISSUE TITLE
Discrete Contour Fill

### ISSUE THREAD

**Issue by jleman** [jheinen/GR.jl#165]
I am trying to prepare a filled contour plot with discrete levels.  However, it appears that only a continuous gradient is possible (attached example).  Is it possible to specify the number of contours and have a solid fill in between levels?  On contour plots without fill I see it is possible to specify the number of levels.  Can this be done with a filled contour plot?

using GR
f(x,y) = (3x + y^2) * abs(sin(x) + cos(y))
x = 0:0.1:20
y = 0:0.1:10
z = [f(i,j) for i in x, j in y]'
contour(x,y,z,levels=10,fill=true)#levels does not change the plot

![continuousfill](https://user-images.githubusercontent.com/44458380/47479739-de7b3f80-d7e2-11e8-8981-707f801d7580.png)

Looking to do something more like this:
![discretefill](https://user-images.githubusercontent.com/44458380/47479792-11bdce80-d7e3-11e8-934b-f11cebf24283.PNG)

**Comment by jheinen** [comment]
This feature is currently unsupported, but planned for a future release.

**Comment by danielkaiser** [comment]
This feature is now implemented and will be included in one of the next releases.
![gks](https://user-images.githubusercontent.com/9868673/48425908-09174300-e766-11e8-997c-894e2da980ba.png)

**Comment by jleman** [comment]
Excellent.  Looking forward to it.  Thank you.


A quick follow-up question.  How does one get involved in supporting this effort?  I am not a programmer, but really like Julia and I think the GR backend is one that I would like to see succeed in the Julia platform.  I am an engineer working on a PhD and my time is booked through the end of the year, but next year I could see myself spending some time helping out if possible.   Perhaps something like helping to expand the available documentation (more example plots with corresponding code etc.) if there is any interest in that kind of support or something similar I'd be interested.


Best Regards,


Jon


________________________________

**Comment by jheinen** [comment]
Works fine in `GR.jl` master:
```julia
using GR
contourf(peaks())
```
<img width="713" alt="screen shot 2018-11-14 at 03 48 13" src="https://user-images.githubusercontent.com/5718244/48456664-2547ce00-e7c0-11e8-9362-1806ea34e952.png">

**Comment by FlorianRhiem** [comment]
@jleman Contributions, especially improvements to the GR documentation, are more than welcome!

I've set up a GitHub mirror of our documentation repository at [sciapp/gr-documentation](https://github.com/sciapp/gr-documentation), so you can open up pull requests there once you find the time, and if you have any questions or want to discuss things, feel free to open an issue or send an email.

**Comment by juliohm** [comment]
Please tag a new release for this :champagne: :fireworks: :smiley: It would also be nice to update Plots.jl :100:

**Comment by aramirezreyes** [comment]
> Please tag a new release for this 🍾 🎆 😃 It would also be nice to update Plots.jl 💯

Yes, please!

**Comment by juliohm** [comment]
I think this issue is solved :+1:

**Comment by PieterjanRobbe** [comment]
It seems that discrete contour plots are the standard now?

```
 A = [sin(pi*x)*cos(pi*y) for x in 0:0.01:1, y in 0:0.01:1]
contourf(A, fill=true)
```

Is there a way to get back the "old" `gr` behaviour without the obvious

```
contourf(A, fill=true, nlevels=1000, linewidth=0)
```
?

<img width="873" alt="Screenshot 2019-04-08 at 21 34 55" src="https://user-images.githubusercontent.com/15999604/55751589-50b8a700-5a46-11e9-8ba4-49d740851702.png">

<img width="871" alt="Screenshot 2019-04-08 at 21 35 09" src="https://user-images.githubusercontent.com/15999604/55751562-439bb800-5a46-11e9-9f75-e7143837e563.png">

**Comment by juliohm** [comment]
You probably want heatmap?

**Comment by PieterjanRobbe** [comment]
Ah I didn't know that, perfect!
