### ISSUE TITLE
GKSTerm crashes on mac with large number of points

### ISSUE THREAD

**Issue by ViralBShah** [jheinen/GR.jl#17]
This causes GKSTerm to crash on my mac. 

````
GR.plot(1:10^6, 1:10^6)
````

**Comment by jheinen** [comment]
Will be fixed in the next release. The CGPoint buffer in the polyline() routine has to be allocated from heap instead from stack. Using malloc() fixed the problem (on my Mac).

    - (void) polyline: (int) n : (double *) px : (double *) py
    {
      int ln_type, ln_color, i;
      double ln_width;
      CGPoint *points;
      int dashlist[10];
      CGFloat lengths[10] = {0., 0., 0., 0., 0., 0., 0., 0., 0., 0. };
      double x, y;
 
      points = (CGPoint *) malloc(n * sizeof(CGPoint));
      for (i = 0; i < n; ++i)
        {
          WC_to_NDC(px[i], py[i], gkss->cntnr, x, y);
          seg_xform(&x, &y);
          NDC_to_DC(x, y, points[i].x, points[i].y);
        }
 
      ln_type  = gkss->asf[0] ? gkss->ltype : gkss->lindex;
      ln_width = gkss->asf[1] ? gkss->lwidth : 1;
      ln_color = gkss->asf[2] ? gkss->plcoli : 1;
 
      [self set_stroke_color: ln_color : context];
 
      begin_context(context);
 
      CGContextBeginPath(context);
 
      if (ln_type != 1)
        {
          gks_get_dash_list(ln_type, ln_width, dashlist);
          for (i = 1 ; i<= dashlist[0]; ++i)
            lengths[i-1] = (float) dashlist[i];
 
          CGContextSetLineDash(context, 0.0, lengths, dashlist[0]);
        }
 
      CGContextSetLineWidth(context, ln_width);
      CGContextAddLines(context, points, n);
      CGContextDrawPath(context, kCGPathStroke);
 
      free(points);
 
      end_context(context);
    }

**Comment by jheinen** [comment]
Fixed in https://github.com/jheinen/gr/commit/bce259f85514d86a5b58d80044b434374715b0ae.

**Comment by ViralBShah** [comment]
Swift work!

Cc @shashi

**Comment by jheinen** [comment]
Fixing bugs is one thing - deploying the patched software is more time-consuming ...

**Comment by ViralBShah** [comment]
Yeah - I was actually pleasantly surprised how easy it was to get the first plot going with GR.jl!
