### ISSUE TITLE
Visual regression tests and GR on different OS

### ISSUE THREAD

**Issue by juliohm** [jheinen/GR.jl#170]
I am having this issue more often than I wished, which is the fact that the plots generated in Linux versus plots generated in Mac OS differ considerably. I already increased the tolerance in my visual regression tests, but the discrepancy is continuously increasing with new updates.

Is there any way to force the exact same output in different operating systems? Is this an issue of the software using for saving the figures on the disk instead?

Thank you,

**Comment by jheinen** [comment]
Could please provide an example (MWEi, including the GR output type) and version information about the OSs.

**Comment by juliohm** [comment]
Thank you @jheinen , this is one instance of the problem in Travis: https://travis-ci.org/juliohm/Variography.jl/builds/454761484

The Mac build is failing one of the tests with a tolerance greater than 0.1 whereas all the tests pass on Linux with 0.0 visual difference.

**Comment by jheinen** [comment]
I'd like to wait for the results with GR 0.36.0 (released yesterday), which contains several bug fixes.

**Comment by juliohm** [comment]
I am only testing on Linux now given that the variability is not caused by GR per see, but the load/save of images from disk. Thank you for the attention.
