### ISSUE TITLE
Oh man... Windows install nightmare

### ISSUE THREAD

**Issue by EricForgy** [jheinen/GR.jl#18]
~~~julia
julia> Pkg.add("GR")
WARNING: julia is fixed at 0.4.2 conflicting with requirement for Unitful: [0.5.0-,∞)
INFO: Cloning cache of GR from git://github.com/jheinen/GR.jl.git
INFO: Installing GR v0.9.17
INFO: Removing ColorVectorSpace v0.1.1
INFO: Removing ImageMagick v0.1.3
INFO: Removing Images v0.5.3
INFO: Removing SIUnits v0.0.6
INFO: Removing TexExtensions v0.0.3
INFO: Building GR
INFO: Downloading pre-compiled GR 0.17.3 binary
=================================[ ERROR: GR ]==================================

LoadError: chmod: no such file or directory (ENOENT)
while loading C:\Users\Eric Forgy\.julia\v0.4\GR\deps\build.jl, in expression starting on line 25

================================================================================

================================[ BUILD ERRORS ]=================================

WARNING: GR had build errors.

 - packages with build errors remain installed in C:\Users\Eric Forgy\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("GR")`
 - build a single package by running its `deps/build.jl` script

=================================================================================
INFO: Package database updated
julia>
~~~

Why did installing this package remove my other unrelated packages?

~~~julia
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
~~~

**Comment by tbreloff** [comment]
Certainly your install didn't go well, but I highly doubt GR had anything to do with removing other packages.  I'm pretty sure `Pkg.add` does a `Pkg.resolve` before running (or maybe after it's added?).  Either way... there must have been some other dependency change, or you removed a parent package earlier, or something like that.

As for windows... well I don't use my windows machine for serious work for a reason :P  Sorry I can't help with that.

**Comment by jheinen** [comment]
> Downloading pre-compiled GR 0.17.3 binary

Please checkout the master branch until we have deployed GR 0.18.0: ``Pkg.checkout("GR")``.

Nevertheless, this is not related to any other packages (as @tbreloff already mentioned).

**Comment by EricForgy** [comment]
Hmm. Would Pkg.resolve ever remove packages?

When I did a `Pkg.add("GR")`, several of my packages were removed.

**Comment by jheinen** [comment]
GR has only one(!) requirement (``Compat``, for compatibility with Julia v0.3.x).

I'll try to reproduce your problem this morning ...

**Comment by tbreloff** [comment]
> Would Pkg.resolve ever remove packages?

Yes that's one of it's main purposes... to add/remove dependencies as needed.  Likely you had a package that used to depend on those packages, but removed the dependency.  Or you might have removed a package and the unneeded dependencies weren't resolved until now.

**Comment by EricForgy** [comment]
@tbreloff Ok, but I added those packages manually...

Thanks @jheinen . Pkg.checkout worked for me :+1:
