### ISSUE TITLE
Add support for volume plots

### ISSUE THREAD

**Issue by juliohm** [jheinen/GR.jl#186]
Hi,

Do you have plans to add support for volume plots? I think the only backend that currently supports it is `GLVisualize.jl`? It would be awesome to have it in `GR.jl` as well.

Thanks,

**Comment by jheinen** [comment]
GR has support for [isosurfaces](https://twitter.com/josef_heinen/status/870653440283770880) which you can find in the examples directory:
- [brain.jl](https://github.com/jheinen/GR.jl/blob/master/examples/brain)
- [slices.jl](https://github.com/jheinen/GR.jl/blob/master/examples/slices.jl)
- [orbitals.jl](https://github.com/jheinen/GR.jl/blob/master/examples/orbitals.jl)

**Comment by jheinen** [comment]
GR has support for [isosurfaces](https://twitter.com/josef_heinen/status/870653440283770880) which you can find in the [examples](https://github.com/jheinen/GR.jl/tree/master/examples) directory:
- brain.jl
- orbitals.jl
- slices.jl

**Comment by juliohm** [comment]
Thank you @jheinen, so the Plots.jl package is not mapping a seriestype to the available implementation? Whenever I try to plot 3D objects with GR backend, I get an error message saying that the backend does not support the plot.

**Comment by jheinen** [comment]
Could you provide a MWE in Plots?

**Comment by juliohm** [comment]
Is this error expected? Shouldn't the command trigger the available implementation in GR.jl?

**Comment by jheinen** [comment]
GR currently "only" supports isosurface plots for this kind of data. I assume, you are expecting a volume plot here, right?

We will add volume splatting in a future release.

**Comment by juliohm** [comment]
How do we call the isosurface plot in GR.jl from Plots.jl? Any 3D plot
would be useful since none is working at the moment.

**Comment by juliohm** [comment]
Marking the issue as solved. We now have 3D volume plots :+1:
