### ISSUE TITLE
Serve the gr binary through BinaryBuilder / Github / julialang-s3

### ISSUE THREAD

**Issue by ViralBShah** [jheinen/GR.jl#187]
I am visiting Beijing right now, and I note (as did many others here) that the GR binary installs is one of the slowest steps when setting up a Julia install. In general, I found it slow in the US too, but it is extremely slow in Beijing.

Does it make sense to serve the binaries through BinaryBuilder, the julialang-s3 hosting or even just uploading them to GitHub so that they get served through a CDN?

cc @staticfloat

**Comment by jheinen** [comment]
I fully agree. I will see how we can setup such a mirror.

**Comment by ViralBShah** [comment]
Maybe the simplest is to just upload to github in the releases? That does seem to work well.

**Comment by staticfloat** [comment]
GitHub releases is how we're serving most of our BB infrastructure as well; they have a pretty good CDN already, so I'd list that as best first solution.
