### ISSUE TITLE
Installing GR 0.38 on Ubuntu doesn't build

### ISSUE THREAD

**Issue by fratrik** [jheinen/GR.jl#190]
It seems that when trying to download the prebuilt Ubuntu package, it gets a github html page instead. (I renamed the extension to html)

https://www.dropbox.com/s/on222xq730utbfu/gr-0.38.0-Ubuntu-x86_64.tar.gz.html?dl=0

FWIW, both 0.37 and #master seem to work.

**Comment by jheinen** [comment]
The link should be 
https://github.com/sciapp/gr/releases/download/v0.38.0/gr-0.38.0-Ubuntu-x86_64.tar.gz

I have no idea where the dropbox link comes from!?

**Comment by eschnett** [comment]
I have the same issue on Darwin. `GR.jl` uses the link `https://github.com/sciapp/gr/releases/tag/v0.38.0/gr-0.38.0-Darwin-x86_64.tar.gz`, but should use `https://github.com/sciapp/gr/releases/download/v0.38.0/gr-0.38.0-Darwin-x86_64.tar.gz` instead. That is, `tag` should be replaced by `download`.

**Comment by jheinen** [comment]
Fixed in 0.38.1
