### ISSUE TITLE
log2 y-axis scaling does not work

### ISSUE THREAD

**Issue by natschil** [jheinen/GR.jl#191]
It seems like `yscale=:log2` doesn't work anymore: 
```
┌ Warning: scale log2 is unsupported with Plots.GRBackend().  Choose from: Symbol[:identity, :log10]
```
This used to work, and it seems like log2 x-axis scaling still works.

**Comment by ncihnegn** [comment]
xaxis is not working, either. This should have the highest priority.

**Comment by jheinen** [comment]
Please move this issue to Plots.jl. The problem can't be fixed in GR.jl.

**Comment by ncihnegn** [comment]
> Please move this issue to Plots.jl. The problem can't be fixed in GR.jl.

Care to elaborate? I don't understand why GR is the only backend with this issue.

**Comment by jheinen** [comment]
Unfortunately I cannot offer a short-term solution.

I have never implemented log2 axis scaling in GR, and, the GR backend in Plots does not offer this functionality either, see [documentation](https://docs.juliaplots.org/latest/generated/supported/#Scales-1). So I'm honestly a little confused as to when that should have worked!?

I will of course add it to the GR TODO list. Would that be okay?

**Comment by ncihnegn** [comment]
> Unfortunately I cannot offer a short-term solution.
> 
> I have never implemented log2 axis scaling in GR, and, the GR backend in Plots does not offer this functionality either, see the Plots [documentation](https://docs.juliaplots.org/latest/generated/supported/#Scales-1). So I'm honestly a little confused as to when that should have worked!?
> 
> I will of course add it to the GR TODO list. Would that be okay?

Got it. I will dig deeper.

**Comment by jiangnanhugo** [comment]
I like use GR backend than the others. currently, the log2 is useful for scientific graph plotting.

**Comment by timcop** [comment]
Any updates on this? I am getting this issue myself

**Comment by fdamore95** [comment]
Hi, is this still up? Same problem today.

**Comment by jheinen** [comment]
There's an [example](https://github.com/jheinen/GR.jl/blob/master/examples/log2_ex.jl) in 0.64.3.
