### ISSUE TITLE
GR in Atom(Juno) on Mac doesn't render texts

### ISSUE THREAD

**Issue by utotch** [jheinen/GR.jl#193]
I use GR in Atom(Juno) on Mac.
But GR.plot doesn't render texts (title, xlabel, ...) even though other rendering works well.

I tried 3D plot like trisurf, but the xtick numbers in the graph are correctly rendered.

Do you have any ideas about why the texts are not correctly rendered?

[environment]
GR.version() = "0.38.0"
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_HOME = /Applications/Julia-1.1.app/Contents/Resources/julia/bin
  JULIA_EDITOR = atom -a
  JULIA_NUM_THREADS = 2

```julia
using GR
plot(rand(10), title="title is not rendered")
title("also this doesn't renderd")
```

![image](https://user-images.githubusercontent.com/834175/53615125-5f7f8480-3b91-11e9-9d34-f9bef968e843.png)

```julia
using GR
N = 500
x = -1 .+ rand(N) * 2
y = -1 .+ rand(N) * 2
z = [x[i]^2-y[i]^2 for i=1:N]
trisurf(x,y,z)
```
![image](https://user-images.githubusercontent.com/834175/53615195-b1280f00-3b91-11e9-86c0-a695616f8d64.png)

**Comment by jheinen** [comment]
If I remember right, this problem started with the `ink 0.9.12` package update, which caused problems in the SVG text part. You can check the SVG created by GR - it's ok and can be displayed by different other renderers (Inkscape, Adobe tools, ...) or browsers.

The only workaround is to switch to PNG:
```
using GR
inline("png")
...
```

... or downgrade `ink`.

**Comment by utotch** [comment]
Thanks for the comment.

I tried to downgrade ink to 0.9.11. But unfortunately, it caused an error and a plot in Atom doesn't work in my env.

**Comment by utotch** [comment]
I compared ink 0.9.10 - ink 0.9.14.

https://github.com/JunoLab/atom-ink/compare/v0.9.10...v0.9.14

But I can't find any suspicious code related to svg text rendering. ...difficult.

**Comment by jheinen** [comment]
I'm currently out of office. I'm pretty sure that it was related to `ink`, but I could not figure out why.

I'll check an older version from my backup disk next week and try to find out, what cause the problem.

**Comment by jheinen** [comment]
Even a simple example doesn't work:
```
bg = 0x00ffffff
file_path="test.svg"
content = Base.HTML(string("""<div style="display: inline-block; background: #""", Base.hex(UInt64(bg), 6, false), """;">""", String(read(file_path)), """</div>"""))
Main.Atom.render(Main.Atom.PlotPane(), content)
```
`test.svg`:
```
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="500" height="500">
<rect x="5" y="10" width="40" height="40" stroke="orange" stroke-width="5"/>
<text style="font-size:50px;" x="50" y="50">Hello World</text>
</svg>
```
The filled rectangle is shown, but the text is missing!?

**Comment by jheinen** [comment]
I simplified the display/show logic which seems to fix the text problem. Please `] add GR#master`.

**Comment by utotch** [comment]
Thank you very much.
The text problem looks recovered.

But the output is not clearly seen in the default color scheme.
The rendering problem could be related to a color scheme.

# default colorscheme

![image](https://user-images.githubusercontent.com/834175/53661964-8b911900-3c16-11e9-99f2-d5894e923572.png)

```julia
usecolorscheme(2)
```
![image](https://user-images.githubusercontent.com/834175/53661990-99df3500-3c16-11e9-8fa3-f7346472c55e.png)

**Comment by AhmedSalih3d** [comment]
Same problem on Windows 10, no texts are rendered inside Atom plot pane - saving as pdf, everything is visible though.

**Comment by jheinen** [comment]
Please `] add GR#master`.

**Comment by AhmedSalih3d** [comment]
@jheinen thanks :-)
