### ISSUE TITLE
Rotate x and y ticks

### ISSUE THREAD

**Issue by AhmedSalih3d** [jheinen/GR.jl#195]
Hello

I am doing following code  (GR v0.38.1):

Using GR
v = rand(5,1)
plot(v,rotation=45)

Which runs, but does not rotate any thing in the plot. I have spent a while trying to find out whether it is possible to rotate tick labels using GR?

Kind regards

**Comment by jheinen** [comment]
The `rotation` parameter controls the orientation of the 3d space. It has no effect on 2d axes labels. We can add such a feature in a future release.

**Comment by AhmedSalih3d** [comment]
@jheinen thank you, I was going crazy trying to figure out. I really like the GR package though, thanks for taking time to make Julia able to use it. 

Kind regards
