### ISSUE TITLE
Legend Position

### ISSUE THREAD

**Issue by AhmedSalih3d** [jheinen/GR.jl#197]
Hello guys

I've seen a similar issue, #75 , but no answer so I will try asking again. I know that this is possible using the Plots interface, but I want to use GR framework directly, ie. "using GR". I always check the following website:

https://gr-framework.org/julia-gr.html

But have not found any description of how to move the legend:

![image](https://user-images.githubusercontent.com/36305327/54136368-f400a700-441b-11e9-94c6-9296e76f785f.png)

Which I would like to have on at least the other side, or maybe out of the figure. Also the legend box seems a bit too small, n touches the edge, but I am not sure why. 

Using GR v0.38.1 with Julia. Would it be better for me to use the Plots interface to interact with GR in Julia?

Kind regards

**Comment by jheinen** [comment]
see #75

**Comment by AhmedSalih3d** [comment]
Thanks! I didn't know if this has been possible all the time, but thanks for providing an example for me :-) I will close it off now.
