### ISSUE TITLE
unwanted $ signs in `ylabel = string(L"\alpha", " sometext")`

### ISSUE THREAD

**Issue by aborzunov** [jheinen/GR.jl#198]
I want to provide some text after LaTeX string which yields unwanted `$` signs around LaTeXString.
```plot(randn(10), ylabel = string(L"\alpha", " sometext"))```
![example](https://user-images.githubusercontent.com/2773341/54423252-4b0ac280-4721-11e9-9300-a1d065f8a84e.png)

**Comment by greimel** [comment]
In just had the same issue and found the solution in some other issue.

Use `\( ... \)` instead of `$ ... $`. This seems to work

```julia
using GR, LaTeXStrings
plot(randn(10), ylabel = L"\(\alpha \) some text")
```

```julia
using Plots, LaTeXStrings
plot(randn(10), ylabel = L"\(\alpha \) some text")
```

**Comment by ShuhuaGao** [comment]
> Use `\( ... \)` instead of `$ ... $`. This seems to work

It reports "ERROR: syntax error" on my system.
```
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8

(@v1.4) pkg> status LaTeXStrings
Status `C:\Users\shuhu\.julia\environments\v1.4\Project.toml`
  [b964fa9f] LaTeXStrings v1.1.0
```

**Comment by heliosdrm** [comment]
In the newer versions, full LaTeX strings are supported, and the older workaround mentioned by @greimel mentioned some nearly a year ago shouldn't be used.

**Comment by ShuhuaGao** [comment]
> In the newer versions, full LaTeX strings are supported, and the older workaround mentioned by @greimel mentioned some nearly a year ago shouldn't be used.

Thank you, @heliosdrm . Yes, you are right. `using LaTeXStrings` is enough. 

However, one pitfall in mixing normal text and math expression is that **`\mathrm` rather than `\textrm` (or `\textrnomal`)** should be used. In view of the above example

> I want to provide some text after LaTeX string which yields unwanted `$` signs around LaTeXString.
> `plot(randn(10), ylabel = string(L"\alpha", " sometext"))`

we should write `L"\alpha \mathrm{sometext}"`.
