### ISSUE TITLE
Locating libGR.so

### ISSUE THREAD

**Issue by dextorious** [jheinen/GR.jl#2]
Due to certain restrictions, I've installed the GR framework using the binary package for the Anaconda python distribution (using "conda install -c https://conda.binstar.org/jheinen gr") rather than compiling from source and I've verified that it works from the python interpreter (which is in my global $PATH). 

Unfortunately, when I try to use "polyline(rand(100), rand(100))" from Julia, I get the error "ERROR: error compiling polyline: could not load module /usr/local/gr/lib/libGR.so: /usr/local/gr/lib/libGR.so: cannot open shared object file: No such file or directory". I skimmed through the source of GR.jl and tried copying libGR.so to $HOME/gr/lib, since it seemed to check that path for the shared library, but this did not change the error. Perhaps I'm missing something obvious here, but it may be the case that handling of the library dependency in GR.jl could be improved.

Either way, looking forward to using this great framework from my Julia code!

**Comment by jheinen** [comment]
I'll check this tomorrow morning when I'm back in my office. Should be possible by setting an environment variable ``GRDIR`` for the GR runtime ...

**Comment by jheinen** [comment]
Starting with GR.jl version 0.4.0 (published a few minutes ago) you can "share" the GR framework runtime environment between Anaconda and Julia. You will have to set the ``GRDIR`` environment to the GR Python module path in your Anaconda (or Miniconda) distribution, e.g.:

    export GRDIR=${HOME}/anaconda/lib/python2.7/site-packages/gr
