### ISSUE TITLE
Closing figure and figure window is gone forever

### ISSUE THREAD

**Issue by grinsted** [jheinen/GR.jl#20]
When i close a figure window, and then attempt to plot again, then the figure window is gone forever. I'd like it to pop up again by itself. (as matlab would do) 

Here's what i do: 
1. copy/paste the mandel.jl source to the REPL.
2. close the figure window.
3. execute the final mandel for-loop one more time. 

Problem: it does not show me the figure in step 3.

**Comment by jheinen** [comment]
I would kindly ask you to wait until we have solved this problem with a special Qt backend, which will run as a separate process (with its own event loop). In my opinion, this is the only way to allow GR to be used both for plotting continuous data streams (in real-time) and in a figure-oriiented manner (like most of the other plotting tools). The thing is more difficult than it appears ...

But it is on my radar!

**Comment by floswald** [comment]
any news on this thread? Is there a way to open a new GR window? like `gui()` or so?

**Comment by jheinen** [comment]
We started to deploy `gksqt`, but we still need some time to make it "production-ready", as the automatic start of the GUI is not working as expected ...

**Comment by jheinen** [comment]
Fixed with GKSQt being the default output device
