### ISSUE TITLE
ploting multiple figures shows blank figure

### ISSUE THREAD

**Issue by utotch** [jheinen/GR.jl#202]
When I use Plots.jl with GR#master ("0.38.0.post81), the plot sometimes includes unexpected blank, white area.

I think this tends to happen when I use logscale plotting.
The example is as follows.

```julia
using Plots
plot(plot(rand(10,2),yscale=:log10), plot(rand(10,2)), layout=(2,1), size=(800,800))
```

the first figure of this plot isn't correctly shown, and that includes a blank, white area.

![image](https://user-images.githubusercontent.com/834175/54860646-43778a80-4cda-11e9-9c44-a8d9379ee335.png)

```bash
julia> GR.version()
"0.38.0.post81

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_DIR = /Applications/Julia-1.1.app/Contents/Resources/julia
  JULIA_HOME = /Applications/Julia-1.1.app/Contents/Resources/julia/bin
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2
```

**Comment by jheinen** [comment]
Thanks for the hint - I can reproduce it. I'm currently out of office and will check it on Monday ...

**Comment by jheinen** [comment]
The upper plot is hidden by a filled polygon (produced by Plots) - but I couldn't find it in the Plots code yet.

**Comment by jheinen** [comment]
Please move the issue to Plots.jl.
