### ISSUE TITLE
stem plot strange

### ISSUE THREAD

**Issue by zhulunwu** [jheinen/GR.jl#203]
GR version 3.80
code:
using GR
n = 0:40
x = sin.(0.1π*n)
stem(n,x)

and got:
![temp](https://user-images.githubusercontent.com/32381755/54875095-02df5480-4e33-11e9-9d61-301cc158254a.PNG)

it seems any x<0 are omited

**Comment by jheinen** [comment]
Stupid bug - has just been fixed in 8d5790d.
