### ISSUE TITLE
Stem plots

### ISSUE THREAD

**Issue by sivapvarma** [jheinen/GR.jl#21]
Is there currently a way to do stem plots with GR. This might be more a feature request. 

MATLAB
`stem(x, 'filled')`
![image](https://cloud.githubusercontent.com/assets/1314675/14408101/94d83d06-fe9b-11e5-9c6f-3b0c30172a4c.png)

Thanks for the work you put into GR.

**Comment by jheinen** [comment]
I just added a ``stem()`` function in 5839246.

    using GR
    X = linspace(0, 2*pi, 50)';
    Y = [cos(X); 0.5*sin(X)];
    stem(X, Y)

<img width="712" alt="stem" src="https://cloud.githubusercontent.com/assets/5718244/14411915/e69c4258-ff55-11e5-9989-1e71c75f946c.png">

Want to add more functions (e.g. ``stairs()``), examples and ``docstrings`` before I tag a new version, but you can checkout the master branch in the meantime ...

**Comment by sivapvarma** [comment]
This is awesome. Thanks!
