### ISSUE TITLE
Issue with large values in jupyter notebook

### ISSUE THREAD

**Issue by rakhusur** [jheinen/GR.jl#210]
When run in a jupyter notebook, this code
```julia
using GR
x = 0:0.01:3
plot(x[x .> 0], x -> 3/x^2, ylim = (0, 2))
```
gives me a plot which is cut off:
![Screenshot_2019-04-15 Untitled](https://user-images.githubusercontent.com/22003125/56120578-ad4c2280-5f6e-11e9-85dd-e4e729ef6629.png)

It seems to related to the function taking very large values. In the REPL (QtTerm) and in Juno everything works fine.

**Comment by jheinen** [comment]
I cannot reproduce this problem. Which OS (and browser) are you using? It runs even on mybinder.org:
![Screenshot 2019-04-15 at 13 44 26](https://user-images.githubusercontent.com/5718244/56130263-b21bd100-5f84-11e9-8b41-dccf2bf53253.png)

**Comment by rakhusur** [comment]
I'm using firefox on arch linux. I just tested a bit more: the issue appears neither with gnome web nor with nteract but only with firefox...

**Comment by FlorianRhiem** [comment]
I can reproduce this issue with an svg document only containing a clipping region and a polyline with three points from the original line:
```
<svg height="460.75" viewBox="0 0 2458 1843" width="614.5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="width: 100%; height: 100%;">
<defs>
  <clipPath id="clip5000">
    <rect height="1475" width="1967" x="307" y="138" />
  </clipPath>
</defs>
<polyline clip-path="url(#clip5000)" points="   313.805,-22114400  412.125,-84778      1493.64,937.554   2273.65,1366.89       " style="stroke:#00528a; stroke-width:4.301; stroke-opacity:1; fill:none"/>
</svg>
```

 We'll have to look into what exactly is causing this problem in Firefox and whether we can fix it in the gr runtime.

**Comment by jheinen** [comment]
@FlorianRhiem : But only in Firefox, right?

**Comment by FlorianRhiem** [comment]
Yes, it seems to be an issue in the SVG implementation of Firefox in connection with clip paths.

**Comment by FlorianRhiem** [comment]
It's a confirmed bug in Firefox's handling of SVG coordinates: https://bugzilla.mozilla.org/show_bug.cgi?id=1544413

**Comment by rakhusur** [comment]
I see, thanks for investigating. I guess this issue can be closed then?
