### ISSUE TITLE
Saving outputs as png

### ISSUE THREAD

**Issue by jbrea** [jheinen/GR.jl#22]
I'd love to use GR as an alternative to (slow) matplotlib.
However, I often want to save outputs as png,
which currently does not seem to be possible.
I don't know what gr3.save is supposed to do
but the following code produces a black output.

using GR
GR.inline()
GR.cellarray(0,1,0,1,50,50,round(255*rand(50,50)))
GR.show()
GR.gr3.save("foo.png", 300, 300)

Am I using it the wrong way?

**Comment by jheinen** [comment]
``savefig()`` should do the job, e.g.:

> julia> using GR
julia> contour(peaks())
julia> savefig("cont.png")

Which platform are you using? You possibly have to check out the latest GR version (or even the master branch):

    Pkg.checkout("GR")

The resulting PNG should look something like this:

![cont](https://cloud.githubusercontent.com/assets/5718244/14682965/960afa48-0728-11e6-8e17-1277443b6a2c.png)

**Comment by jbrea** [comment]
Thank you very much for the quick response!

Your example works. 
I'm on a x86_64-linux-gnu.

Unfortunately, for the following example,
I only see an output in the GKS 5 window,
but I don't find a saved file.

julia> using GR
julia> cellarray(0,1,0,1,50,50,round(255*rand(50,50)))
julia> savefig("array.png")

**Comment by jheinen** [comment]
Unfortunately, there is an inconsistency in the GR convenience layer (which provides MATLAB-like functions). So you have to create the output "yourself" until I have fixed the problem:

    using GR
    beginprint("array.png")
    cellarray(0,1,0,1,50,50,round(255*rand(50,50)))
    endprint()

Instead of using the cellarray function, you can also use ``imshow()``:

    imshow(randn(50,50))

**Comment by jbrea** [comment]
Great, that works, thank you very much.

For imshow I did not yet figure out,
how to set the aspect ratio.
That's why I stick with cellarray for the moment.

**Comment by sivapvarma** [comment]
I get the following error when I try this. How can I resolve this ?
```
julia> savefig("cont.png")  
GKS: Ghostscript support not compiled in
```

I am on Mac OS X El Capitan, Julia & GR master.

**Comment by jheinen** [comment]
Do you have an out-dated GR installation in ``/usr/local/gr`` or ``${HOME}/gr`` ? If so, please remove/rename those directories and rebuild (or re-install) GR.jl.

**Comment by avivasa** [comment]
Hi, there any way to improve the resolution of the figure?

**Comment by jheinen** [comment]
Which size/resolution do you get?
```julia
using GR
contour(peaks())
savefig("cont.png")
```
... produces a high-resolution image for me:
```bash
% identify cont.png
cont.png PNG 3171x2378 3171x2378+0+0 8-bit sRGB 822739B 0.010u 0:00.000
```

**Comment by avivasa** [comment]
Thank you for your response. I will try again but when I tried the resolution was 600x400
identify boxplot1.png 
boxplot1.png PNG 600x400 600x400+0+0 8-bit sRGB 14.3KB 0.000u 0:00.000
