### ISSUE TITLE
inline("mov") on windows failiure

### ISSUE THREAD

**Issue by Mike43110** [jheinen/GR.jl#23]
I am not sure if I require other installation steps I may have missed but just adding the package and trying out the examples using `inline("mov")` do not work on Windows 10 x64 inside a jupyter notebook.

**Comment by jheinen** [comment]
The current Windows package was built without **ffmpeg** support. We have already prepared a ``MinGW-w64`` based package which contains a fully featured movie plugin. I will deploy a new ``GR.jl`` runtime for Windows next week and let you know ...

**Comment by jheinen** [comment]
The problem should be solved with GR 0.19.1
