### ISSUE TITLE
What is the logic of the location number for legends?

### ISSUE THREAD

**Issue by heliosdrm** [jheinen/GR.jl#233]
I have seen that it is possible to set the location of legends by hacking the dictionary `GR.jlgr.plt.kvs`. You can give an integer number in the `:location` field, and then the legend will be shown in a different location of the plot, as in the following scheme:

| left  | middle | right | right (outside) |
|---|----|---|----|
| 2 | 9  | 1 | 11 |
| 6 | 10 |5,7| 12 |
| 3 | 8  | 4 | 13 |

(e.g. by default the location is `1`, thus it is drawn in the top right corner inside the plotted area; but if you set the location as `2`, it will be drawn in the top left corner, if it is `12` it will be drawn in the middle of a right blank band outside the plot, etc.)

However, the distribution of the numbers seems a bit chaotic. Does it follow any particular logic?

**Comment by jheinen** [comment]
There is no logic - the numbers for inside legends have been taken from [Matplotlib](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.legend.html).
