### ISSUE TITLE
Size of a plot

### ISSUE THREAD

**Issue by gestay** [jheinen/GR.jl#24]
Is it posible to change the size of a plot when exporting to a file?
I tried 
```
GR.beginprint("plot.pdf")
GR.plot(x, y, width=100, height=100)
GR.endprint()
```
But it didn't work.
Thanks

**Comment by jheinen** [comment]
You can use the figure command:

    using GR
    figure(size=(width, height))
    plot(x, y)
    savefig("plot.pdf")
