### ISSUE TITLE
Legend placement appears buggy

### ISSUE THREAD

**Issue by abelsiqueira** [jheinen/GR.jl#243]
Hi all,

we noticed [here](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/issues/2) that the legend for `:bottomright` is not at the bottom right. A short example of the problem can be recreated with
```
plot([scatter(rand(10,2), rand(10,2), legend=:bottomright) for i = 1:5]...,
	 layout=(1,5), size=(2000,400))
```

Thanks in advance.

**Comment by heliosdrm** [comment]
I'd say you have submitted this issue to the wrong package. The keyword argument `legend` is not even possible in GR. Does this perhaps belong in [Plots](https://github.com/JuliaPlots/Plots.jl/)?

**Comment by dpo** [comment]
Thanks. I opened an issue over at Plots.jl.

**Comment by abelsiqueira** [comment]
Sorry, I've missed this comment. Thanks for the answer.
