### ISSUE TITLE
Incorrect window size.

### ISSUE THREAD

**Issue by tmptrash** [jheinen/GR.jl#25]
Hi Josef,
Thanks again for you library..

Аfter several unsuccessful attempts to figure out what is wrong with window size i'm writing this issue. I tried the code, you gave me to setup window size in pixels:
```julia
w = 400
h = 300
mwidth, mheight, width, height = GR.inqdspsize()
if w >= h
    ratio = float(h) / w
    msize = mwidth * w / width
    GR.setwsviewport(0, msize, 0, msize * ratio)
    GR.setwswindow(0, 1, 0, ratio)
else
    ratio = float(w) / h
    msize = mheight * h / height
    GR.setwsviewport(0, msize * ratio, 0, msize)
    GR.setwswindow(0, ratio, 0, 1)
end

setviewport(0, 1, 0, ratio)
setwindow(1, w, 1, h)
#...
drawrect(1, w, 1, h)
#...
```
But, the size of the window is not 400x300. It's about 485x410. See [this](https://www.dropbox.com/s/ahtsndyvsogyp7z/size.png?dl=0) screenshot for details.

What i'm doing wrong?

**Comment by jheinen** [comment]
Nothing :-). This bug has been fixed in https://github.com/jheinen/gr/commit/0adb216927851b818f756e3efd06606941ce13a6

**Comment by tmptrash** [comment]
I think the issue is still there. The height was fixed, but the width wasn't. Here is a [source](https://github.com/tmptrash/jevo/blob/master/tmp/gltmp.jl) of code and here is the [screenshot](https://www.dropbox.com/s/pf4q7vhvskpa1pw/width.png?dl=0). I use 1280x720 with the same width and height, but the window is not a full screen.

**Comment by jheinen** [comment]
The Windows driver in GR will always preserve a margin of 0.75% in each direction., to allow the user to resize, move or iconify the window. Also keep in mind, that, depending on the Windows release, the window decoration is part of the requested viewport - I will check this tomorrow ...

**Comment by tmptrash** [comment]
But it works for height, so at least this margin is actual only for width...

**Comment by jheinen** [comment]
Could you please try again? IMO there is a strange bug in the Windows ``GetClientRect`` and/or ``GetWindowRect`` functions - I added a workaround when resizing the GR window. Nobody should try to understand what's going on behind the scenes ... If someone finds it out, pls let me know :-)

**Comment by tmptrash** [comment]
I will try in the evening...

**Comment by tmptrash** [comment]
Looks like it works! Great job, Josef! I think we may close the issue.
