### ISSUE TITLE
Error in GR.panzoom?

### ISSUE THREAD

**Issue by heliosdrm** [jheinen/GR.jl#252]
The code of `GR.panzoom` is:

https://github.com/jheinen/GR.jl/blob/6ae98b338345be850fbd96472d553327449e8736/src/GR.jl#L3734-L3744

However, the interface of `gr_panzoom` in the C source (https://github.com/sciapp/gr/blob/master/lib/gr/gr.c#L9600) is:

```c
void gr_panzoom(double x, double y, double xzoom, double yzoom, double *xmin, double *xmax, double *ymin, double *ymax)
```

So, it looks as if `GR.panzoom` were not supplying all the necessary arguments to the C function. Maybe the line 3742 should be:

`x, y, zoom,`**`zoom`**`, xmin, xmax, ymin, max`

Is that right?

**Comment by jheinen** [comment]
Thanks for the hint. It's fixed in 216045dc35fbd962ec63acc0903260f6e1c91b4d.
