### ISSUE TITLE
What are `mainloop`, `send_meta` and `send_serialized` for?

### ISSUE THREAD

**Issue by heliosdrm** [jheinen/GR.jl#258]
`send_meta` and `send_serialized` seem to be called instead of the main body of `plot_data` in some particular situations -- but I can't figure out when those situations may occur, and what actually happens in those cases. `mainloop` is even more intriguing for me.

Is there any case use or example that I could look at?

**Comment by jheinen** [comment]
These entry points are used for a new abstraction layer, which will allow us to implement high-level drawing operations, like `plot`, `scatter`, `heatmap`, `surface`, `contour`, etc),  in C. This will allow us to use the **same** code for different languages (Python, Julia, Ruby) and also transpile the code to Javascript. It is not documented, as it is still WIP.
