### ISSUE TITLE
Question. Image data of GR.readimage and  GR.drawimage. Int32 or UInt32 ?

### ISSUE THREAD

**Issue by kojix2** [jheinen/GR.jl#260]
Hi. 
this is a question. 

In GR.jl, `readimage` returns an array of `Uint32`. 
But, In python-gr or sciapp/gr, it seems return an array of `Int32`. 
Similarly, in GR.jl `drawimage` takes an array of `Uint32` as an argument, 
but in sciapp/gr it seems to take an array of `Int32`.

In the newtons_cradle example, readimage produces an array of `Uint32`, and drawimage works well because it receives an array of `Uint32`.
https://github.com/jheinen/GR.jl/blob/master/examples/newtons_cradle.jl

Should this be `Int32` or `UInt32`?
I'm writing a Ruby-GR binding for my personal use, So I'm wondering which type I should use.

**Comment by jheinen** [comment]
UInt32 is the correct type - `readimage` return RGBA tupels ...

**Comment by kojix2** [comment]
Thank you very much.
