### ISSUE TITLE
GR.jl on Manjaro Linux

### ISSUE THREAD

**Issue by cauachagas** [jheinen/GR.jl#265]
I got the following error installing GR.jl on Manjaro Linux.

```julia
julia> using Plots

julia> plot()
~/.julia/packages/GR/f1Iqi/src/../deps/gr/bin/gksqt: error while loading shared libraries: libQtGui.so.4: cannot open shared object file: No such file or directory
connect: Connection refused
GKS: can't connect to GKS socket application
Did you start 'gksqt'?
```

## Problem:

Trying to open `gksqt` in the specified path gives an error.
An incompatible binary is downloaded (qt4).

## Solution:

In

https://github.com/jheinen/GR.jl/blob/121f203612620ddca8d2c8782cb1235181d12242/deps/build.jl#L86

change to 

```julia
elseif id == "arch" || id_like == "arch"
```

**Comment by jheinen** [comment]
Thanks for the patch which is now merged into GR#master
