### ISSUE TITLE
Window breaks down in fullscreen mode

### ISSUE THREAD

**Issue by tmptrash** [jheinen/GR.jl#27]
This is simple bug. When i click on fullscreen button at the right top corner the window breaks down. See [screenshot](https://www.dropbox.com/s/72rsfyfp5yb2ii0/crash.png?dl=0) for details. Normal window - on the left, in fullscreen mode - on the right.

P.S. I use windows 8.1.

**Comment by jheinen** [comment]
Fixed with GKSQt
