### ISSUE TITLE
Packaging on Archlinux, problem with Julia and inline("mov")

### ISSUE THREAD

**Issue by stefanocampanella** [jheinen/GR.jl#29]
Hi! I am trying to packaging GR on Archlinux (you can find the package [here](https://aur.archlinux.org/packages/gr-git/)). I can successfully import GR in Julia and Python, however in Julia the following code 

``` julia
using GR
inline("mov")
x = collect(0:0.01:2*pi)
for i = 1:200
  plot(x,sin(x + i/10)
end
```

prompts the following error

`GKS: /usr/lib/./movplugin.so: undefined symbol: gks_movplugin`

**Comment by jheinen** [comment]
I didn't know this package but I'll ask my colleague, whether we can add an Archlinux package [here](http://software.opensuse.org/download.html?project=science:gr-framework&package=python-gr).

**Comment by jheinen** [comment]
If you want only Julia support, you can uninstall the Archlinux package an reinstall (or rebuild) GR (``Pkg.build("GR")``).

**Comment by stefanocampanella** [comment]
Wow! That would be awesome, especially if the package would support both Julia and Python. Thanks!

**Comment by mpastell** [comment]
Hi,
I get the same error on Ubuntu 16.04 using the generic Linux binaries.  

```GKS: /home/mpastell/.julia/v0.5/GR/src/../deps/gr/lib/./movplugin.so: undefined symbol: gks_movplugin```

**Comment by jheinen** [comment]
Could you pls try to checkout GR master and rebuild the package:
```julia
    Pkg.checkout("GR")
    ENV["GRDIR"]=""
    Pkg.build("GR")
```
You should then see that the build script has downloaded a **Ubuntu** binaries (instead of generic Linux binaries).

**Comment by mpastell** [comment]
It works now. Many thanks for the fix and quick reply!
