### ISSUE TITLE
A strange character in the window titles.

### ISSUE THREAD

**Issue by kojix2** [jheinen/GR.jl#294]
Hello!
GR has been updated to show window numbers. That's great. However, you see a strange character on the right side of the title. Maybe it's a font problem?
Do you have any tips to solve this problem?

![image](https://user-images.githubusercontent.com/5798442/76372607-536ffa80-6381-11ea-8859-cd9e86535b1e.png)

**Comment by jheinen** [comment]
This problem is already fixed. A new release will come soon ...

**Comment by kojix2** [comment]
Thanks!
Sorry for the duplicate issue.
