### ISSUE TITLE
Computer Modern font does not like Greek letters

### ISSUE THREAD

**Issue by heliosdrm** [jheinen/GR.jl#297]
The new font introduced in 1cc14975 breaks labels or annotations with Greek letters:

```julia
x = range(0, 1, length=20)
legend("\\alpha=1", "\\alpha=2", "\\alpha=3")
plot(x, x.^1, x, x.^2, x, x.^3)
```

(The example is with a legend, but titles, axes labels, etc. with Greek letters vanish too.)

A related comment: the font and precision codes used in the new code (`GR.settextfontprec(232, 3)`) are outside the documented ranges of options. (Fonts are only documented from 101 to 131, and precisions from 0 to 2).

**Comment by jheinen** [comment]
Thanks for the hint - will check.

```
plot(x, x.^1, x, x.^2, x, x.^3, labels=(L"\alpha=1", L"\alpha=2", L"\alpha=3"))
```
works fine.

**Comment by heliosdrm** [comment]
Ok, that's a reasonable workaround - although it depends on LaTeX (and the package LaTeXStrings if you want to use the `L"..."` syntax). The nice thing of `"\\alpha"` etc. is that you could use it without having any LaTeX installation in your machine (which I think is the case of many users).

**Comment by jheinen** [comment]
I will try to support both methods ...

**Comment by heliosdrm** [comment]
In version 0.49.1 I consider that this is solved. Now strings with non-ASCII characters (e.g. accented letters, and also Greek alphabet etc.) look fine again.
