### ISSUE TITLE
The grid is red in mac OS

### ISSUE THREAD

**Issue by kojix2** [jheinen/GR.jl#298]
Hello. 

The grid turns red in version 0.48.0 as shown.

`snoop.jl`

![image](https://user-images.githubusercontent.com/5798442/78009343-daf6cb00-737b-11ea-80ac-e7267bac5ac7.png)

I suspect this is a bug, not a change in specifications. Because on Ubuntu and Windows it dose not happen. The grid turns gray when I use libgr installed with homebrew.
I have seen this happen on two Macs. I think it may be a known problem, but I report it.

Thank you.

**Comment by jheinen** [comment]
I can't reproduce this behaviour. Did you close the `GKSTerm.app` before installing GR?

**Comment by kojix2** [comment]
You are right. 
I tried again. It does not reproduce.
Maybe GKSTerm.app was running and left some settings. 
I'm sorry to have disturbed you. Thank you again.
