### ISSUE TITLE
Cannot Plot 3D 

### ISSUE THREAD

**Issue by duncanam** [jheinen/GR.jl#303]
Hi,

When trying to use something 3D like `isosurface`, I get:

```
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  46
  Current serial number in output stream:  45
```
I am on an XPS 9370 with integrated graphics, and I have iris and swrast .so libraries in that dri folder location. Any suggestions? I'd like to be able to do 3D plotting on my laptop.

**Comment by jheinen** [comment]
I assume there is no other problem using 3d on your laptop (e.g. `glxgears` works) - so could you please post the output of `glxinfo`?

**Comment by duncanam** [comment]
`glxgears` does appear to work. The info from `glxinfo` is, in short:
`OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.0-devel (git-06c5875fd6)`

And long attached:
[glxinfo_out.txt](https://github.com/jheinen/GR.jl/files/4498520/glxinfo_out.txt)

**Comment by duncanam** [comment]
This is solved by downgrading `mesa`, discussed in [this plots ticket.](https://github.com/JuliaPlots/Plots.jl/issues/2598)
