### ISSUE TITLE
every plot closes/reopens GKS QtTerm

### ISSUE THREAD

**Issue by wmkoolen** [jheinen/GR.jl#306]
Dear developers,

I am using GR as the plots backend from the julia REPL. I am using KDE on Debian bullseye. I switched from julia 1.3 to 1.4 today, and the following changed.

On 1.4, when issuing subsequent plots, say
julia> plot(1:5)
julia> plot(1:6)
the first opens a window, and the second closes that first window and reopens a new window. The position, size and maximisation state of the fist window are forgotten. The new window's title bar says "GKS QtTerm (121)", where the number in parentheses is incremented every plot. Also the new window asks for attention; it unhides the task bar, with the GKS QtTerm entry marked orange. 

Previously, subsequent plots would reuse the same window. I would maximise the plot window on my second monitor and all plots would go there. 

Is this a design choice? Is there a setting I can change to get the old behaviour?

Cheers,

Wouter

julia> versioninfo()
Julia Version 1.4.1
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

julia> GR.version()
"0.48.0.post91"

**Comment by jheinen** [comment]
I can reproduce the "resize" but not he "reopen" behaviour. The "resize" problem seems to be related to the GKS QtTerm - doesn't happen using GKSTerm on macOS. We will check this ...

**Comment by wmkoolen** [comment]
Dear developers,

While wondering how a julia update could have caused this, I noticed the process /home/wouter/.julia/packages/GR/yMV3y/src/../deps/gr/bin/gksqt -session 10d9d9dd73000158750187000000066720029_1587591455_160090 that was running in the background, even with no julia session ongoing.

After killing this process manually, the next julia plot command respawned that same process (without the session argument) and the expected previous plotting behaviour returned. Subsequent plot windows are now resizing (unless maximised), and they keep their position. Mysterious! Glad to have sanity restored.

Cheers,

Wouter

**Comment by tysun** [comment]
How do we stop this window from opening and keep plots in embedded tabs in VS Code? Thanks
