### ISSUE TITLE
Trisurf support for triangles

### ISSUE THREAD

**Issue by ChrisRackauckas** [jheinen/GR.jl#31]
It would be nice to be able to set the triangles in trisurf. For example, and array triangles is usually given as:

```
triangles = [node1 node2 node3
                   node4 node5 node6
                   ...]
```

where this means that for

```
plot(x,y,z,triangles=triangles)
```

we have that `(x[node1],y[node1],z[node1])`, `(x[node2],y[node2],z[node2])`, and `(x[node3],y[node3],z[node3])` are the points which make the first triangle, etc. The reason for this is referenced in tbreloff/Plots.jl#392

**Comment by jheinen** [comment]
Shouldn't the triangles have the form (x[node1], y[node1], z[node1]), (x[node2], y[node2], z[node2]), and (x[node3], y[node3], z[node[3]), ...

**Comment by ChrisRackauckas** [comment]
Yes, I was being silly.

**Comment by tbreloff** [comment]
I think something different... the triangles are the data to be plotted, and the x/y/z inputs should be triplets of coordinates in each dimension.  No triangles keyword.

**Comment by ChrisRackauckas** [comment]
Usually the triangles are an optional entry (matplotlib, plotly, MATLAB) because the naive "connect all the triangles" works for convex domains.

**Comment by tbreloff** [comment]
Please stop limiting yourself to the design of those crappy languages.  We have multiple dispatch! :)  You can do something different depending on the type of data you get.

**Comment by ChrisRackauckas** [comment]
So then if given just x/y/z it defaults to doing a surface plot (which works for convex domains), but putting triangles in front (as a matrix) dispatches to this more precise trisurf? That would work. It would be nice to have the option to give x/y/z either as vectors or as a single vector of (x,y,z) tuples (that could be handled in Plots.jl though).

**Comment by tbreloff** [comment]
No.  If you want a mesh, you call mesh.  If you want a surface, you call surface.  I'm trying to distinguish between the two.  A "tri-surface" is just that... a surface where triangles are used to avoid requiring an evenly spaced grid.  A "tri-mesh" is different... this is a 3D model of sorts.

**Comment by tbreloff** [comment]
Your lake example is a mesh, even though there are no overlapping triangles in the z-dimension.
