### ISSUE TITLE
surface() crashes on Windows when rotation == 0

### ISSUE THREAD

**Issue by Allardvm** [jheinen/GR.jl#33]
I'm experiencing some crashes when plotting 2-dimensional histograms in `Plots.jl` when using the GR framework with a large amount of data on Windows 10.

The following code reproduces the issue in GR using a setup that is similar to the one called in `Plots.jl` for 2-dimensional histograms:
```julia
using GR

setwindow(0, 1000, 0, 1000)
setviewport(0, 1, 0, 1)

x = collect(1:1000)
y = collect(1:1000)
z = [rand() for x in x, y in y]

setspace(0, 1, 0, 90)

surface(x, y, z, GR.OPTION_HEATMAP)
```
The critical piece of code is the `0` that specifies the rotation in `setspace(Int64, Int64, 0, Int64)`. The issue only occurs for reasonably large amounts of data.

**Comment by jheinen** [comment]
The bug is fixed in https://github.com/jheinen/gr/commit/971e03974fa4abf42776d9760bcba36c6f74f9d0 . I will build new binaries within the next days ...

**Comment by Allardvm** [comment]
Awesome! Thanks for the quick fix.
