### ISSUE TITLE
Use VS Code extension plot pane by default

### ISSUE THREAD

**Issue by heliosdrm** [jheinen/GR.jl#335]
Since the VS Code extension is meant to be the replacement of Juno, should GR use the VS Code's plot pane by default, as it does in Atom? Now the GKS window is normally used, unless you run `inline("svg")` explicitly.

When using the VS Code extension, the module `Main.VSCodeServer` is defined, and it shouldn't be difficult to find out what function in that module can be used, to check if it is suitable to produce SVG files instead of using the GKS window.

**Comment by jheinen** [comment]
Thanks for the hint. Will change that soon ...

**Comment by jheinen** [comment]
What's the trick to get inline plots in VS Code? Tried PyPlot, Plotly, Plots ... no success. Do you have any idea, which extension has to be installed /enabled?

**Comment by jheinen** [comment]
Ok - it now works in the `Julia REPL` in a VSCode Terminal. Don't know, how to open a Julia file and use the `VSCodeServer`.

**Comment by heliosdrm** [comment]
I don't know either.
