### ISSUE TITLE
guidefontrotation changes font size

### ISSUE THREAD

**Issue by Byrth** [jheinen/GR.jl#352]
`guidefontrotation=30` seems to set my guide font size instead of rotation. I tried with 8 and 30 and it varies the font size in both cases.

GR 0.52.0, Julia 1.5.2, Plots 1.6.4

**Comment by jheinen** [comment]
You mean in Plots?

**Comment by Byrth** [comment]
I am never quite sure what lives where. Is this a Plots issue, then?

**Comment by jheinen** [comment]
yes, `guidefontrotation` is a Plots keyword.

**Comment by Byrth** [comment]
OK, I will re-make the issue over there! Thank you.
