### ISSUE TITLE
[BUG] Heatmap draws background on top in specific cases

### ISSUE THREAD

**Issue by gustaphe** [jheinen/GR.jl#359]
Running the code below:
```julia
using Plots;
pl = heatmap(
    rand(10,10),color=:reds,background=:green,
    showaxis=false, # A
    ticks=false, # B
    legend=false, # C
    )
pl # retriggering the draw required to see bug. Can also (annoyingly) be done with savefig()
```
causes the green background to be drawn (semi-transparent) on top of the heatmap. This goes for any combination of colors, but green and red is very illustrative. 

The important part is that commenting out *either* of line `A`, `B` or `C` removes the bug.

A workaround is using `ticks=[]`, but this introduces a slight gap (space for the empty tick labels).

There is more weirdness here: the important axis seems to be the `y` axis. If line `A` is prepended by `y`, the bug still appears, but it disappears with `x`. Line `B` does not show this behaviour, both axes must be tickless to see the bug.

Any ideas?

```
Plots v1.9.1
GR v0.53.0
```

**Comment by jheinen** [comment]
Could you please post the issue in Plots.jl? I think this bug can only be fixed in the GR backend part of Plots.jl.
