### ISSUE TITLE
How to set aspect ratio?

### ISSUE THREAD

**Issue by sje30** [jheinen/GR.jl#36]
Hi, how do I set the aspect ratio of a plot?

In Plots.jl, this works for pyplot() but not for gr()

```
w = rand(10,2)
pyplot()
plot(w[:,1], w[:,2], w=9, aspect_ratio=1)
gr()
plot(w[:,1], w[:,2], w=9, aspect_ratio=1)
```

**Comment by sje30** [comment]
Ping?

Or is this a bug for Plots.jl?  @tbreloff

**Comment by tbreloff** [comment]
It might not be implemented for GR.

**Comment by jheinen** [comment]
I just made a ``Plots.jl`` PR (#472) to add ``gr()`` support for setting the ``aspect_ratio`` of a plot.

**Comment by sje30** [comment]
Thank you very much!  I just tested this, and it works for me.

**Comment by mtaoraki** [comment]
I have a question concerning the aspect_ratio in Plots.jl, when using the GR backend. I am trying to get contour plots with an aspect ratio of 1 and colorbar. However, when trying the following code, I get different aspect ratios and the ylabel is shifted when I change the aspect ratio:

```julia
using Plots
gr()
n = 10
```

Without colorbar the aspect ratio is right, but the ylabel is shifted:
```julia
contourf(randn(n,n),c=:viridis,aspect_ratio=1,colorbar=false,xlabel="x",ylabel="y")
```
[output](https://github.com/jheinen/GR.jl/files/653279/asp_ratio_2.pdf)

When I turn on the colorbar the aspect ratio is computed including the colorbar:
```julia
contourf(randn(n,n),c=:viridis,aspect_ratio=1,colorbar=true,xlabel="x",ylabel="y")
```
[output](https://github.com/jheinen/GR.jl/files/653278/asp_ratio_1.pdf)

Without changing the aspect ratio the ylabel is fine:
```julia
contourf(randn(n,n),c=:viridis,colorbar=false,xlabel="x",ylabel="y")
```
[output](https://github.com/jheinen/GR.jl/files/653280/asp_ratio_3.pdf)


Is there something I'm missing or is there a way to get something like axis('equal') in matplotlib or is it a "bug"?

**Comment by photor** [comment]
> I just made a `Plots.jl` PR (#472) to add `gr()` support for setting the `aspect_ratio` of a plot.

aspect_ratio works in Plots.jl using the GR backend, but does not work in GR.jl. Actually, the following code:

> import GR
> x = collect(0:0.01:2*pi)
> GR.plot(x, sin.(x), size=(400,300), aspect_ratio=1)

just results in a warning message "Invalid keyword: aspect_ratio". So how to make that work in GR.jl?
