### ISSUE TITLE
Minimum OSX version == 10.9 ?

### ISSUE THREAD

**Issue by acroy** [jheinen/GR.jl#37]
As you might guess I am on 10.8 and got the following after the install went through without hiccup

```
julia> using GR

julia> GR.plot(rand(10))
dyld: lazy symbol binding failed: Symbol not found: ___sincos_stret
  Referenced from: ~/.julia/v0.4/GR/deps/gr/lib/libGR.so
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___sincos_stret
  Referenced from: ~/.julia/v0.4/GR/deps/gr/lib/libGR.so
  Expected in: /usr/lib/libSystem.B.dylib
```

Apparently `sincos` et al were introduced in 10.9 ...

Any chance the pre-compiled GR framework could support 10.8?

**Comment by jheinen** [comment]
You are right - our current build system is 10.9.5. Is there a reason why you still use 10.8?

**Comment by acroy** [comment]
No particular reason other than that I am reluctant to change my system now. BTW, the official Julia package for OSX actually supports 10.7.

I can understand if you don't want to extend the support,  but maybe you could mention this somewhere in the README or give a warning during install?

**Comment by jheinen** [comment]
We build our own GR distribution with OSX 10.7, that's not the problem. But our CI system, which builds the self-contained packages, is 10.9.5. may be I can "downgrade" ...
