### ISSUE TITLE
FR: Italic capital greek letters in Latex strings

### ISSUE THREAD

**Issue by mmikhasenko** [jheinen/GR.jl#377]
I cannot figure out if it is already possible.
Neither `\mathit`, nor \varOmega work.

Perhaps, it just requires adding `\usepackage{amsmath}`
https://tex.stackexchange.com/questions/87238/greek-letters-in-italic-in-math-equation

I am working with `Plots.jl` and `gr()` backend

MWE
```julia
using Plots
using LaTeXStrings
plot(title=L"\langle \mathit{\Omega} \rangle")
```

**Comment by mmikhasenko** [comment]
From a post in gitter by @jheinen 
```julia
using GR
using LaTeXStrings
# settextfontprec(232,3)
mathtex(0.1, 0.5, L"\langle \rangle, and \mathit{\Omega}")
```
But everything should work if you omit `settextfontprec()` - the text will then be rendered using your local LaTeX installation.

> trying to reproduce it, currently getting `ERROR` printed when calling `mathtex` with either `\langle` or `\rangle`

**Comment by mmikhasenko** [comment]
There is some 
I get `latex: failed to create a dvi file` even with L`\alpha`

```latex
\documentclass{article}
\pagestyle{empty}
\usepackage[dvips]{color}
\begin{document}
\[
\color[rgb]{0.000,0.000,0.000} {
\alpha}
\]
\end{document}
```

the same is for `L"\langle \rangle, and \mathit{\Omega}"` 
```latex
\documentclass{article}
\pagestyle{empty}
\usepackage[dvips]{color}
\begin{document}
\[
\color[rgb]{0.000,0.000,0.000} {
\langle \rangle, and \mathit{\Omega}}
\]
\end{document}
```

**Comment by mmikhasenko** [comment]
`latex`, and `pdflatex` work on the temporary files that at produced by GR.

I am on windows, do not have `bash`

**Comment by mmikhasenko** [comment]
Is it possible to add symbols
```
\\varGamma
\\varDelta
\\varTheta
\\varLambda
\\varXi
\\varPi
\\varSigma
\\varUpsilon
\\varPhi
\\varPsi
\\varOmega
```
coming from `\usepackage{amsmath}`
to 
https://github.com/sciapp/gr/blob/7e617d2ec4d0ce65e2f55a754831eb154e387706/lib/gr/mathtex2.c

**Comment by jheinen** [comment]
> Would it possible to add symbols
> 
> ```
> \\varGamma
> \\varDelta
> \\varTheta
> \\varLambda
> \\varXi
> \\varPi
> \\varSigma
> \\varUpsilon
> \\varPhi
> \\varPsi
> \\varOmega
> ```
> 
> coming from `\usepackage{amsmath}`
> to
> https://github.com/sciapp/gr/blob/7e617d2ec4d0ce65e2f55a754831eb154e387706/lib/gr/mathtex2.c
> 
> ?

I added support for user-defined LaTeX preambles. With the next release you can use `AMS` packages, e.g.
```julia
ENV["GR_LATEX_PREAMBLE"] = "AMS"
using GR
using LaTeXStrings

plot(rand(10), title=L"\langle \varGamma \varDelta \varTheta \varLambda \varXi \varPi \varSigma \varUpsilon \varPhi \varPsi \varOmega \rangle", font="Times_Roman")
```

Simply adding the above mentioned `\var` Symbols would not work, because they are not contained in the CM font we use. I can probably try to slant the text with GKS (at a very low level), but I'll first have to check, whether the results are acceptable.

**Comment by jheinen** [comment]
It will be available in the next GR release, hopefully next week.

**Comment by mmikhasenko** [comment]
Indeed, it is solved! Many thanks
