### ISSUE TITLE
implict plot functions

### ISSUE THREAD

**Issue by jmarcellopereira** [jheinen/GR.jl#38]
How to make implict plot functions?
x - y^2 ==2
2*x + y == 0

**Comment by tbreloff** [comment]
Joao: I'll assume that you didn't like my first response. Instead of
opening an issue in every graphics package with the same question, maybe
you should discuss alternatives to SymPy in julia-users. If there's a
plotting package that supports it I'm sure you'll find out that way.

**Comment by jmarcellopereira** [comment]
Hi, tbreloff
ok, you're right. I looked for a way to make and not discovered. I found the package "ImplicitEquations" but did not like.
