### ISSUE TITLE
GKSwstype vs GKS_WSTYPE

### ISSUE THREAD

**Issue by mkitti** [jheinen/GR.jl#398]
I noticed that GR.jl uses both `GKSwstype` and `GKS_WSTYPE`. It looks like `GKS_WSTYPE` takes precedence over `GKSwstype` upstream:
https://github.com/sciapp/gr/blob/c5fbc6613de1437a3dd598680de02af8dbe1098f/lib/gks/util.c#L1621-L1625

Is this intentional? Should we standardize on one form or the other?

Currently,
* `init` uses `GKSwstype`.
* `inline` and `reset` uses `GKS_WSTYPE`.

**Comment by jheinen** [comment]
Yes, this is intentional. The user may set `GKSwstype`, while internally, e.g. in `Plots.jl`, the output device may be switched temporarily (via `GKS_WSTYPE`).
