### ISSUE TITLE
LaTeX exponent position

### ISSUE THREAD

**Issue by gustaphe** [jheinen/GR.jl#402]
When rendering LaTeX strings, the position of an exponent changes a lot if the symbol before it is encased in gull wings or not:

```julia
plot(rand(5); xguide=raw"$x^2 {x}^2 \mathrm{x}^2 \mathrm{x^2} \mathbf{x}^2 \mathbf{x^2}$")
```
![grissues](https://user-images.githubusercontent.com/6677110/116120414-cb050400-a6bf-11eb-808d-ebb3faaa0dc9.png)

the first, fourth and sixth are correct. The fourth demonstrates a workaround for the case of `\mathrm` (when the exponent is a number), but the sixth demonstrates why this isn't always an option.

In LaTeX, these exponents would all be the same height.

**Comment by gustaphe** [comment]
Found a bit of time to try stuff out. 
When running 
```julia
julia> using GR
julia> hold(false);
julia> plot(randn(5),zeros(5));
julia> hold(true);
julia> GR.mathtex(0.5,0.5,raw"$m^{-1}\mathrm{m}^{-1}$");
julia> plot(randn(5),zeros(5));
```
(plotting twice was the only way I could get a `GR.mathtex` to show, if you have an easier debug method I'd love to hear it)

I get this incorrect placement:
![image](https://github.com/user-attachments/assets/a383d69e-b1ca-42e8-b723-a2340f2d7887)

But when running 
```c
#include <stdio.h>
#include <gr.h>

int main(void) {
    gr_beginprint("testgr.png");
    gr_setfillintstyle(1);
    gr_setfillcolorind(0);
    gr_fillrect(0.3,0.53,0.4,0.5);
    gr_mathtex(0.42,0.5,"m^{-1}\\mathrm{m}^{-1}");
    gr_endprint();
    return 0;
}
```
it appears like the positioning is correct:
![image](https://github.com/user-attachments/assets/c666e826-a83d-417b-8165-4359855d92c2)

`GR.mathtex` just filters out the dollar signs and does a `ccall`, so I don't understand how these can be different, unless the positioning has changed between versions, and GR.jl uses another version than my system. But the same thing happens if I launch Julia with `GRDIR` set.

**Comment by jheinen** [comment]
Yes, we get different results when we compare GR's built-in LaTeX interpreter (llines 3 + 4) with TeXlive's (original) LaTeX. We will take a look at this.

```julia
using GR

# use (external) TeXlive
mathtex(0.5, 0.5, raw"$m^{-1}\mathrm{m}^{-1}$")
mathtex(0.5, 0.4, "m^{-1}\\mathrm{m}^{-1}")

# use GR's LaTeX interpreter
settextfontprec(232, 3)
mathtex(0.5, 0.3, raw"$m^{-1}\mathrm{m}^{-1}$")
mathtex(0.5, 0.2, "m^{-1}\\mathrm{m}^{-1}")

updatews()
```
