### ISSUE TITLE
Edit on Github URL: Page not found

### ISSUE THREAD

**Issue by ptoche** [jheinen/GR.jl#405]
http://docs.juliaplots.org/latest/generated/gr/

top-right corner sends to:

https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/generated/gr.md

which is 404

**Comment by jheinen** [comment]
This issue is related to the `Plots.jl` documentation and cannot be fixed here.

**Comment by ptoche** [comment]
Oh sorry, posted in the wrong place. Thanks.
