### ISSUE TITLE
savefig error for png

### ISSUE THREAD

**Issue by abieler** [jheinen/GR.jl#41]
saving to png format produces the following error msg:

GKS: /home/abieler/.julia/v0.5/GR/deps/gr/lib/cairoplugin.so: undefined symbol: XRenderCompositeText32

On 64 bit Linux Mint 17.2 Rafaela (Ubuntu Trusty)

**Comment by jheinen** [comment]
Please checkout the GR master branch and force a download of the latest pre-built run time:

```
    julia> Pkg.checkout("GR")
    julia> ENV["GRDIR"]=""
    julia> Pkg.build("GR")
    INFO: Building GR
    INFO: Downloading pre-compiled GR latest Linux binary
```

At this point you have to quit Julia and start it again.

With the next GR release (0.21.0) you can simply ``Pkg.update("GR")`` and you will get a working run-time.

**Comment by abieler** [comment]
That worked, thanks!

**Comment by lucianolorenti** [comment]
I'm having the same issue in Arch Linux 32 bits. I have already updated the package.
What could be the problem?

**Comment by jheinen** [comment]
Do you have an older GR installation anywhere, e.g. in `$(HOME)/gr`, `/opt/gr`, `/usr/local/gr` or `/usr` ? if so, you should simply remove those folder(s).

**Comment by lucianolorenti** [comment]
No, it is the first time that I install gr.   The only place where gr  it is located is in   $(HOME)/.julia/v0.5/GR/deps/gr

**Comment by lucianolorenti** [comment]
I compile GR from source and replace .julia/v0.5/GR/deps/gr/lib/cairoplugin and now is working.
