### ISSUE TITLE
GR.show() should do nothing unless GR.mimetype[] is not empty

### ISSUE THREAD

**Issue by mkitti** [jheinen/GR.jl#411]
I was thinking about `GR.show()` and perhaps that it should not do anything if `GR.mimetype[]` is not set to anything. Currently it always calls `emergencyclosegks()`:

https://github.com/jheinen/GR.jl/blob/41eeb9d860dde7476860b663957267102c0cee07/src/GR.jl#L3770-L3772

Could we make calling `emergencyclosegks()` depend on `mime_type[]` being not set? Is there a reason to call ``emergencyclosegks()` if `mime_type[]` is not set?

```julia
function show()
    if !isempty(mime_type[])
        emergencyclosegks()
    end
    if mime_type[] == "svg"
         ...
    end
    return nothing
end
```

**Comment by jheinen** [comment]
Yes, that should be ok.
