### ISSUE TITLE
camera keyword in plot allows only AZIMUTH between 0 and 90 degrees

### ISSUE THREAD

**Issue by Dejan-Ilic** [jheinen/GR.jl#415]
When I use the camera keyword, the conveniently named variable `AZIMUTH` is always reduced to the range [0, 90], but I need something like 110 so that "the x-axis points out of your screen"

```
θ = 0

y = @. sqrt(x + 1) * cos(θ)
z = @. sqrt(x + 1) * sin(θ)
        
plot(x, y, z, label=nothing, color=:blue, camera=(AZIMUTH, 45),
                framestyle = :origin, xlims = (-1, 4), ylims = (-2, 2), zlims=(-3,3))
```

**Comment by jheinen** [comment]
This is currently not possible. It will be support in a future GR version.
