### ISSUE TITLE
GKS: invalid workstation type (windows)

### ISSUE THREAD

**Issue by musm** [jheinen/GR.jl#42]
![image](https://cloud.githubusercontent.com/assets/4319522/19198392/ee9435a0-8c8c-11e6-80c3-03487da55ded.png)

**Comment by jheinen** [comment]
This error message indicates that the ``GKS_WSTYPE`` environment variable is set to "windows", which is not supported. On Windows, GR automatically sets the correct workstation type (41).

I found the setting in Plots.jl:
```
const _gr_wstype_default = @static if is_linux()
    "cairox11"
elseif is_apple()
    "quartz"
else
    "windows"
end
```

I'll discuss that with Tom.

@tbreloff : Is this flag new? Should I allow that ``GKS_WSTYPE`` setting in GR?

**Comment by tbreloff** [comment]
I'm clueless when it comes to windows. Let me know what you think I should
change.

**Comment by ChrisRackauckas** [comment]
Adding a bit more information:

I get this error as well. If I ever close the window I need to restart Julia to plot again. Using GR directly (not through Plots.jl) doesn't throw errors, but it has the same problem that if the GUI is ever closed it won't come back and you have to restart Julia.

**Comment by jheinen** [comment]
@ChrisRackauckas - Either @tbreloff has to change from "windows" to "win" or I have to change from "win" to "windows" (or allow both aliases for the corresponding workstation type 42).Right now, the window should/can (only) be closed by the application (Julia), but I'll see whether I can change this behaviour in the Windows driver part of GR.

**Comment by ChrisRackauckas** [comment]
The `invalid workstation type (windows)` is fixed on the `dev` branch of Plots (for me).

**Comment by jheinen** [comment]
BTW: The upcoming Qt5 driver will solve all these problems (and provide interactivity, zoom, pan, etc.).

**Comment by tbreloff** [comment]
@jheinen I pushed up a fix, which is to not set the environment variable on windows.

**Comment by musm** [comment]
Thanks newest Plots.jl seems to fix this.
