### ISSUE TITLE
contour and trisurf may not be working very well

### ISSUE THREAD

**Issue by kojix2** [jheinen/GR.jl#425]
Hi @jheinen and GR.jl developers

I've been working on making GR.rb follow the recent changes in GR.jl. However, I noticed that when I applied the new changes, the example did not work very well.

So, I ran faster-time-to-first-plot.ipynb to see how Julia works. I used the latest [Julia GR](https://github.com/jheinen/GR.jl/commit/056f811b62cb4363d73108361b61d351a502c3e5) with `dev GR`.

https://gist.github.com/kojix2/2cf9ffdd79ba0d77f49ca20ef1a79605

`contour` and `trisurf` do not seem to work very well, I think.
![image](https://user-images.githubusercontent.com/5798442/127861100-ca4834cb-e0b5-4037-bc5d-cb547ffdc3a6.png)
![image](https://user-images.githubusercontent.com/5798442/127861138-225d4f64-4f63-439a-bc9c-3233d7b2d638.png)

Maybe I should really try to figure out why, but I'm just reporting today. Take care.

**Comment by jheinen** [comment]
Thanks for the bug report(s). I guess we need to do more testing before tagging a new release.

Sorry for that.

**Comment by kojix2** [comment]
I confirmed that this problem has been fixed.
