### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by swt30** [jheinen/GR.jl#43]
The key thing that's stopping me using GR is that I can't pass a LaTeX string (e.g. from the LaTeXStrings.jl package) and have it rendered as an axis label or whatever. I know there's some support for Greek letters but it's not as complete as matplotlib, which will accept basically any LaTeX you give it. 

Is this something that GR will be able to do one day?

**Comment by jheinen** [comment]
What about that?

```julia
using GR
histogram(randn(10000), title="\$Histogram : \\sigma = \\sqrt {\\mu_2 }\$")
```

![screen shot 2016-10-12 at 17 06 48](https://cloud.githubusercontent.com/assets/5718244/19315518/46a891b8-909e-11e6-8d84-7298572fbddc.png)

**Comment by swt30** [comment]
Oh I didn't realise there was full LaTeX rendering - that's great! I guess the answer is "yes". It doesn't work for me on Linux at the moment though:

```julia
julia> using GR

julia> histogram(randn(10000), title="\$Histogram : \\sigma = \\sqrt {\\mu_2 }\$")
WARNING: both GR and Base export "show"; uses of it in module Main must be qualified
WARNING: sturges(n) is deprecated, use StatsBase.sturges(n) instead.
SYSTEM: show(lasterr) caused an error

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by swt30** [comment]
I've just checked and this only seems to happen in the REPL, not when running from a script, in Juno, or in Jupyter.

**Comment by swt30** [comment]
A couple of other questions:

- Is it possible to have mixed latex and ordinary text? `"For example, a \$string\$ like this \$\\alpha\$"`.
- It looks like the rendering doesn't support unicode characters at the moment - matplotlib/pyplot allow you to pass the string `"\$α\$ and \$β\$"` to the latex engine.

**Comment by swt30** [comment]
An update: the example you gave is now working fine. I'd like to suggest that the ability to mix LaTeX and ordinary text and include unicode characters in the string would be very useful, especially given that Julia makes it very easy to type these characters. Ideally we could do the following:

```julia
using GR, LaTeXStrings
histogram(randn(10000), title=L"Mixed normal text and $\sqrt{3 + α} LaTeX$")
```

**Comment by jheinen** [comment]
Enabling unicode characters in GR is on our radar. But this step requires a lot of testing (and probably code changes) in some GKS drivers, e.g. PostScript. I'll take a closer look ASAP.

**Comment by ma-laforge** [comment]
@swt30:

Though supporting LaTeXStrings is a good long-term solution, for the moment you can mix normal text and equations using LaTeX construct `\textrm`:

histogram(randn(10000), title="\$\\textrm{Histogram : }\\sigma = \\sqrt {\\mu_2 }\$")
