### ISSUE TITLE
Segmentation fault (or at best, no plot) when $HOME is undefined

### ISSUE THREAD

**Issue by drayer587** [jheinen/GR.jl#430]
There are some other issues that seem related to this one, but since I've finally discovered why this is happening after a couple days of tinkering, I figure it's worthwhile documenting it somewhere.

If $HOME isn't defined, GR (by itself or via Plots) will (without additional steps) segfault in gks_drv_socket when trying to plot anything. After recently going through the three steps to basic troubleshooting in the readme here, I now instead get

```
julia> using Plots

julia> scatter(1:10,sin)
GKS: cannot open display - headless operation mode active

shell> $HOME
ERROR: UndefVarError: HOME not defined
```

So, I suppose it's an improvement, but still seems like unintended/undesired/unexpected/anomalous behavior.

Reproducible (Ubuntu 21.04) by opening a remote terminal through the bundled file manager, opening a new tab (thus locally) and running Julia, using Plots, and an arbitrary plot doesn't plot or segfaults. Somewhere along the line $HOME fails to get defined in this routine (see below)

```
william@william-Precision-5820-Tower-X-Series:/home/william$ ~
bash: /home/william: Is a directory
william@william-Precision-5820-Tower-X-Series:/home/william$ cd $HOME
bash: cd: HOME not set
```

Obviously the solution here is "don't do this" but, again, just seemed worthwhile to document since it caused me headaches for a few days until I finally found the culprit. Finally, the mess from the core dump with a clean, non-troubleshooted installation:

```
@v1.6) pkg> add GR
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `~/.julia/environments/v1.6/Project.toml`
  [28b8d3ca] + GR v0.59.0
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`

julia> using GR

julia> scatter(1:10,sin)
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)
connect: Connection refused
GKS: can't connect to GKS socket application


signal (11): Segmentation fault
in expression starting at REPL[4]:1
gks_drv_socket at /home/william/.julia/artifacts/9a3d38207568a8c97dc4edf968e1fd1d7dc4a730/lib/libGR.so (unknown line)
gks_ddlk.isra.0 at /home/william/.julia/artifacts/9a3d38207568a8c97dc4edf968e1fd1d7dc4a730/lib/libGR.so (unknown line)
gks_open_ws at /home/william/.julia/artifacts/9a3d38207568a8c97dc4edf968e1fd1d7dc4a730/lib/libGR.so (unknown line)
initgks at /home/william/.julia/artifacts/9a3d38207568a8c97dc4edf968e1fd1d7dc4a730/lib/libGR.so (unknown line)
gr_clearws at /home/william/.julia/artifacts/9a3d38207568a8c97dc4edf968e1fd1d7dc4a730/lib/libGR.so (unknown line)
clearws at /home/william/.julia/packages/GR/82MXo/src/GR.jl:664 [inlined]
plot_data at /home/william/.julia/packages/GR/82MXo/src/jlgr.jl:1206
plot_data at /home/william/.julia/packages/GR/82MXo/src/jlgr.jl:1183 [inlined]
#scatter#45 at /home/william/.julia/packages/GR/82MXo/src/jlgr.jl:1860
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:670
scatter at /home/william/.julia/packages/GR/82MXo/src/jlgr.jl:1856
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:562
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:670
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139
repl_backend_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:200
start_repl_backend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:185
#run_repl#42 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:317
run_repl at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:305
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#874 at ./client.jl:387
jfptr_YY.874_23032.clone_1 at /home/william/julia-1.6.2/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
jl_f__call_latest at /buildworker/worker/package_linux64/build/src/builtins.c:714
#invokelatest#2 at ./essentials.jl:708 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
run_main_repl at ./client.jl:372
exec_options at ./client.jl:302
_start at ./client.jl:485
jfptr__start_34281.clone_1 at /home/william/julia-1.6.2/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:560
repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:702
main at julia (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4007d8)
Allocations: 17791794 (Pool: 17785997; Big: 5797); GC: 24
Segmentation fault (core dumped)
```

**Comment by jheinen** [comment]
I don't really understand in which environment you are using `Plots`/`GR`. Are you on a desktop machine or did you `ssh` to a remote host, or, are you an a headless system? I also don't understand, why `$HOME` is not defined.

**Comment by drayer587** [comment]
I agree: I don't understand why `$HOME` isn't defined. This is on a desktop, wherein the terminal is opened remotely via the right click menu in the file manager while `sftp` onto a remote server. However, upon opening a new tab in this terminal, I'm on the local Precision tower:

```
william@william-Precision-5820-Tower-X-Series:/home/william$ ~
bash: /home/william: Is a directory
```

So, this first tab is `ssh` into a remote host, the second tab is local, and somehow when a tab is opened in this terminal, started by the method described above, `$HOME` somehow doesn't get defined. Curiously, if I start plotting, this error doesn't occur, so it's just trying to hook up to GKS/X11/whatever down the line the first time in this odd method. I will add some pictures that may clarify once I'm back on that machine later today.

**Comment by drayer587** [comment]
![Screenshot from 2021-09-21 12-15-17](https://user-images.githubusercontent.com/50423792/134210809-b51c3dd5-ffb0-4dd8-8b8c-df657d7be0e3.png)
![Screenshot from 2021-09-21 12-18-38](https://user-images.githubusercontent.com/50423792/134210813-0d9e58df-34d9-400f-8acc-64735e5cac66.png)
![Screenshot from 2021-09-21 12-18-43](https://user-images.githubusercontent.com/50423792/134210815-0d0a40ea-2680-4bd9-ac8d-1c14d6b0708e.png)
![Screenshot from 2021-09-21 12-38-01](https://user-images.githubusercontent.com/50423792/134211523-b652cb8d-5e82-44b6-a37c-27ef250907cd.png)

Here are some screen grabs, and there's one more that annoyingly I couldn't manage to grab in Ubuntu (right click menu) so that one will come in just a minute. Left tab is the one opened through the file manager, directly into `ssh` while the second tab puts me on the local machine without $HOME.

To be clear, I'm well aware this is a problem of not having $HOME defined outside Julia/GR in this strange instance, I think there is just likely a preference for no seg fault if $HOME isn't defined (for whatever odd reason).

**Comment by jheinen** [comment]
I suspect that "Open in Remote Terminal" starts an `ssh` connection. Plots graphics will only work, if X11 forwarding is (also) enabled. Dir you check this?

**Comment by drayer587** [comment]
More testing reveals this happens even with starting in a local terminal (e.g. in local home), without `sftp` from the file manager: `$HOME` fails to get defined without any `ssh`. So it's the Ubuntu file manager that's the culprit for starting any new terminal tab without defining `$HOME`. Ctrl-Alt-T to get a terminal does not present this issue on new tabs, regardless of the status of the current tab (`ssh` or not).

tab one:
```
william@william-Precision-5820-Tower-X-Series:~$ pwd
/home/william
william@william-Precision-5820-Tower-X-Series:~$ $HOME
bash: /home/william: Is a directory
william@william-Precision-5820-Tower-X-Series:~$ 
```

tab two:
```
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

william@william-Precision-5820-Tower-X-Series:/home/william$ pwd
/home/william
william@william-Precision-5820-Tower-X-Series:/home/william$ $HOME
william@william-Precision-5820-Tower-X-Series:/home/william$ cd
bash: cd: HOME not set
william@william-Precision-5820-Tower-X-Series:/home/william$
```

**Comment by drayer587** [comment]
going to close this issue as after returning to this now, as I can no longer reproduce this. Likely some bug fix elsewhere in the default Ubuntu file manager/terminal
