### ISSUE TITLE
poor rendering of numbers with LaTeXStrings

### ISSUE THREAD

**Issue by lmiq** [jheinen/GR.jl#431]
MWE:

```
julia> using Plots

julia> using Plots, LaTeXStrings

julia> plot([0,1],[0,1],grid=:false)

julia> annotate!(0.5,0.25,text(L"\alpha = 0.99, \beta = 5.6",50))

(@v1.6) pkg> status Plots
      Status `~/.julia/environments/v1.6/Project.toml`
  [91a5bcdd] Plots v1.20.1

(jl_wgaRpm) pkg> status GR
      Status `/tmp/jl_wgaRpm/Project.toml`
  [28b8d3ca] GR v0.59.0

```

result:

![image](https://user-images.githubusercontent.com/31046348/135515390-2e864d5c-f120-4c1a-8375-8e96be9cc203.png)

Note that the dot overlaps with the "nine", and it it too close to the "six". 

How this should look like:

![image](https://user-images.githubusercontent.com/31046348/135515557-62c8d9d0-46b9-44f1-9c09-3bf0c8368b83.png)

**Comment by lmiq** [comment]
By the way, this is a regression introduced at some point in the last few months, as this same figure was ok the first time I plotted it:

![image](https://user-images.githubusercontent.com/31046348/135516867-88fd44b3-983f-46aa-aefa-a83dd1721dbb.png)

**Comment by FlorianRhiem** [comment]
We have been working on improving the LaTeX math emulation and it seems some of the kerning corrections are causing an issue here. I have disabled the additional offsets applied to character combinations including `.` as a [workaround in the GR runtime develop branch](https://github.com/sciapp/gr/commit/6ca04968c6534235102bd8b7db565938e8083105), and will look into why the negative offet is too large.

**Comment by lmiq** [comment]
I'm sorry to disturb, but how can I use this branch? I tried to downgrade, but 0.57 still shows that bug, and 0.55 is already incompatible with other features of the figure I have now.

**Comment by jheinen** [comment]
Could you please try `ENV["GRDIR"]=""; ] build GR`? This should download/install the development version.

**Comment by lmiq** [comment]
I was not able to fix that for now :-( 

Trying that I get, and then adding Plots, 

```
    Building Plots → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/5696200f1f85647b159f7cfe9854a14be522b8cc/build.log`
ERROR: Error building `Plots`: 
ERROR: LoadError: UndefVarError: info not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/Plots/JGPR6/deps/build.jl:6
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [3] top-level scope
   @ none:5
in expression starting at /home/leandro/.julia/packages/Plots/JGPR6/deps/build.jl:5

```

**Comment by lmiq** [comment]
Thanks, that worked: 

![image](https://user-images.githubusercontent.com/31046348/136836340-0580a175-b1b0-4c93-bd98-8d3b49ee9957.png)
