### ISSUE TITLE
Help migrating from Winston.jl

### ISSUE THREAD

**Issue by ezaron** [jheinen/GR.jl#440]
Hi,

I wonder if you can provide any pointers for migrating from Winston.jl? I am looking for simple examples of how to produce good quality basic 2-d line plots with control over linewidth, color, axis labels, etc. I have looked at the source code and examples for linewidth, but the setlinewidth command does not seem to have an effect on subsequent calls to plot.

All the best,

Ed

**Comment by ChasingZenith** [comment]
I think [the domucmentation of GRUtil](https://heliosdrm.github.io/GRUtils.jl/stable/api/attributes/) will be useful.

**Comment by ezaron** [comment]
-thx
