### ISSUE TITLE
Precompilation failed when running "] test GR"

### ISSUE THREAD

**Issue by XiangYyang** [jheinen/GR.jl#450]
Hello, I'm trying using Plots package and it failed. I think the reason is failing precompile GR.

```
Julia Version 1.7.2, Windows x64
```

```bash
] test GR

...(some lines)...

Precompiling project...
  ✗ GR
  48 dependencies successfully precompiled in 23 seconds (31 already precompiled)
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
     Testing Running tests...
ERROR: LoadError: ArgumentError: not a path: `C:\Users\USERNAME\.julia\packages\GR\jpQcZ\deps\deps.jl`
...(stack trace)...
ERROR: LoadError: Failed to precompile GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71] to C:\Users\USERNAME\.julia\compiled\v1.7\GR\jl_7BA8.tmp.
...(stack trace)...
ERROR: Package GR errored during testing
```

I tried to rebuild it, but not working.

Thanks!

**Comment by jheinen** [comment]
I can't reproduce the problem. Did you try to install GR in an empty environment? Are other any (other) packages that prevent an update to the current version?

**Comment by IngoMeyer441** [comment]
> 1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

Does the full report give any hints?

**Comment by XiangYyang** [comment]
Thank you for your reply, I tried it at a empty environment: ```bash ] add GR   [28b8d3ca] + GR v0.64.0     Updating `C:\Users\USERNAME\.julia\environments\v1.7\Manifest.toml`   [28b8d3ca] + GR v0.64.0ip2   [cd3eb016] + HTTP v0.9.17   [83e8ac13] + IniFile v0.5.0   [692b3bcd] + JLLWrappers v1.4.1   [682c06a0] + JSON v0.21.3   [739be429] + MbedTLS v1.0.3   [69de0a69] + Parsers v2.2.2   [21216c6a] + Preferences v1.2.3   [05181044] + RelocatableFolders v0.1.3   [6c6a2e73] + Scratch v1.1.0   [5c2747f8] + URIs v1.3.0   [6e34b625] + Bzip2_jll v1.0.8+0   [83423d85] + Cairo_jll v1.16.1+1   [2e619515] + Expat_jll v2.4.4+0   [b22a6f82] + FFMPEG_jll v4.4.0+0   [a3f928ae] + Fontconfig_jll v2.13.93+0   [d7e528f0] + FreeType2_jll v2.10.4+0   [559328eb] + FriBidi_jll v1.0.10+0   [0656b61e] + GLFW_jll v3.3.6+0   [d2c73de3] + GR_jll v0.64.0+0   [78b55507] + Gettext_jll v0.21.0+0   [7746bdde] + Glib_jll v2.68.3+2   [3b182d85] + Graphite2_jll v1.3.14+0   [2e76f6c2] + HarfBuzz_jll v2.8.1+1   [aacddb02] + JpegTurbo_jll v2.1.2+0   [c1c5ebd0] + LAME_jll v3.100.1+0   [dd4b983a] + LZO_jll v2.10.1+0   [e9f186c6] + Libffi_jll v3.2.2+1   [d4300ac3] + Libgcrypt_jll v1.8.7+0   [7e76a0d4] + Libglvnd_jll v1.3.0+3   [7add5ba3] + Libgpg_error_jll v1.42.0+0   [94ce4f54] + Libiconv_jll v1.16.1+1   [4b2f31a3] + Libmount_jll v2.35.0+0   [89763e89] + Libtiff_jll v4.3.0+0   [38a345b3] + Libuuid_jll v2.36.0+0   [e7412a2a] + Ogg_jll v1.3.5+1   [458c3c95] + OpenSSL_jll v1.1.13+0   [91d4177d] + Opus_jll v1.3.2+0   [2f80f16e] + PCRE_jll v8.44.0+0   [30392449] + Pixman_jll v0.40.1+0   [ea2cea3b] + Qt5Base_jll v5.15.3+0   [a2964d1f] + Wayland_jll v1.19.0+0   [2381bf8a] + Wayland_protocols_jll v1.23.0+0   [02c8fc9c] + XML2_jll v2.9.12+0   [aed1982a] + XSLT_jll v1.1.34+0   [4f6342f7] + Xorg_libX11_jll v1.6.9+4   [0c0b7dd1] + Xorg_libXau_jll v1.0.9+4   [935fb764] + Xorg_libXcursor_jll v1.2.0+4   [a3789734] + Xorg_libXdmcp_jll v1.1.3+4   [1082639a] + Xorg_libXext_jll v1.3.4+4   [d091e8ba] + Xorg_libXfixes_jll v5.0.3+4   [a51aa0fd] + Xorg_libXi_jll v1.7.10+4   [d1454406] + Xorg_libXinerama_jll v1.1.4+4   [ec84b674] + Xorg_libXrandr_jll v1.5.2+4   [ea2f1a96] + Xorg_libXrender_jll v0.9.10+4   [14d82f49] + Xorg_libpthread_stubs_jll v0.1.0+3   [c7cfdc94] + Xorg_libxcb_jll v1.13.0+3   [cc61e674] + Xorg_libxkbfile_jll v1.1.0+4   [12413925] + Xorg_xcb_util_image_jll v0.4.0+1   [2def613f] + Xorg_xcb_util_jll v0.4.0+1   [975044d2] + Xorg_xcb_util_keysyms_jll v0.4.0+1   [0d47668e] + Xorg_xcb_util_renderutil_jll v0.3.9+1   [c22f9ab0] + Xorg_xcb_util_wm_jll v0.4.1+1   [35661453] + Xorg_xkbcomp_jll v1.4.2+4   [33bec58e] + Xorg_xkeyboard_config_jll v2.27.0+4   [c5fb5394] + Xorg_xtrans_jll v1.4.0+3   [3161d3a3] + Zstd_jll v1.5.2+0   [0ac62f75] + libass_jll v0.15.1+0   [f638f0a6] + libfdk_aac_jll v2.0.2+0   [b53b4c65] + libpng_jll v1.6.38+0   [f27f6e37] + libvorbis_jll v1.3.7+1   [1270edf5] + x264_jll v2021.5.5+0   [dfaa095f] + x265_jll v3.5.0+0   [d8fb68d0] + xkbcommon_jll v0.9.1+5   [0dad84c5] + ArgTools   [56f22d72] + Artifacts   [2a0f44e3] + Base64   [ade2ca70] + Dates   [8bb1440f] + DelimitedFiles   [f43a241f] + Downloads   [b77e0a4c] + InteractiveUtils   [b27032c2] + LibCURL   [76f85450] + LibGit2   [8f399da3] + Libdl   [37e2e46d] + LinearAlgebra   [56ddb016] + Logging   [d6f4376e] + Markdown   [a63ad114] + Mmap   [ca575930] + NetworkOptions   [44cfe95a] + Pkg   [de0858da] + Printf   [3fa0cd96] + REPL   [9a3f8284] + Random   [ea8e919c] + SHA   [9e88b42a] + Serialization   [6462fe0b] + Sockets   [fa267f1f] + TOML   [a4e569a6] + Tar   [8dfed614] + Test   [cf7118a7] + UUIDs   [4ec0a83e] + Unicode   [e66e0078] + CompilerSupportLibraries_jll   [deac9b47] + LibCURL_jll   [29816b5a] + LibSSH2_jll   [c8ffd9c3] + MbedTLS_jll   [14a3606d] + MozillaCACerts_jll   [4536629a] + OpenBLAS_jll   [83775a58] + Zlib_jll   [8e850b90] + libblastrampoline_jll   [8e850ede] + nghttp2_jll   [3f19e933] + p7zip_jll Precompiling project...   ✗ GR   79 dependencies successfully precompiled in 63 seconds   1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package ``` Then: ```bash import Pkg; Pkg.precompile()   ✗ GR   0 dependencies successfully precompiled in 3 seconds (79 already precompiled) ERROR: The following 1 direct dependency failed to precompile: GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71] Failed to precompile GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71] to C:\Users\USERNAME\.julia\compiled\v1.7\GR\jl_A85A.tmp. ERROR: LoadError: ArgumentError: not a path: `C:\Users\USERNAME\.julia\packages\GR\jpQcZ\deps\deps.jl` Stacktrace:  [1] RelocatableFolders.Path(mod::Module, dir::String, path::String)    @ RelocatableFolders C:\Users\USERNAME\.julia\packages\RelocatableFolders\PYUl8\src\RelocatableFolders.jl:51  [2] top-level scope    @ C:\Users\USERNAME\.julia\packages\GR\jpQcZ\src\GR.jl:36  [3] include    @ .\Base.jl:418 [inlined]  [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)    @ Base .\loading.jl:1318  [5] top-level scope    @ none:1  [6] eval    @ .\boot.jl:373 [inlined]  [7] eval(x::Expr)    @ Base.MainInclude .\client.jl:453  [8] top-level scope    @ none:1 in expression starting at C:\Users\USERNAME\.julia\packages\GR\jpQcZ\src\GR.jl:2 Stacktrace:  [1] pkgerror(msg::String)    @ Pkg.Types E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\Types.jl:68  [2] precompile(ctx::Pkg.Types.Context; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})    @ Pkg.API E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:1362  [3] precompile    @ E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:1013 [inlined]  [4] #precompile#220    @ E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:1011 [inlined]  [5] precompile()    @ Pkg.API E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:1011  [6] top-level scope    @ REPL[2]:1 ``` And, I tried using administrator permission and it&#39;s not helpful. 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月22日(星期二) 下午5:29
收件人: "jheinen/GR.jl";
抄送: "Author";
主题: Re: [jheinen/GR.jl] Precompilation failed when running &quot;] test GR&quot; (Issue #450)





 
I can't reproduce the problem. Did you try to install GR in an empty environment? Are other any (other) packages that prevent an update to the current version?
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XiangYyang** [comment]
Thank you for your reply, I tried it at a empty environment:

```
] add GR

  [28b8d3ca] + GR v0.64.0ip2
  [cd3eb016] + HTTP v0.9.17
  [83e8ac13] + IniFile v0.5.0
  [692b3bcd] + JLLWrappers v1.4.1
  [682c06a0] + JSON v0.21.3
  [739be429] + MbedTLS v1.0.3
  [69de0a69] + Parsers v2.2.2
  [21216c6a] + Preferences v1.2.3
  [05181044] + RelocatableFolders v0.1.3
  [6c6a2e73] + Scratch v1.1.0
  [5c2747f8] + URIs v1.3.0
  [6e34b625] + Bzip2_jll v1.0.8+0
  [83423d85] + Cairo_jll v1.16.1+1
  [2e619515] + Expat_jll v2.4.4+0
  [b22a6f82] + FFMPEG_jll v4.4.0+0
  [a3f928ae] + Fontconfig_jll v2.13.93+0
  [d7e528f0] + FreeType2_jll v2.10.4+0
  [559328eb] + FriBidi_jll v1.0.10+0
  [0656b61e] + GLFW_jll v3.3.6+0
  [d2c73de3] + GR_jll v0.64.0+0
  [78b55507] + Gettext_jll v0.21.0+0
  [7746bdde] + Glib_jll v2.68.3+2
  [3b182d85] + Graphite2_jll v1.3.14+0
  [2e76f6c2] + HarfBuzz_jll v2.8.1+1
  [aacddb02] + JpegTurbo_jll v2.1.2+0
  [c1c5ebd0] + LAME_jll v3.100.1+0
  [dd4b983a] + LZO_jll v2.10.1+0
  [e9f186c6] + Libffi_jll v3.2.2+1
  [d4300ac3] + Libgcrypt_jll v1.8.7+0
  [7e76a0d4] + Libglvnd_jll v1.3.0+3
  [7add5ba3] + Libgpg_error_jll v1.42.0+0
  [94ce4f54] + Libiconv_jll v1.16.1+1
  [4b2f31a3] + Libmount_jll v2.35.0+0
  [89763e89] + Libtiff_jll v4.3.0+0
  [38a345b3] + Libuuid_jll v2.36.0+0
  [e7412a2a] + Ogg_jll v1.3.5+1
  [458c3c95] + OpenSSL_jll v1.1.13+0
  [91d4177d] + Opus_jll v1.3.2+0
  [2f80f16e] + PCRE_jll v8.44.0+0
  [30392449] + Pixman_jll v0.40.1+0
  [ea2cea3b] + Qt5Base_jll v5.15.3+0
  [a2964d1f] + Wayland_jll v1.19.0+0
  [2381bf8a] + Wayland_protocols_jll v1.23.0+0
  [02c8fc9c] + XML2_jll v2.9.12+0
  [aed1982a] + XSLT_jll v1.1.34+0
  [4f6342f7] + Xorg_libX11_jll v1.6.9+4
  [0c0b7dd1] + Xorg_libXau_jll v1.0.9+4
  [935fb764] + Xorg_libXcursor_jll v1.2.0+4
  [a3789734] + Xorg_libXdmcp_jll v1.1.3+4
  [1082639a] + Xorg_libXext_jll v1.3.4+4
  [d091e8ba] + Xorg_libXfixes_jll v5.0.3+4
  [a51aa0fd] + Xorg_libXi_jll v1.7.10+4
  [d1454406] + Xorg_libXinerama_jll v1.1.4+4
  [ec84b674] + Xorg_libXrandr_jll v1.5.2+4
  [ea2f1a96] + Xorg_libXrender_jll v0.9.10+4
  [14d82f49] + Xorg_libpthread_stubs_jll v0.1.0+3
  [c7cfdc94] + Xorg_libxcb_jll v1.13.0+3
  [cc61e674] + Xorg_libxkbfile_jll v1.1.0+4
  [12413925] + Xorg_xcb_util_image_jll v0.4.0+1
  [2def613f] + Xorg_xcb_util_jll v0.4.0+1
  [975044d2] + Xorg_xcb_util_keysyms_jll v0.4.0+1
  [0d47668e] + Xorg_xcb_util_renderutil_jll v0.3.9+1
  [c22f9ab0] + Xorg_xcb_util_wm_jll v0.4.1+1
  [35661453] + Xorg_xkbcomp_jll v1.4.2+4
  [33bec58e] + Xorg_xkeyboard_config_jll v2.27.0+4
  [c5fb5394] + Xorg_xtrans_jll v1.4.0+3
  [3161d3a3] + Zstd_jll v1.5.2+0
  [0ac62f75] + libass_jll v0.15.1+0
  [f638f0a6] + libfdk_aac_jll v2.0.2+0
  [b53b4c65] + libpng_jll v1.6.38+0
  [f27f6e37] + libvorbis_jll v1.3.7+1
  [1270edf5] + x264_jll v2021.5.5+0
  [dfaa095f] + x265_jll v3.5.0+0
  [d8fb68d0] + xkbcommon_jll v0.9.1+5
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [4536629a] + OpenBLAS_jll
  [83775a58] + Zlib_jll
  [8e850b90] + libblastrampoline_jll
  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll
✗ GR
  79 dependencies successfully precompiled in 63 seconds
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
```

Then:

```
import Pkg; Pkg.precompile()

  ✗ GR
  0 dependencies successfully precompiled in 3 seconds (79 already precompiled)

ERROR: The following 1 direct dependency failed to precompile:

GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71]

Failed to precompile GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71] to C:\Users\USERNAME\.julia\compiled\v1.7\GR\jl_A85A.tmp.
ERROR: LoadError: ArgumentError: not a path: `C:\Users\USERNAME\.julia\packages\GR\jpQcZ\deps\deps.jl`
Stacktrace:
 [1] RelocatableFolders.Path(mod::Module, dir::String, path::String)
   @ RelocatableFolders C:\Users\USERNAME\.julia\packages\RelocatableFolders\PYUl8\src\RelocatableFolders.jl:51
 [2] top-level scope
   @ C:\Users\USERNAME\.julia\packages\GR\jpQcZ\src\GR.jl:36
 [3] include
   @ .\Base.jl:418 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base .\loading.jl:1318
 [5] top-level scope
   @ none:1
 [6] eval
   @ .\boot.jl:373 [inlined]
 [7] eval(x::Expr)
   @ Base.MainInclude .\client.jl:453
 [8] top-level scope
   @ none:1
in expression starting at C:\Users\USERNAME\.julia\packages\GR\jpQcZ\src\GR.jl:2
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\Types.jl:68
 [2] precompile(ctx::Pkg.Types.Context; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:1362
 [3] precompile
   @ E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:1013 [inlined]
 [4] #precompile#220
   @ E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:1011 [inlined]
 [5] precompile()
   @ Pkg.API E:\Tools\Julia-1.7.2\share\julia\stdlib\v1.7\Pkg\src\API.jl:1011
 [6] top-level scope
   @ REPL[2]:1
``` And, I tried using administrator permission and it&[#39](https://github.com/jheinen/GR.jl/pull/39);s not helpful.

**Comment by jheinen** [comment]
We are wondering why the paths in the stack trace contain the directory `USERNAME`. Is this really your login name? Are you installing in a Windows CMD (or Power) shell (recommended) or in a Jupyter environment?

**Comment by XiangYyang** [comment]
> We are wondering why the paths in the stack trace contain the directory `USERNAME`. Is this really your login name? Are you installing in a Windows CMD (or Power) shell (recommended) or in a Jupyter environment?
> 
> Or, is your user name `向阳` (`Xiang Yyang`), which might be a problem within Julia/IJulia and thus is replaced by `USERNAME` - only a guess?

I'm sure it's my login name

That's the school computer, so I replaced my login name. And, a strange thing is that I tried "] add GR" on my own computer and it's working. A little difference is the Julia REPL installation path.

Finally, I reinstalled Julia and it's fixed.

I guess the reason may be the installation path?
