### ISSUE TITLE
Using GR (directly or via Plots) fails in Julia 1.8.1 M1: incompatible architecture. 

### ISSUE THREAD

**Issue by kellertuer** [jheinen/GR.jl#468]
When I am in a Pluto notebook on my M1 Mac and do two cells with

```
using Plots,GR
```
and
```
GR.scatter([1,2,3],[3,4,2])
```
(the same error happens if I use scatter from plots)

I get the error message

```
could not load library "libGR.dylib"
dlopen(~/.julia/packages/GR/uG7UO/src/../deps/gr/lib/libGR.dylib, 0x0001): tried: 
'~/.julia/packages/GR/uG7UO/src/../deps/gr/lib/libGR.dylib' (mach-o file, but is an incompatible architecture (have (x86_64),
need (arm64e))), '~/.julia/packages/GR/uG7UO/deps/gr/lib/libGR.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

What am I doing wrong on Julia 1.8.1 (of course the arm64 variant):
```
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

**Comment by jheinen** [comment]
I cannot reproduce the problem. I get:
```
file /usr/local/lib/julia/artifacts/5711513ad6d2e87586a9918861b61e9245b1a6f3/lib/libGR.dylib
/usr/local/lib/julia/artifacts/5711513ad6d2e87586a9918861b61e9245b1a6f3/lib/libGR.dylib: Mach-O 64-bit dynamically linked shared library arm64
```
Are you probably using a Julia installation from an (older) Intel host?

**Comment by kellertuer** [comment]
Ah, I think I at least see how this might come.

I switched to Juliaup such that it is easier to use old versions (when issues come up with my packages on old versions) and probably Julia 1.7 or 1.6 in juliaup might be running using Rosetta2, if one of them installed some GR somewhen (I did not actively do that), then there might be an artefact (even reappearing).

My problem is
a) I can not avoid that since old versions might run with rosetta and I can not change that
b) I have no clue how to fix above error on Julia 1.8.1? Since I was not aware of such problems, I expected a fresh Pluto to download the most recent version and (usually) to “just work”?

I am also not sure why Julia 1.7 and 1.8 would share artefacts?

**Comment by jheinen** [comment]
I'd really like to help you, but those things are mostly outside the logic of the GR distribution. I also can't say anything about how Juliaup and Pluto interact - I never used Juliaup. As for Pluto, I've already had discussions with their developers to create a way to disable the internal package management in Pluto. Unfortunately, they don't see the need for it.

The only workaround I can offer (with the latest GR release 0.68.0) is to explicitly set the `GRDIR` environment variable to use a local GR installation.

**Comment by kellertuer** [comment]
Well juliaup just handles different versions of Julia, that should just have the effect that the older ones (1.6, 1.7) run with Rosetta and 1.8 runs with native M1, which seems to be the cause here.

I am surprsied that a Pluto notebook (the main thing to have in mind here is that they create a local environment and activate that on start. They have a mode to disable that already actually, just a cell with `using Pkg;` should do the job (even with a warning).

But even then it seems that the main problem here is that if I start Julia 1.7 (Rosetta / emulated Intel) and add GR (or Plots) the Intel artefact gets installed and works fine.
But then quitting and starting Julia 1.8 and adding GR (or Plots) there installs that but doe snot install another (second) artefact with M1 arch? Could that maybe be addressed somewhere?

**Comment by jheinen** [comment]
I don't know who to address this problem to. One solution might be universal binaries - but that would be a big change in the binary builder setups. I have created such a [GR distribution](https://gr-framework.org/downloads/gr-latest-Darwin-universal.tar.gz) for our purposes - but this is not a solution for the general public.

**Comment by kellertuer** [comment]
So what for now can solve the problem is to manually remove the file mentioned in the error message and add/rebuild GR. But that then has to be done every time I switch back and forth between 1.7 and 1.8; and though my day-to-day version is 1.8, I do need GR on 1.7 to run the test suite we have.
