### ISSUE TITLE
Problem showing a png() using Plots.plot(img)

### ISSUE THREAD

**Issue by sje30** [jheinen/GR.jl#47]
Hi,

Not sure if this should go to GR.jl or Plots.jl... (CC @tbreloff) 

But when I try to load a simple image using v0.5 Julia and latest release of packages, the plot is okay in pyplot, but not gr:

```
using Plots, Images
f = expanduser("~/.julia/v0.5/Images/docs/src/img/rose_hsv.png")
img = Images.load(f)
pyplot()
plot(img)

gr()
plot(img)
```
Results in the following two windows:

<img width="1219" alt="ohoh" src="https://cloud.githubusercontent.com/assets/1095067/19832814/ad351dcc-9e25-11e6-91e7-aa7526b5ee9f.png">

**Comment by sje30** [comment]
(ps @tbreloff: I was following the example from your documentation at: https://juliaplots.github.io/examples/gr/#images

but the code seems to rely on the PlotReferenceImages folder which I think is no longer created.)

**Comment by tbreloff** [comment]
This is known and unsolved. And yes I should change that example to use
TestImages.

**Comment by sje30** [comment]
ok, thanks!
