### ISSUE TITLE
GR + Atom @Mac

### ISSUE THREAD

**Issue by missperovaz** [jheinen/GR.jl#48]
Hi Josef,

I'm using Atom, GR directly (using GR), in a mac computer.
As I was facing the issue, already reported, where GKS has to be opened, I'm trying to get plots into the plots pane of Atom.

Issues: 

in the following example:

```
x = linspace(0,10,150)
y = cos(5*x)

title("2-D Line Plot")
xlabel("x")
ylabel("cos(5x)")
plot(x,y,"b")
```

title, xlabel, ylabel are not printed if I write like this, if I execute them after the plot command, the commands title, xlabel, and ylabel overwrite the previous one. I've tried hold(true), but then I get a blank image.

```
GR.beginprint("$dataPath$pltfile")
plot(something)
GR.endgraphics()

GR.beginprint("$dataPath$pltfile2")
plot(something else)
GR.endgraphics()
```

I don't get to save the second plot into the pltfile2 file. 

`GR.setmarkertype(4)`
doesn't work for me either

 thanks,
Let me know if you have any examples on how to have inline plots in atom.

thanks a lot

**Comment by jheinen** [comment]
I'll have to check the print logic in the convenience layer. There's sth going wrong.

Attributes (like ``setmarkertype``) will be overwritten by the keyword arguments. You probably want to use another ``linespec`` in your ``plot`` command, e.g.

    using GR
    inline("atom")
    x = linspace(0,10,150)
    y = cos(5*x)
    title("2-D Line Plot")
    xlabel("x")
    ylabel("cos(5x)")
    plot(x,y,"-o")

... to draw a line with marker symbols.

**Comment by missperovaz** [comment]
thanks Josef, 

I'm using scatter.
