### ISSUE TITLE
Using binary builder

### ISSUE THREAD

**Issue by isentropic** [jheinen/GR.jl#481]
I recently stumbled upon https://github.com/JuliaPackaging/BinaryBuilder.jl
do you think that it might simplify the build process? Just wondering, I have zero knowledge about binaries and julia

**Comment by jheinen** [comment]
Could you please describe your problem?

**Comment by isentropic** [comment]
This not a problem at all. Gr installation has become more stable now. Just wondering if you are aware of binarybuilder package
