### ISSUE TITLE
Synchronize with build_tarballs.jl in Yggdrasil

### ISSUE THREAD

**Issue by mkitti** [jheinen/GR.jl#484]
@sjkelly , I notice that you made [changes](https://github.com/jheinen/GR.jl/commit/e538f2da9c9f0461b3429740bcd8bb8785856871) to the copy of build_tarballs.jl here via #465, but those changes are not reflected in Yggdrasil. Did you intend for those changes to made to Yggdrasil?

https://github.com/JuliaPackaging/Yggdrasil/blob/1f1aa0f6f9bdef97b4f5b879b2a168991fd9157d/G/GR/build_tarballs.jl

**Comment by sjkelly** [comment]
Yes, that is the case.

**Comment by sjkelly** [comment]
Yeah I never made the upstream commit. We should test locally first.

**Comment by mkitti** [comment]
Fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/5784
