### ISSUE TITLE
Grid drawn for imshow

### ISSUE THREAD

**Issue by tonyduan** [jheinen/GR.jl#49]
I recently updated to the latest ``master`` branch and noticed that ``imshow`` now draws a grid background for the plot:

`imshow(randn((12,10)))`

![unknown](https://cloud.githubusercontent.com/assets/1163598/20001201/541f5eca-a238-11e6-9b5d-5dd922cdcc9d.png)

In a build a few weeks ago, the background was not there.

Thanks in advance for the help!

**Comment by jheinen** [comment]
Doesn't make sense. I restored the old (MATLAB-like) behaviour in 1261660.

**Comment by tonyduan** [comment]
Perfect, thanks a lot!
