### ISSUE TITLE
XIO:  fatal IO error 11

### ISSUE THREAD

**Issue by KajWiik** [jheinen/GR.jl#5]
```julia
julia> include("/tmp/anim.jl")
INFO: Loading help data...
fps (mpl): 19.0
fps  (GR): 115.0
  speedup:    6.1

julia> XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 48081 requests (47844 known processed) with 0 events remaining.
X Protocol error detected by server: BadWindow (invalid Window parameter)
Failed request major op code 15 (X_QueryTree)
Invoked from within GKS function id 3
```

**Comment by jheinen** [comment]
Did the X Window (titles GKS 5) appear an show the animation?

Did the error message appear when you close the window (in the windows manager) before trying to close the window in GR? If so, you can simply ignore it. May be I should catch this exception and give a "better" error message to the user (in the next release).

**Comment by KajWiik** [comment]
Ah, that was the case, should have thought of that, sorry... GR.close() closes the window OK.

In fact at first I got the GKS 5 window but did not see any animation at first and thought of some more serious problem. After I inserted a 10ms sleep in the loop the animation became visible :-), very impressive.

GR is especially interesting in real time applications where you want display some data from instruments etc... Great, thanks!

**Comment by jheinen** [comment]
You can omit the sleep() call if you force the GR graphics to be display with double buffering:

``export GKS_DOUBLE_BUF=1``

I have plans to enable double buffering automatically within the GR framework, but I did not have the right idea yet ...

Anyway, with the above setting, the display should be "smooth" :-) You can also do this setting in your Julia (or Python) script.

**Comment by simulkade** [comment]
First of all, FANTASTIC work!
I have the same problem with GR. When I close the window from the window manager I get this error:
```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 280 requests (280 known processed) with 2 events remaining.
```
If I try to plot again, nothing happens.  
I tried to close the window using closegks(), but I get the following error:
```
GKS: GKS not in proper state. GKS must be in the state GKOP in routine CLOSE_GKS
```
Any idea?

**Comment by jheinen** [comment]
The problem is that it's hard to find out whether the window has been closed by the window manager or due to a communication problem. That's because the underlying GKS does not have a real event loop. I'm aware of this problem and will try to find a reasonable solution for non-event driven programs.

BTW: To reset GR's graphics subsystem, you can use the ``GR.emergencyclosegks()`` method ...

**Comment by simulkade** [comment]
Thanks a lot for quick reply. `GR.emergencyclosegks()` is a great help.
