### ISSUE TITLE
another `contour` bug

### ISSUE THREAD

**Issue by t-bltg** [jheinen/GR.jl#501]
@jheinen, [this bug](https://github.com/JuliaPlots/Plots.jl/issues/1745) can be reproduced using plain `GR` commands:

```julia
using GR
x = collect(1:5)
y = collect(3:9)
f(x,y) = x^2 * sqrt(y)
contour(x, y, f, levels=100)
```

**Comment by t-bltg** [comment]
Here is the output (on `linux`):

![cont](https://user-images.githubusercontent.com/13423344/203933486-e196b148-13d6-4c63-8f2e-9df66127c198.png)

**Comment by jheinen** [comment]
But this doesn't work in Plots either? Tried this:
```
using GR
x = 1:5
y = 3:9
z = x.^2 .* sqrt.(y')
contour(x, y, z, levels=100)
```

**Comment by jheinen** [comment]
Aah, I see.

**Comment by t-bltg** [comment]
Yes, sorry wrong paste of the example, I've edited it this morning.
