### ISSUE TITLE
Plot not displayed with 1 million points

### ISSUE THREAD

**Issue by juliohm** [jheinen/GR.jl#51]
The snippet of code below with `Plots.jl` does not display a plot in Jupyter notebooks:

```julia
using Plots
gr()

N = 1000000

x = randn(N)
y = randn(N)
z = randn(N)
scatter(x, y, z, markersize=.1, legend=false)
```

If I reduce the number of points, the plot is displayed.

**Comment by jheinen** [comment]
GR uses SVG for rendering the Plots output when running in a browser context. In your example (with a million points), this does not make sense as the resulting SVG output is too big (about 600 MBytes) for most browsers and cannot be displayed in a reasonable time. Using PNG output solves the problem.

```julia
using GR
inline("png")

N = 1000000

x = randn(N)
y = randn(N)
z = randn(N)

setmarkertype(GR.MARKERTYPE_DOT)
scatter3(x, y, z)
```

This should also work with `Plots`:

```julia
using Plots
gr(format="png")
...
```

**Comment by juliohm** [comment]
Awesome, it is working now, and super fast. Thank you @jheinen.
