### ISSUE TITLE
GKS environment variable name 

### ISSUE THREAD

**Issue by zsz00** [jheinen/GR.jl#510]
I've seen the gks environment variable set in several issues, 
Multiple similar variable names are involved:
GKSWSTYPE, GKS_WSTYPE, GKSwstype

Which one should I use?

**Comment by jheinen** [comment]
`GKS_WSTYPE` and `GKSwstype` change the default output device. But what is the actual problem?

**Comment by zsz00** [comment]
the actual problem is  I don't kown use which one. 
so, GKS_WSTYPE and GKSwstype is all ok, GKSWSTYPE is not right environment variable.

**Comment by jheinen** [comment]
There is no need to use any of those environments unless you want to redirect the output to another device!?

**Comment by zsz00** [comment]
yes, I want to redirect the output to another device. 
I met GKS error , and read from : 
https://discourse.julialang.org/t/unable-to-display-plot-using-the-repl-gks-errors/12826/1

**Comment by jheinen** [comment]
This should work on a headless system:
```julia
ENV["GKS_WSTYPE"]="nul"
using GR
plot(randn(10))
savefig("test.png")
```
