### ISSUE TITLE
BSOD caused by using invalid ylim parameter with heatmap

### ISSUE THREAD

**Issue by OliverDudgeon** [jheinen/GR.jl#517]
I managed to cause a BSOD (error was `VIDEO MEMORY MANAGEMENT INTERNAL`) when using Plots.jl with the default GR backend. This seems to always be caused when using `heatmap` with a `ylims` for a range that doesn't have any overlap with the provided ydata. 

For example:
```julia
maxes = 10:5:200
samples = 10:4000:800_000

values = rand(length(maxes), length(samples))

heatmap(maxes, samples, values, xlabel="max", ylabel="sample", ylims=(0,1))# adding the ylims causes a BSOD
```

I know this isn't something that a user would inetntionally do, I just did it by mistake but it shouldn't be causing a full system failure. 

I've only tried this inside a Jupyter notebook in VSCode.

**Comment by jheinen** [comment]
The parameters passed to `GR.jl` from `Plots.jl` make no sense. So, the problem can only be fixed in `Plots.jl`. Nevertheless, we will add a sanity check (in GR) to avoid such problems.
