### ISSUE TITLE
scatter or plot shifts heatmap, when in log-scale

### ISSUE THREAD

**Issue by tnadolny** [jheinen/GR.jl#519]
Hi,
In this code, the presence of both scatter and the log-scale seems to shift the heatmap. This is not what should happen, right?
```julia
heatmap(1:10,1:10,rand(10,10))
scatter!([5],[10],label = nothing) # or plot!(something)
plot!(yscale=:log10)
#GR v0.72.5
#Plots v1.38.12
```
![image](https://github.com/jheinen/GR.jl/assets/104072493/f2016819-0ec1-4448-8c5d-3a044fb8d2ba)

**Comment by jheinen** [comment]
This behaviour can only be fixed in Plots.jl. This is the GR version:
```julia
using GR
heatmap(1:10, 1:10, rand(10,10), ylog=true)
```
<img width="715" alt="Screenshot 2023-05-23 at 17 05 19" src="https://github.com/jheinen/GR.jl/assets/5718244/8efc3229-c01e-41d9-879b-7b642e555c49">
