### ISSUE TITLE
Problem with setting line attributes on Windows

### ISSUE THREAD

**Issue by mpastell** [jheinen/GR.jl#52]
For some reason the following doesn't set the line attributes for me on Windows 7 (GR 0.18) in `GKS 5` window . (I just get a thin black line). 

```julia
GR.setlinetype(1)
GR.setlinecolorind(10)
GR.setlinewidth(3)
```
It works if output SVG and also for the on screen device on Ubuntu 16.04. For linetype 2 output on sceen works also on Windows:

```julia
GR.setlinetype(2)
GR.setlinecolorind(10)
GR.setlinewidth(3)
```

This produces thicker dotted blue line.

**Comment by jheinen** [comment]
This problem has just been fixed in https://github.com/jheinen/gr/commit/de9017347cdd856743de8b0fc3e463d74455ae37. New binaries coming soon ...

**Comment by mpastell** [comment]
Great, thanks!
