### ISSUE TITLE
Qt6 support testing

### ISSUE THREAD

**Issue by barche** [jheinen/GR.jl#524]
With PR https://github.com/JuliaPackaging/Yggdrasil/pull/7016 GR.jl will use Qt6 instead of Qt5. This is meant as a less disruptive alternative to PR #518.

Testing this is already possible now, by running (in Pkg mode):

```
add https://github.com/barche/GR_jll.jl.git
add GR
```

From then on, all plotting commands from the REPL should use a Qt6 window. For Wayland users, you can additionally add and use `Qt6Wayland_jll`, this should give a native Wayland window now.

**Comment by jheinen** [comment]
@barche : I published the new runtime (v0.72.9), see [JuliaPackaging/Yggdrasil/pull/7059](https://github.com/JuliaPackaging/Yggdrasil/pull/7059). Are there any other requirements before I tag a new GR.jl version? Is there anything I might have forgotten?

**Comment by barche** [comment]
No, other than the compat change suggested in https://github.com/JuliaPackaging/Yggdrasil/pull/7059 it should work without any changes to GR.jl itself. The compat will avoid issues when we upgrade Qt.
