### ISSUE TITLE
GR.jl doesn't come with 'Plots' package on apple silicon

### ISSUE THREAD

**Issue by PinkGenji** [jheinen/GR.jl#529]
Hi, I am new to Julia. I am learning Julia on both Mac and Windows. When I install "Plots" on windows, everything works fine. But When I try to install Plots and use the plot() function, I got the error 'could not load library "libGR.so"'. After a look on the terminal, it seems GR package wasn't included in the Mac installation list. Tried re-installing and it didn't work.

Julia v1.9.3 + GR v0.72.10 + MacOS v14.0

**Comment by jheinen** [comment]
I can't reproduce this on any macOS platform. I also have no idea why `libGR.so` is searched for and not - as expected - `libGR.dylib`.

Could you please start in a fresh environment (`rm -rf .julia`) and try to `] add GR`? In case of problems, please start Julia with `JULIA_DEBUG=GR julia`.

**Comment by PinkGenji** [comment]
Thanks for helping!  I ended up re-installing Julia and the problem was solved!
