### ISSUE TITLE
example gtk_ex.jl error on Win10

### ISSUE THREAD

**Issue by AStupidBear** [jheinen/GR.jl#53]
![2017-01-19_173432](https://cloud.githubusercontent.com/assets/16422976/22101271/b5bee440-de6d-11e6-99b1-b0257cfb49db.png)

It kept displaying "Contour ...", but cannot show the plot.

**Comment by jheinen** [comment]
Unfortunately, I cannot reproduce the problem on my Windows 10 VM. Which Julia / GR versions are you using?

![screen shot 2017-01-19 at 15 14 55](https://cloud.githubusercontent.com/assets/5718244/22110052/9e9029cc-de5a-11e6-8858-becd1c54d7ce.png)

**Comment by AStupidBear** [comment]
commit version: 1273a2507ffac0afe0ff8835672202583f1d3fb7

**Comment by AStupidBear** [comment]
This issue is solved in the newest release!
