### ISSUE TITLE
Problem with Qt when precompiling GR_jll

### ISSUE THREAD

**Issue by marcusbritanicus** [jheinen/GR.jl#537]
I get the following error when I am installing/precompiling GR_jll, which is needed for the Plots package.

```
julia> using GR_jll
Precompiling GR_jll
        Info Given GR_jll was explicitly requested, output will be shown live 
ERROR: LoadError: InitError: could not load library "/home/cosmos/.julia/artifacts/466e859891e85a1f8a887e712f17b1645ec9c803/lib/libQt6PrintSupport.so"
/usr/lib64/libQt6Widgets.so.6: undefined symbol: _ZN21QMessageDialogOptions18clearCustomButtonsEv, version Qt_6_PRIVATE_API
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/JLLWrappers/pG9bm/src/products/library_generators.jl:63 [inlined]
 [2] __init__()
   @ Qt6Base_jll ~/.julia/packages/Qt6Base_jll/fqleI/src/wrappers/x86_64-linux-gnu-cxx11.jl:72
 [3] top-level scope
   @ ~/.julia/packages/JLLWrappers/pG9bm/src/toplevel_generators.jl:192
 [4] top-level scope
   @ stdin:3
during initialization of module Qt6Base_jll
in expression starting at /home/cosmos/.julia/packages/GR_jll/QVoGS/src/wrappers/x86_64-linux-gnu-cxx11.jl:14
in expression starting at /home/cosmos/.julia/packages/GR_jll/QVoGS/src/GR_jll.jl:2
in expression starting at stdin:3
  ✗ GR_jll
  0 dependencies successfully precompiled in 1 seconds. 80 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

GR_jll [d2c73de3-f751-5644-a686-071e5b155ba9]

Failed to precompile GR_jll [d2c73de3-f751-5644-a686-071e5b155ba9] to "/home/cosmos/.julia/compiled/v1.10/GR_jll/jl_88sRda".
```

While I understand that there may not be much that GR_jll team can do about this, my question is slightly different. **Can we precompile/install GR_jll without Qt6Base_jll?**

**Comment by jheinen** [comment]
The loader tries to include `/usr/lib64/libQt6Widgets.so` to resolve symbols in `GR_jll` - this shouldn't happen as the required run-time should be provided in your `.julia/artifacts` tree. Which Linux system are you using? Was `LD_LIBRARY_PATH` explicitly set when starting Julia?

**Comment by marcusbritanicus** [comment]
@jheinen Thanks for the quick reply. I'm using Artix/Arch. Yes, I do have `LD_LIBRARY_PATH` explicitly set so that I can use binaries which link to a few libraries in `/opt`

**Comment by marcusbritanicus** [comment]
@jheinen Thanks for the tip! I started julia after explicitly unsetting `LD_LIBRARY_PATH` and I was able to precompile `GR_jll` and `Plots`. 

PS: This issue is resolved from my side and you can close it if you wish to. However, from what I understand, I think GR_jll should be ignoring the `LD_LIBRARY_PATH` isn't it?

**Comment by jheinen** [comment]
> PS: This issue is resolved from my side and you can close it if you wish to. However, from what I understand, I think GR_jll should be ignoring the `LD_LIBRARY_PATH` isn't it?

Thanks for the information - but I suspect this needs to be investigated elsewhere.
