### ISSUE TITLE
GKS: file open error ; can't open SVG file

### ISSUE THREAD

**Issue by lvyuemeng** [jheinen/GR.jl#547]
OS: windows 11 
VSCode version: 1.90.1
In vscode repl using Plots:

>  GKS: file open error (C:\Users\吕粤蒙\AppData\Local\Temp\jl_ixshsrUJIN.svg)
> open: No such file or directory
> GKS: can't open SVG file
> open: No such file or directory

the problem still occur if using plot in powershell
the output disappears with `GR.inline("png")`, but the problem still occurs.

**Comment by jheinen** [comment]
According to this path, the setting for your home directory seems to be wrong: `C:\Users%username%\AppData\Local\Temp\jl_ixshsrUJIN.svg`. We do not use the `%username%` substitution at any point, so the problem is probably in the VSCode configuration.

**Comment by jheinen** [comment]
GR does not support non-UTF-8 file names - you could probably change the path for temporary files using the `TEMP` or `TMP` variables.

**Comment by lvyuemeng** [comment]
> GR does not support non-UTF-8 file names - you could probably change the path for temporary files using the `TEMP` or `TMP` variables.

Does the julia extension setting: "Plots path" help? I try to add a new path but it seems doesn't work, or should I change the `TEMP` as you said?

**Comment by jheinen** [comment]
I don't know the `Plots.jl` `Plots paths` setting. However, I suspect that a "forced" path for temporary files (`TEMP` or `TMP`) should help.

**Comment by lvyuemeng** [comment]
> I don't know the `Plots.jl` `Plots paths` setting. However, I suspect that a "forced" path for temporary files (`TEMP` or `TMP`) should help.

I mean the vscode julia extension setting: Plots path, anyway changing the path of `TEMP` really helps! Thanks!

**Comment by jheinen** [comment]
That's good news. If we can help on GR side, let me know. At the moment, however, I don't know how.

**Comment by IngoMeyer441** [comment]
> the %username% is actually 吕粤蒙 which is non-UTF-8. so I guess this is the problem.

Only for our understanding: So the symbols "吕粤蒙" are not part of the Unicode character set? I ask, because UTF-8 can encode every Unicode character, so a non-UTF-8 character cannot be inside Unicode. So how is this supported by Windoes then?

**Comment by lvyuemeng** [comment]
> > the %username% is actually 吕粤蒙 which is non-UTF-8. so I guess this is the problem.
> 
> Only for our understanding: So the symbols "吕粤蒙" are not part of the Unicode character set? I ask, because UTF-8 can encode every Unicode character, so a non-UTF-8 character cannot be inside Unicode. So how is this supported by Windoes then?

It should be Non-ASCII characters, sorry for my misrepresentation.
