### ISSUE TITLE
conversion to latin1

### ISSUE THREAD

**Issue by henripal** [jheinen/GR.jl#55]
Hi!!!
Conversion to latin1 fails for multibyte characters:
```
using Plots
gr()
scatter([0], [0], series_annotations = ["\u2200 or B"],
             xlims = (-.1, .1), ylims = (-.1,.1))
```
throws `BoundsError: attempt to access 6-element Array{UInt8,1} at index [7]`

I think it would be better to print garbled text in this case than throw an error, so I fixed it locally by changing
```
function latin1(string)
  b = convert(Array{UInt8}, string)
  s = zeros(UInt8, length(string))
...
```
to
```
function latin1(string)
  b = convert(Array{UInt8}, string)
  s = zeros(UInt8, length(b))
...
```
in `GR.jl`

Let me know if that's ok and I'll PR it!

Thanks!

**Comment by jheinen** [comment]
Looks good. Please PR it ...

Thanks a lot!

**Comment by jheinen** [comment]
There is no Latin-1 equivalent for the `forall` symbol. The only workaround is to use a LaTeX string, e.g. `scatter(randn(10),randn(10),xlabel="\$\\forall X\$")`.

Full Unicode support for `GR` is planned for a future release.

The `BoundsError` shouldn't happen, I will fix that and print a reasonable warning message.
