### ISSUE TITLE
Latest GR and GDAL versions can't be installed together

### ISSUE THREAD

**Issue by asinghvi17** [jheinen/GR.jl#551]
It looks like `GR_jll` restricts its libtiff compat to 4.5.1, whereas GDAL requires 4.7.0.

Is this a restriction on the library's end, or is it possible to loosen that compat and rebuild upstream?

**Comment by jheinen** [comment]
I made local tests with tiff 4.7.0 and it seems to work fine. I'll make a new GR release on Monday ...
