### ISSUE TITLE
Pkg.test("GR") fails on Julia v0.5 Windows x64

### ISSUE THREAD

**Issue by finmod** [jheinen/GR.jl#56]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.test("GR")
INFO: Testing GR
running C:\Users\Denis\.julia\v0.5\GR\test\ex.jl ...
running C:\Users\Denis\.julia\v0.5\GR\test\griddata.jl ...
ERROR: LoadError: unlink: resource busy or locked (EBUSY)
 in uv_error at .\libuv.jl:68 [inlined]
 in unlink(::String) at .\file.jl:382
 in #rm#7(::Bool, ::Bool, ::Function, ::String) at .\file.jl:107
 in macro expansion; at C:\Users\Denis\.julia\v0.5\GR\test\runtests.jl:14 [inlined]
 in anonymous at .\<missing>:?
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\Denis\.julia\v0.5\GR\test\runtests.jl, in expression starting on line 8
=================================[ ERROR: GR ]==================================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.5.0\bin\julia' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.5\GR\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
ERROR: GR had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258

julia>

**Comment by jheinen** [comment]
I just fixed this problem (7f12432). On Windows, any output file has to be explicitly closed before getting its status or trying to remove it.
