### ISSUE TITLE
Strange Contour Artifacts Only on Save

### ISSUE THREAD

**Issue by RankWinner** [jheinen/GR.jl#59]
Hi,

Been working on a project for a while, nearly finished now but there seem to be some weird artifacts that only appear when I try and save plots using savefig.

This is what one of my plots looks like when I just display it normally:

![capture3](https://cloud.githubusercontent.com/assets/11875157/25687412/eb4a5624-306d-11e7-82ea-29d01b9b59fa.PNG)

But when I save it using savefig("name.png") it randomly gets some strange artifacts:

![fig](https://cloud.githubusercontent.com/assets/11875157/25687430/10a4df34-306e-11e7-891e-8e5ce512d619.png)

I think a similar issue was noted here: https://github.com/jheinen/GR.jl/issues/34

Did anybody figure out a fix?

**Comment by jheinen** [comment]
Do you have an example script - probably with the required data files - to reproduce the problem?

**Comment by RankWinner** [comment]
Sure, excuse my code, it's still quite rough (ended up making a Gist as a demonstration, might be easier to just look at it instead of reading what I wrote: https://gist.github.com/RankWinner/f4b2b48c02bca3edae0b93483b6a1cb9 )

The configuration I used for those images was:
`[-0.416009 0.400346; -0.332775 -0.942973; 0.103662 -0.994593; -0.393716 -0.3875; 0.00462801 -0.557885; -0.530239 -0.847777; -0.838718 -0.544552; -0.116181 -0.993222; 0.352125 0.935912; 0.703057 -0.711051; 0.399918 -0.389485; 0.991166 -0.132616; -0.308169 0.951314; 0.952909 0.303115; 0.996185 0.0871884; -0.0861578 0.996266; 0.730764 0.682553; 0.134916 0.990843; -0.994258 0.106853; -0.0199588 0.563051; 0.554898 0.831872; 0.865567 0.500668; -0.842938 0.537975; -0.943606 0.331027; 0.843046 -0.537773; -0.512738 0.858505; 0.529117 -0.848544; 0.547083 0.0183195; 0.321895 -0.946744; -0.939961 -0.341121; -0.57325 0.00312208; -0.700035 -0.713954; -0.697646 0.716389; 0.940092 -0.340918; -0.00785041 0.00848953; 0.384766 0.419353; -0.992371 -0.12325]`

Just do something like `Min_Solution= ` what's above.

The code which produces the X, Y and Z mesh is:

```
function FindPotentialField(Min_Solution, GridSize=0.001,
        r::Union{Int, Float64}=1; lowerflag=true, lowerlvl=0.88)
    
    x = -r:GridSize:r; y = -r:GridSize:r
    X = repmat(x',length(y),1); Y = repmat(y,1,length(x)) # Makes mesh of X's and Y's
    
    points = Min_Solution; n = size(points, 1)
    
    Findrs(x, y, xc, yc) = begin
        sqrt((x-xc)^2 + (y-yc)^2)
    end
    
    FindPotential(x, y) = begin # Simplified as V = 1/r
        V = 0
        
        for i = 1:n
            V += 1/Findrs(x, y, points[i, 1], points[i, 2])
        end
        
        return V
    end
    
    RemoveOOB(X, Y, Z) = begin # V drops off towards 0 outside the disk, screws up scaling
        MeshRadii = sqrt((X.^2) .+ (Y.^2))
        
        for i = eachindex(MeshRadii)
            if MeshRadii[i] >= r*1 # Removes Z values outside the disk
                Z[i] = NaN
            end
        end
        
        return Z
    end
    
    LowerPotential(Z) = begin # Potential -> inf on top of points, must lower for plot
        stdv = std(Z[!isnan(Z)]); avg = mean(Z[!isnan(Z)])
        boundup = (avg + stdv); bounddwn = (avg - stdv)
        # Lowers max potential to mean+stddev 
        for z in eachindex(Z)
            if Z[z] > boundup*lowerlvl
                Z[z] = boundup*lowerlvl
            elseif Z[z] < bounddwn*(2-lowerlvl) && lowerflag # Optionally set minimum value as well
                Z[z] = bounddwn*(2-lowerlvl)
            end
        end
        
        return Z
    end
        
    Z = map(FindPotential, X, Y)
    
    Z = RemoveOOB(X, Y, Z)
    
    Z = LowerPotential(Z)
    
    return (x, y, Z, FindPotential)
end
```
And to then plot it:

```
function PlotPotential(Min_Solution, r::Union{Int, Float64}=1;
        lowerflag=true, lowerlvl=0.88)

    plot(Plots.partialcircle(0, 2π, 100, r), aspect_ratio=:equal,
        grid=false, border=false, ticks=false, legend=false)

    title!(string("Estimated Minimum Configuration for ",
            Int(size(Min_Solution, 1)), " Charges"))
    
    (X, Y, Z, FindPotential) = FindPotentialField(Min_Solution;
        lowerflag=lowerflag, lowerlvl=lowerlvl)
    
    annotate!([(0+r, 0-r,
        text(string("i: ", lowerlvl*100), 10))])
    
    contour!(X, Y, Z, fill=false)
    
    plt = scatter!(Min_Solution[:, 1], Min_Solution[:, 2], size=(750, 750))
    
    return plt
end
```

Then something like:

`PlotPotential(Min_Solution, lowerlvl=2)`

Will produce the correct plot. But using savefig("whatever") afterwards has the weird lines doing to the top left.

Here's a Gist where I test this out: https://gist.github.com/RankWinner/f4b2b48c02bca3edae0b93483b6a1cb9

And here's what the savefig bit produces:

![sol37-2](https://cloud.githubusercontent.com/assets/11875157/25703674/650c2bf8-30ce-11e7-929c-422a4f182762.png)

This happens both when just using straight GR, and when using Plots with GR as the backend.

**Comment by jheinen** [comment]
There are nan values in X and/or Y, which are not supported in all drivers. I will have to check, how (and where) to efficiently handle such coordinates / missing values in GR

**Comment by RankWinner** [comment]
Thanks for the quick reply.

I don't think there should be any NaN's in X or Y, I thought they'd only be in Z, since the X and Y which are plotted (this is my fault for being inconsistent with notation) are just the range `-r : GridSize : r`, capital X and Y are found with `repmat` and are only used with the map function to find Z.

But in the end lower-case `x` and `y` are returned to be plotted, so contour should basically be doing:

`contour(-r:GridSize:r, -r:GridSize:r, Z)`

Where `Z` is the only one with NaN values.

Are there any ways to not plot points other than using NaN?

**Comment by jheinen** [comment]
I fixed the problem in https://github.com/jheinen/gr/commit/cdf9fdcb357f6525ba348c89e4c4415f5cfcfc0d and triggered our Jenkins server to build new binaries - but this takes 1-2 hours.

**Comment by jheinen** [comment]
The updated binary distributions are ready to use. Please rebuild GR:
```julia
ENV["GRDIR"]=""
Pkg.build("GR")
```

**Comment by RankWinner** [comment]
Oh wow! Didn't expect such a quick reply, took a bit of a break from the project.

Thanks for the help, image saving works perfectly now, this should make what I'm doing much easier.

Do you have a donation option anywhere, for yourself/GR? I looked around but couldn't find one.

**Comment by jheinen** [comment]
Good to hear that it's working now.

No, there is no donation option. But you can help us by providing a script or a notebook file with corresponding data files for our example gallery ;-)
