### ISSUE TITLE
svg output off by one pixel

### ISSUE THREAD

**Issue by pfitzseb** [jheinen/GR.jl#63]
When saving a heatmap (this may or may not be the case for other plot types) as a svg, there's a `transform` on the embedded `<image>`, which is off by one pixel in x- and y-direction:
`transform="translate(39,7)"`:
![off by one](https://user-images.githubusercontent.com/6735977/27225196-6ac59344-5299-11e7-953c-9df16246ca0a.png)
`transform="translate(40,8)"`:
![fixed](https://user-images.githubusercontent.com/6735977/27225204-6fcc33a2-5299-11e7-8766-a5b0719617db.png)

Edit:
Unrelated, but the x and y ticks are displayed *behind* the heatmap, which doesn't seem desirable?

**Comment by jheinen** [comment]
Fixed in https://github.com/jheinen/gr/commit/ff3266f9cbd97f1e61ef4db6ac5b5f1c284e0917 . The CI build is triggered - new run-time will be available soon ...
