### ISSUE TITLE
GKS: Movie support not compiled in

### ISSUE THREAD

**Issue by stefanocampanella** [jheinen/GR.jl#66]
Recently I am no more able to produce a video output (such as mp4 or gif) with GR in Julia. If I try to open a video device with `beginprint("test.mov")` then I get the following message: `GKS: Movie support not compiled in`

Unfortunately I can't tell whether it depends on the upgrade of Julia (v0.6) or GR binaries (v0.25).  I am on Archlinux.

**Comment by jheinen** [comment]
It seems there was a problem on our build server. I'll check this ...
Which binary did you use before? Generic Linux?

**Comment by stefanocampanella** [comment]
Yes, the same I use now. That is the one that are downloaded automatically when I build the GR.jl package.

**Comment by jheinen** [comment]
All binaries have been rebuilt - some of them were built without movie support due to a download problem. Pls checkout GR master and rebuild:
```julia
Pkg.checkout("GR")
ENV["GRDIR"] = ""
Pkg.build("GR")
```
This should solve the problem.
