### ISSUE TITLE
underscores and strings in GR backend

### ISSUE THREAD

**Issue by gdkrmr** [jheinen/GR.jl#68]
Underscores do not have a consistent behaviour across backends:

```julia
julia> gr()
julia> Plots.plot(1:10, 1:10, title = "asdf_asdf")
```
![screenshot from 2017-07-27 08-32-14](https://user-images.githubusercontent.com/12512930/28657201-2f72d61c-72a6-11e7-8aba-803ddde2b657.png)

```julia
julia> plotlyjs()
julia> Plots.plot(1:10, 1:10, title = "asdf_asdf")
```
![screenshot from 2017-07-27 08-33-31](https://user-images.githubusercontent.com/12512930/28657221-4ed2bd7e-72a6-11e7-9781-3b49637124c7.png)

and there are bugs in the GR backend:
```julia
julia> gr()
julia> Plots.plot(1:10, 1:10, title = "asdf_asdf_asdf")
duplicate expression
```
doesn't print a title:

![screenshot from 2017-07-27 08-34-36](https://user-images.githubusercontent.com/12512930/28657245-6e3e99da-72a6-11e7-9c48-38b8d00bfdef.png)

what works is something like this:
```julia
julia> gr()
julia> Plots.plot(1:10, 1:10, title = "asdf_{asd}f_asdf")
```
![screenshot from 2017-07-27 08-36-22](https://user-images.githubusercontent.com/12512930/28657288-ade3383e-72a6-11e7-94a0-272c96bf0e35.png)

I guess, this is some kind of simple Latex formatting, it is probably better to either turn Latex formatting on and use the full syntax or not do it at all.

The issue is also quite annoying when you have to do a lot of diagnostic plots with strings taken from some database and the words are concatenated by underscores.

**Comment by jheinen** [comment]
Fixed in https://github.com/JuliaPlots/Plots.jl/pull/1003
