### ISSUE TITLE
clearws() doesn't work as intended in IJulia

### ISSUE THREAD

**Issue by saschatimme** [jheinen/GR.jl#74]
In an IJulia enviroment `clearws()` should call `IJulia.clear_output(true)`, but it in my tests the constant `have_clear_output` is always `false` (Implementation is [here](https://github.com/jheinen/GR.jl/blob/master/src/GR.jl#L379-L381))
I think the problem is the `__precompile__` flag, i.e. if the precompilation happens in a non `IJulia` enviroment the cached version will always set the flag to `false`.

I think either the precompilation has to be dropped or the flag has to be set in a more dynamic way (e.g. during a call to `inline()`).

**Comment by jheinen** [comment]
... should be fixed with https://github.com/jheinen/GR.jl/commit/8657c0a7d3d89fde4adb74a86a2e31443044fda6
