### ISSUE TITLE
Two problems with backslash greek letters

### ISSUE THREAD

**Issue by improbable22** [jheinen/GR.jl#77]
Here the title is truncated to "before f", and the space after \beta is swallowed: 
```
using Plots
plot(rand(20), lab="a = \\beta = c", title="before f(\\theta) and after")
```
This was in IJulia / Jupyter. The space after \beta is fine if I save a PDF, but if I save as SVG then it has the same problem: `savefig("test.svg")`. The truncation of the title however is the same, and only occurs with round brackets.  

This only happens with the GR background in Plots.  Here is an example of the same problems directly in GR: 
```
using GR
inline()

x = 0:pi/100:2*pi
y = sin.(x) + 2 .* x

plot(x,y,title="sin(\\theta) + 2\\theta", xlabel="\\theta", ylabel="a + 1 + \\beta + 1 + c")
```

I can avoid this by doing the labels in Latex, `using LaTeXStrings` or just as below, but then they are printed in the Computer Modern font which I'd like to avoid -- often simple greek letters are enough.
```
plot(rand(20), lab="\$ a = \\beta = c \$", title="\$ \\mathrm{ before \\ }f(\\theta)\\mathrm{ \\ and \\ after} \$")
```
(This was [plots.jl #1150](https://github.com/JuliaPlots/Plots.jl/issues/1150) )

**Comment by lnacquaroli** [comment]
Do you know where is `GR.jl` taking the LaTeX fonts settings from? Because you could customize this with the `pyplot()` backend in `Plots.jl` through `PyCall` (https://github.com/JuliaPlots/Plots.jl/issues/997, not recommended) or through the matplotlibrc file, but I could never done it in `gr()`.

**Comment by jaakkor2** [comment]
Putting backslashes before parenthesis helps.
```
using Plots
plot(rand(20), lab="a = \\beta = c", title="before f\\(\\theta\\) and after")
```

**Comment by jheinen** [comment]
@lnacquaroli : the LaTeX body template is currently static.
https://github.com/jheinen/gr/blob/ee94daa553c1c4e58a1ee70eb148b08c4792f3e4/lib/gr/gr.c#L7255-L7267

**Comment by lnacquaroli** [comment]
@jheinen thanks for the notice.

**Comment by improbable22** [comment]
@jaakkor2 thanks! Backslashes in front of the brackets solves this for me.
