### ISSUE TITLE
Feature request: simple Matlab/Octave-like functions

### ISSUE THREAD

**Issue by simulkade** [jheinen/GR.jl#8]
Hi Josef,

Perhaps it is too much to ask, but I was wondering if it is possible for you to add a few Matlab-like functions to GR, something that can be called for daily quick visualization of 2D and 3D data. Or alternatively provide a few minimum working example in the form of a notebook. 
There are a few that comes to my mind that I use most of the time in Matlab/octave/matplotlib without touching the default output ([here](https://github.com/simulkade/FVTool/tree/master/Visualization) are some of the octave code that I have written in Octave/Matlab for visualization of data on different coordinates)
`plot(x,y)`: is already there.
`xlabel(string)`: label for the x axis
`ylabel(string)`: label for the y axis
`surf(x,y,z)`: 3D plot similar to surface with a default view and axis, where x and y are vectors and z is a 2D array
`pcolor(x,y,z)`: 2D visualization of 3D data with a default colormap
`contour(x,y,z)` and `contourf(x,y,z)`
`slice`: would be fantastic!
[List of octave 3D visualization functions](https://www.gnu.org/software/octave/doc/interpreter/Three_002dDimensional-Plots.html)

Thanks a lot in advance.

**Comment by jheinen** [comment]
Hil Ali,

your request is high on our TODO list. I hope to add basic support in one of the next releases (v0.16.0). Most of the functionality is available - it "only" has to implemented in a convenient way both for Julia and Python ...

**Comment by simulkade** [comment]
Thanks a lot Josef for your quick reply. I'm looking forward to the new versions of GR.

**Comment by jheinen** [comment]
... planned for v0.18.0 - I promise ;-)

**Comment by simulkade** [comment]
Looking forward to using it :+1:

**Comment by simulkade** [comment]
I tried the new plot function:

```
x=collect(linspace(0,10,100))
y=sin(x);
plot(x,y)
```
I get this on Julia 0.4.2
```
GKS: unable to load font H���
Union{}
```
plot2d on the other hand works fine.

**Comment by jheinen** [comment]
The master branch now works fine with 0.4.2, but I still could not reproduce the GKS error (unable to load font).

**Comment by simulkade** [comment]
Thanks. It works fine, but the warning is still there (on another laptop, Linux mint 17.3)
```
GKS: unable to load font HP�+
```
or 
```
GKS: unable to load font x-
```
One more observation:I have to run `xlabel("x axis")` before the plot function to see the label on the x axis. Just a minor difference with matplotlib and Matlab.

**Comment by simulkade** [comment]
Dear Josef,

I was wondering if there is any alternative to the following PyPlot commands in GR:
```
x=collect(linspace(0,3,10))
y=collect(linspace(0,2*pi,10))
subplot(111, polar="true")
pcolor(y,x,rand(10,10))
```
![figure_1](https://cloud.githubusercontent.com/assets/1881542/15270006/418ea040-1a11-11e6-8c41-02b03209909e.png)

basically, it is a 2D surface plot in polar coordinate.

**Comment by jheinen** [comment]
I will have to check, which Matplotlib commands support polar coordinates It seems, that I should move this functionality into the GR library. Right now, it is implemented in the wrapper part. That would be a major change - but I put it onto the wish list.

**Comment by simulkade** [comment]
Thanks a lot.
