### ISSUE TITLE
Pkg.build seems broken on Redhat/CentOS

### ISSUE THREAD

**Issue by oschulz** [jheinen/GR.jl#80]
With the current GR.jl v0.24.0,`Pkg.build` fails for me (on CentOS 7) with

```
LoadError: failed process: Process(`curl -L -f -o downloads/gr-0.27.0-Redhat-x86_64.tar.gz http://gr-framework.org/downloads/gr-0.27.0-Redhat-x86_64.tar.gz`, ProcessExited(22)) [22]
```

There doesn't seem to be a gr-0.27.0 RedHat release in the download directory. I realize this is kind of an upstream issue, but I thought I report it here since GR.jl refers to gr-0.27.0 specifically (and since there's personnel overlap between GR and GR.jl anyhow ;-) ).

**Comment by jheinen** [comment]
This problem should be fixed now.

**Comment by oschulz** [comment]
Thanks for the quick reaction! I still have trouble though - `Pkg.build("GR")` still results in

```
LoadError: failed process: Process(`curl -L -f -o downloads/gr-0.27.0-Redhat-x86_64.tar.gz http://gr-framework.org/downloads/gr-0.27.0-Redhat-x86_64.tar.gz`, ProcessExited(22)) [22]
```

**Comment by jheinen** [comment]
Sorry for the confusion and give it another try ...

**Comment by oschulz** [comment]
Perfect, thanks a lot for the quick fix, Josef!
