### ISSUE TITLE
Flickering when running particles.jl example (or any fast calls to clearws())

### ISSUE THREAD

**Issue by samstewart** [jheinen/GR.jl#83]
I'm running ArchLinux, so this could be my problem, not a problem of the framework, but I'm wondering if anyone else has noticed flickering when calling clearws() in an animation.

Double buffering would fix this which I'm happy to implement if others have this same problem. It's quite distracting for simulations.

**Comment by jheinen** [comment]
Please enable double buffering:
```bash
export GKS_DOUBLE_BUF=1
julia ...
```

**Comment by samstewart** [comment]
Great, thank you for the quick reply. Do you think there is a nice way to integrate this into GR.jl? If so, I'm happy to do so.

**Comment by jheinen** [comment]
There are several options that should probably be read from a user-specific resource and/or configuration file (sth like ~/.grrc). Such a feature is already on our radar :-)

**Comment by samstewart** [comment]
Ah, ok. If I have some time, maybe I'll make a pull request. Thanks for all the help and an amazing framework!
