### ISSUE TITLE
Using GR as backend to Plots fails to plot in JuliaBox

### ISSUE THREAD

**Issue by gaomrx** [jheinen/GR.jl#86]
I am using Julia version 0.6.0 on juliabox.com and Plots version 0.13.1. 
![image](https://user-images.githubusercontent.com/6380557/33146486-536c88bc-cf92-11e7-915f-25f0aac02f81.png)

**Comment by jheinen** [comment]
As a (quick) workaround, you could change the `label` argument:
```julia
label=["No" "1E-1" "1E-2" "1E-3" "1E-4" "1E-5"]
```

**Comment by jheinen** [comment]
... should be fixed with https://github.com/JuliaPlots/Plots.jl/pull/1260

**Comment by jheinen** [comment]
Merged.
