### ISSUE TITLE
Running example gtk_ex.jl fails

### ISSUE THREAD

**Issue by bspinnler** [jheinen/GR.jl#91]
Running example gtk.jl gives me:

```
julia> include("gtk_ex.jl")

(process:12573): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
GKS: dlopen(/Users/spb/.julia/v0.6/GR/src/../deps/gr/lib/cairoplugin.so, 1): Library not loaded: /Users/gitlabci/builds/06a5c4ed/0/Scientific-IT-Systems/gr/3rdparty/cairo/../build/lib/libcairo.2.dylib
  Referenced from: /Users/spb/.julia/v0.6/GR/deps/gr/lib/cairoplugin.so
  Reason: image not found
```

This is on
```
Version 0.6.1 (2017-10-24 22:15 UTC)
Official http://julialang.org/ release
x86_64-apple-darwin14.5.0
```

The same error occurs with Gtk and GR updated to
```
julia> Pkg.status.(["Gtk", "GR"])
 - Gtk                           0.13.1
 - GR                            0.25.0
```

as well as with GR on current master:
```
julia> Pkg.status.(["Gtk", "GR"])
 - Gtk                           0.13.1
 - GR                            0.25.0+            master
```

Needless to say, there is no user 'gitlabci' on my system. Seems there is some hard coded path in cairoplugin.so. Or is my installation broken?

Bernhard

**Comment by peterahrens** [comment]
I am also having this issue. + 1

**Comment by EdgarMCR** [comment]
I also have encountered that issue on Mac OSX, with the vanilla Julia install when using Plots with the GR backend. Happy to provide details if that would be useful.

**Comment by jheinen** [comment]
The problem with Gtk on macOS is, that there are so many (different) packages ((MacPorts, Homebrew, Fink), installation options  and dependencies.

@FlorianRhiem : Can this issue be fixed using `install_name_tool` ?

Are you starting a project from scratch? If so, I'd give Qt a chance. There are official packages (provided by qt.io) and we successfully use it on all platforms (macOS, Windows, Linux).

**Comment by FlorianRhiem** [comment]
This was a bug in our CI configuration. The cairoplugin is statically linked to libcairo on Linux and Windows, but on macOS we dynamically link to `libcairo.2.dylib`, so when packaging the runtime for macOS, we need to add the dylib and adjust the path in `cairoplugin.so`.

I have committed a fix for this and after a few more tests @jheinen will release a new version of GR without this issue.

**Comment by bspinnler** [comment]
Thanks. Appreciate your efforts. Looking forward to a new version. Will test it when it becomes available.

Thanks also for the Qt hint. However, for a current small project Qt seemed like an overkill to me. Also I haven't found a lot of examples how to use Qt with Julia. I've come across PySide and QML.jl. Is this what people are using? Any pointers to other projects or examples are appreciated.
