### ISSUE TITLE
Pkg.build broken on CentOS, download of GR fails

### ISSUE THREAD

**Issue by oschulz** [jheinen/GR.jl#95]
Pkg.build is currently broken on CentOS, the download of the GR binary fails.

"http://gr-framework.org/downloads/" does list "gr-latest-Redhat-x86_64.tar.gz", but "gr-0.30.0-Redhat-x86_64.tar.gz" is missing.

**Comment by jheinen** [comment]
Thank you - I just added the missing links ...

**Comment by oschulz** [comment]
Sorry for the late reply - many thanks for the quick fix!
