### ISSUE TITLE
GKS: svgplugin.dll: can't load library, error 126 (0x7e)

### ISSUE THREAD

**Issue by HamletFr** [jheinen/GR.jl#97]
I get the following error:

`GKS: svgplugin.dll: can't load library, error 126 (0x7e)`

> Windows 10 Pro x64
> Atom 1.24.1 x64
> Julia 0.6.2
> Plots.jl 0.15
> GR.jl 0.28.0

I tried a rebuild of the GR and Plots package, but it did not change anything. Any ideas? Thanks!

**Comment by jheinen** [comment]
Did you already:
```
ENV["GRDIR"]=""
Pkg.build("GR")
```
BTW: GR v0.29.0 has just been tagged ...

**Comment by HamletFr** [comment]
Unfortunately that did not help ... :(

With Pkg.checkout("GR") I still stay on v.028.0. Should v.0.29.0 solve my problem?

**Comment by jheinen** [comment]
No - 0.28.0 should also work - Strange.
Are you using the correct run-time?
```
import GR
GR.version()
```
... should give "0.30.1"

**Comment by HamletFr** [comment]
Yes, thats what I have ...

**Comment by jheinen** [comment]
0.30.0 should work, too. I'll have to leave office now but I'll check it this evening ...

**Comment by jheinen** [comment]
I found a serious bug in the plugin code (on Windows systems). I'll check the new version when the CI has finished.

**Comment by jheinen** [comment]
GR.jl v0.30.0 is tagged and will be merged soon by the Julia project collaborators. This release will fix the plugin problem.

**Comment by HamletFr** [comment]
v.30.2.post5 solved the problem! Thanks!
